### ISSUE TITLE
WampProcedureAttribute should be optional

### ISSUE THREAD

**Issue by BrannonKing** [Code-Sharp/WampSharp#104]
I don't like having to decorate my primary service interfaces. They live in a very "portable" project that I like to keep reference-free. I think we can make the WampProcedure attribute be optional. Use the method name as default. If it conflicts append the parameter count. If that conflicts throw an exception stating that the method names need to be disambiguated.

**Comment by darkl** [comment]
This is already supported - just pass your own Registration Interceptor to the RegisterCallee Method.
