### ISSUE TITLE
Dependency issue: Ix-Async does not have support for WinRT

### ISSUE THREAD

**Issue by PaulosV** [Code-Sharp/WampSharp#109]
In v1.2.3.12-beta, commit e476bb9a63c4198bbf763ab9ecd0e55593901a7b replaced WampSharp's queue mechanism to a Ix-Async-based one. Unfortunately, Ix-Async is not available for WinRT-based platforms, which is Windows Store apps (either Win or WP) and UWP apps, and thus the latest version of WampSharp cannot be added to the project.

I had to go with v1.2.3.11-beta. Although I believe that for a client application, this should not be a big issue, right?

**Comment by darkl** [comment]
Hi,

This sounds odd, since the Ix-Async package contains a folder named "portable-windows8+net45+wp8". Also, the pcl build succeeds. Also @sidhant stated in [this issue](https://github.com/Code-Sharp/WampSharp-docs/issues/1) that the dev version works fine for him for a UWP project.

Are you sure you're not doing anything wrong?

Elad

**Comment by PaulosV** [comment]
I'm sorry that I left you without an answer for so long.
This is the error that I currently get when trying to include WampSharp 1.2.3.14-beta using NuGet:
```
Could not install package 'Ix-Async 1.2.5'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Which looks like an issue with Ix-Async packaging and not your package in particular. I'll try to file a bug there.

**Comment by Luke47** [comment]
@PaulosV did you solve this issue already? Because I have the same issue right now. Thanks :)

**Comment by PaulosV** [comment]
@Luke47 Not yet, I went with using older version of WampSharp, but lately I needed to compile my own version because of another (WP81 specific) bug. If you do compilation from source, then you'll be able to include the result DLL into the project. The issue with Ix-Async is merely a NuGet formality.

**Comment by Luke47** [comment]
Oh okay, will try that. Thank you very much! :)

I also tried using older versions but it seems it does not work with the WAMP V1 protocol. Which WAMP version do you use? V1 or V2?

**Comment by PaulosV** [comment]
I'm using V2. V1 has its own set of packages and I think it has been available before as well, most likely even before V2. More in the docs - https://github.com/Code-Sharp/WampSharp-docs - but I'd move that discussion somewhere else, so we don't clutter this issue ;)

**Comment by darkl** [comment]
WampSharp v1.2.4.18-beta now uses System.Threading.Tasks.DataFlow instead of Ix-Async.

Elad

**Comment by PaulosV** [comment]
That fixed the issue completely, thank you!
