### ISSUE TITLE
Problems with Connection Broken

### ISSUE THREAD

**Issue by LordMandrake** [Code-Sharp/WampSharp#114]
Hi, I implemented WAMPSharp in a solution with a Heroku App with Crossbar.IO
Everything works fine (except that I need to open a "ping channel" to keep the connection alive) but I encountered with a problem that I couldnt resolve yet ...

I tried to unplug the ethernet cable to see what happen and I noted that the channel send a message that the connection is broken and bla bla bla. I detected these event  but I can not make the channel connect again. Could you help me ???

This is the code:

	private DefaultWampChannelFactory g_CbChannelFactory;
	private IWampChannel g_CbChannel;
	private IWampRealmProxy g_CbRealm;
	private IWampClientConnectionMonitor g_CbMonitor;
	private Func<Task> g_CbDeviceConnect;
	private IDisposable g_CbDeviceSuscriber;
	private IDisposable g_CbPingSuscriber;
	private WampChannelReconnector g_CbPingReconnector;
	private WampChannelReconnector g_CbDeviceReconnector;
	private delegate void PingDetectedDelegate(string text);
	
	private void frmMain_Load(object sender, EventArgs e)
	{
		#region [ Config. Crossbar.IO ]
		g_CrossbarUrl = ConfigurationManager.AppSettings["Crossbar.Url"];
		g_CrossbarRealm = ConfigurationManager.AppSettings["Crossbar.Realm"];
		g_CbTopicResponse = ConfigurationManager.AppSettings["Crossbar.Response"];
		g_CbTopicPing = ConfigurationManager.AppSettings["Crossbar.Ping"];
		g_CbChannelFactory = new DefaultWampChannelFactory();
		g_CbChannel = g_CbChannelFactory.CreateJsonChannel(g_CrossbarUrl, g_CrossbarRealm);
		g_CbRealm = g_CbChannel.RealmProxy;
		g_CbMonitor = g_CbRealm.Monitor;
		g_CbMonitor.ConnectionBroken += CbMonitor_ConnectionBroken;
		g_CbChannel.Open().Wait(10 * 1000);
	
		g_CbDeviceSuscriber = null;
		g_CbPingSuscriber = null;
		#endregion
		
		PingSuscriber();
		DeviceSuscriber();
	}
	
	private async void PingSuscriber()
	{
		g_CbDeviceConnect = async () =>
		{
			g_CbPingSuscriber = g_CbRealm.Services.GetSubject<string>(g_CbTopicPing)
				.Subscribe(x => 
					{
						Thread ping = new Thread(new ThreadStart(PingDetected));
						ping.Start();
					});
	
			var subscriptionTask = g_CbChannel.RealmProxy.Services.RegisterSubscriber(g_CbPingSuscriber);
			var asyncDisposable = await subscriptionTask;
		};
	
		g_CbPingReconnector = new WampChannelReconnector(g_CbChannel, g_CbDeviceConnect);
		g_CbPingReconnector.Start();
	}
	
	private async void DeviceSuscriber()
	{
		string l_CrossbarDevice = string.Format("com.rcpcom.cloud.{0}", g_DeviceId);
	
		g_CbDeviceConnect = async () =>
		{
			g_CbDeviceSuscriber = g_CbRealm.Services.GetSubject<MsgPackAction>(l_CrossbarDevice)
				.Subscribe(x =>
				{
					//TODO: envio la accion a un metodo para ejecutarlas
					g_ActionReceived = x;
					Thread execAction = new Thread(new ThreadStart(ActionDetected));
					execAction.Start();
				});
	
			var subscriptionTask = g_CbChannel.RealmProxy.Services.RegisterSubscriber(g_CbDeviceSuscriber);
			var asyncDisposable = await subscriptionTask;
		};
	
		g_CbDeviceReconnector = new WampChannelReconnector(g_CbChannel, g_CbDeviceConnect);
		g_CbDeviceReconnector.Start();
	}
	
	private void PingDetected()
	{
		PingDetected(DateTime.Now.ToString("dd/MM/yy HH:mm:ss"));
	}
	
	private void PingDetected(string fecha)
	{
		// InvokeRequired required compares the thread ID of the
		// calling thread to the thread ID of the creating thread.
		// If these threads are different, it returns true.
		if (this.txtCbPing.InvokeRequired)
		{
			PingDetectedDelegate d = new PingDetectedDelegate(PingDetected);
			this.Invoke(d, new object[] { fecha });
		}
		else
		{
			this.txtCbPing.Text = fecha;
		}
	}
	
	private void ActionDetected()
	{
		ActionDetected(g_ActionReceived);
	}
	
	private void ActionDetected(MsgPackAction mAction)
	{
		// InvokeRequired required compares the thread ID of the
		// calling thread to the thread ID of the creating thread.
		// If these threads are different, it returns true.
		if (this.lstCbDevice.InvokeRequired)
		{
			ActionDetectedDelegate d = new ActionDetectedDelegate(ActionDetected);
			this.Invoke(d, new object[] { mAction });
		}
		else
		{
			string txt = mAction.Action;
			lstCbDevice.Items.Add(txt);
			ExecuteAction(mAction);
		}
	}

Thanks a lot !!!

**Comment by darkl** [comment]
Hi @LordMandrake,

I didn't try your code, but it seems that your usage is a bit different than the one specified in the documentation: You don't call await channel.Open().ConfigureAwait(false); inside the reconnector callback. Please try moving the channel.Open() to the reconnector code as demonstrated [here](https://github.com/Code-Sharp/WampSharp-docs/blob/master/WAMP2/Client/WampChannelReconnector.md).

Elad

**Comment by LordMandrake** [comment]
But I need to open 2 suscriptions per channel. 1 for ping and 1 for thouse "actions" that I need to capture. If I move the  channel.Open() inside the reconnector code, I could not "add" the ping channel to keep connection alive ...

**Comment by darkl** [comment]
Hi,

It's fine, just make both subscriptions in the same reconnector callback.

By the way, you can get rid of your pings by setting the WebSocket ping
interval to a smaller interval. If you'd like to do this, I can elaborate.

Elad

**Comment by LordMandrake** [comment]
Thanks for all Elad,

I dont understand anything of WAMPSharp, WebSockets, Crossbar.IO, Heroku & all king of this but the owner of the company WANTS an app that do that.
I will appreciate all you can bring me ...

We need to make a windows service that "talks" to an app with WAMP & Crossbar router. The messages are randomly generated by the app and the windows service listen it and response in consequence.

I hope be clear. My english is not too good !!

Thanks a lot !

**Comment by darkl** [comment]
Hi @LordMandrake,

Here is a sample how to create a connection with PingInterval of 10 seconds.

```csharp
private static IWampChannel GetWampChannel(string serverAddress)
{
    DefaultWampChannelFactory channelFactory =
        new DefaultWampChannelFactory();

    IWampChannel wampChannel =
        channelFactory.ConnectToRealm("realm1")
                      .WebSocketTransport(subprotocolName => CreateWebSocket(subprotocolName, serverAddress))
                      .JsonSerialization()
                      .Build();


    return wampChannel;
}

private static WebSocket CreateWebSocket(string subprotocolName, string serverAddress)
{
    WebSocket result = new WebSocket(uri: serverAddress,
                                  subProtocol: subprotocolName,
                                  version: WebSocketVersion.None);

    result.AutoSendPingInterval = 10;

    return result;
}
```

Elad

**Comment by LordMandrake** [comment]
Thanks Elad, I will try this and I will keep you posted !!!

Thanks again !!!

**Comment by LordMandrake** [comment]
Elad,

I was trying your code but I havent some mothods that you describe. This example is with v1 or v2 version of WAMPSharp ???

**Comment by darkl** [comment]
Hi,

My apologies, please add a using directive to WampSharp.V2.Fluent. (using
WampSharp.V2.Fluent;)

Elad

**Comment by LordMandrake** [comment]
Elad,

I tried your methods and works perfect with old code that I have !!! But I have a new question, how I create methods that send or receive messages ???

Thanks a lot !!!
Gustavo.-

**Comment by darkl** [comment]
Hi Gustavo,

I'm not sure I understand your question. What exactly are you trying to do?

Elad

**Comment by LordMandrake** [comment]
Elad,

I'm trying to make 2 subscriptions subject. One for send "messages" (objects) and other to listen those messages.
Do you understand what I mean ??

Thanks,
Gustavo.-

**Comment by darkl** [comment]
You can publish messages to a topic using the OnNext method of the
IWampSubject interface. Please see documentation as well.

Elad

**Comment by LordMandrake** [comment]
Elad,
I wrote both, but I don't know wich is wrong because I don't receive anything ...

Suscribe

    Func<Task> g_CbDeviceConnect;
    IDisposable g_CbDeviceSuscriber;
    WampChannelReconnector g_CbDeviceReconnector;
    IWampRealmProxy g_CbRealm;
    
    string l_CrossbarDevice = "cloud";
    
    g_CbRealm = g_CbChannel.RealmProxy;
    
    g_CbDeviceConnect = async () =>
    {
    	g_CbDeviceSuscriber = g_CbRealm.Services.GetSubject<MsgPackAction>(l_CrossbarDevice)
    		.Subscribe(x =>
    		{
    			var tmp = x;
    		});
    
    	var subscriptionTask = g_CbChannel.RealmProxy.Services.RegisterSubscriber(g_CbDeviceSuscriber);
    	var asyncDisposable = await subscriptionTask;
    };
    
    g_CbDeviceReconnector = new WampChannelReconnector(g_CbChannel, g_CbDeviceConnect);
    g_CbDeviceReconnector.Start();


Publish

	ISubject<string> subjectResponse = g_CbRealm.Services.GetSubject<string>(l_CrossbarDevice);
	subjectResponse.OnNext("OK");

Note that some variables are globals for both methods.

**Comment by darkl** [comment]
Hi Gustavo,

By default, publications made by the client aren't received by the client.

In order to receive them you need to publish with PublishOptions
ExcludeMe=false. Please see Raw Publisher documentation for the usage.

Elad

**Comment by LordMandrake** [comment]
Elad,
Let me introduce you on what are we trying to do. We need to make 2 apps. One is a "Host" that has a publish topic to other/s app (windows services) and a subscription to a channel whose "listen" those other/s apps.
The other apps (windows service) has a subscription topic where receives the messages sent by the host (this topic is unique for each app) and a publish topic (which is general for all the apps) where response those messages that received.

Could you understand what I trying to do ?

So, in fact with this, we need both methods on each app, publish and subscribe. And keep both alive ...

**Comment by darkl** [comment]
Please try the samples included in the tutorials of Publisher/Subscriber,
these should work. The only thing is that you won't receive messages that
were published by yourself (ie published by the channel the subscription
was made) unless you set ExcludeMe=false. (But for separate processes this
should work fine of course)

Elad

**Comment by LordMandrake** [comment]
OK, I keep trying to make it ...
Thanks for all !!!
