### ISSUE TITLE
PluginLoader with WampHost

### ISSUE THREAD

**Issue by mikos7** [Code-Sharp/WampSharp#115]
This issue might not be a WampSharp issue and if so, I apologies for polluting this forum (but I ask here since it relates to WampSharp and I guess @darkl is greatly qualified to answer).

The plugin loader class I have built implements an interface with WampProcedure methods and has a private WampHost. It works great when invoked during application startup. But when invoking it from a WampProcedure I get the exception below. The exception is thrown when accessing the newly created plugin AppDomain in the AddPlugin method (WampProcedure: "ActivatePlugin"). 
Class file attached: [PluginLoader.txt](https://github.com/Code-Sharp/WampSharp/files/90173/PluginLoader.txt)

What to do..?

Kind regards, Mikael

 Exception:

```c#
System.Runtime.Serialization.SerializationException: Typen WampSharp.V2.WampInvocationContext i sammansättningen WampSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null är inte deklarerad som serialiserbar.

```

The text in Swedish tells that “PublicKeyToken” is not declared as serializable.

**Comment by darkl** [comment]
Hi @mikos7,

The issue seems to be that WampInvocationContext isn't serializable but it is set as a value of CallContext. This does trouble since you create a new AppDomain in the application, and then this value is serialized/deserialized.

Will try to send to release a patch for this in the weekend.

Elad

**Comment by darkl** [comment]
Fixed

**Comment by mikos7** [comment]
Same issue with WampSharp.V2.Core.Contracts.InvocationDetails

**Comment by darkl** [comment]
Hi @mikos7,

You are right. I'll try to fix this on the weekend.

Elad

**Comment by darkl** [comment]
@mikos7, should work now.
