### ISSUE TITLE
Possible AccessViolationException in WampSharp.Windows when running on WP (ARM)

### ISSUE THREAD

**Issue by PaulosV** [Code-Sharp/WampSharp#122]
When running on Windows Phone ARM devices, it's possible to run into `AccessViolationException` after opening connection, when receiving message when using text JSON connection (with Newtonsoft.Json and `CreateJsonChannel`).

Using PCL version with **WampSharp.Default.Client** installed, either on the latest version or just a few versions back to 1.2.2.11-beta.

In `WampSharp.Windows\Windows\MessageWebSocketTextConnection.cs`, line 31. This line throws an exception.
https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/Default/WampSharp.Windows/Windows/MessageWebSocketTextConnection.cs#L31

    WampMessage<TMessage> message = mTextBinding.Parse(frame);

Here's a clue, and it might be wrong: The `OnMessageReceived` handler is linked directly as an event handler of `Windows.Networking.Sockets.MessageWebSocket`. I believe this Windows websocket implementation internally operates on a different thread (maybe somehow protected), and therefore the thread might not have the same level of access to the functions of instances whose class originates in different assembly, or even on an UI thread. (?)

And, apparently, there's a difference between running it in Debug and Release, but that only showed when doing it through the NuGet package (!) - Release crashed, Debug did not. But when doing it from the source, both crashed. Maybe is there some difference in protection levels between these two?

So when I rewrite that part as this:

    await Task.Run(() => {
        WampMessage<TMessage> message = mTextBinding.Parse(frame);
        RaiseMessageArrived(message);
    });

the whole thing starts to work again.

Just doing the `Task.Run` without awaiting it also throws an exception, though a different one (`ExecutionEngineException`), and the app forcibly shuts down. The usual UI thread marshalling through `CoreWindow.GetForCurrentThread().Dispatcher` also caused the `AccessViolationException`, so I'm not really sure why it's happening.

This is one of the more interesting exceptions lately.  :-)  I hope someone can provide some insight on why it's actually happening. I'll also post a miniproject where you can see the error clearly.

**Comment by darkl** [comment]
Hi @PaulosV,

Very interesting findings.

After you'll post that miniproject, I'll try to modify to be WampSharp independent, and then you can probably ask some Microsoft guys about this error.

Best regards,
Elad

**Comment by PaulosV** [comment]
Here's the smal project that's causing the issue. Here it actually causes DataMisalignedException, not AccessViolationException. My attempts to analyze that exception were not successful so far.

Exception happens when built with Debug|ARM or Release|ARM.

[DataMisalignedException-App2.zip](https://github.com/Code-Sharp/WampSharp/files/148201/DataMisalignedException-App2.zip)

**Comment by LanceMcCarthy** [comment]
Debugging natively provides a little more information:

System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.
   at WampSharp.Windows.MessageWebSocketTextConnection`1.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at App2.WsClient.<ConnectAndAuthenticateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by darkl** [comment]
I can't make the example run on my machine, it complains about HyperV
emulator. Maybe will try something later.

Maybe I'm not using the right MessageWebSockets methods? Perhaps we should
use the MessageWebSocket as demonstrated on this article
<https://msdn.microsoft.com/en-us/library/windows/apps/mt186447.aspx>?

Elad

**Comment by PaulosV** [comment]
@LanceMcCarthy, thanks, that confirms the location of the problem.
@darkl, the error only appears when running on a real ARM device, I already tried the emulator before and it did not happen for me, while it did happen on four Lumias (925, 950XL and other two testing devices. BTW, the app with this error passed Store technical tests and went to private Store beta. :) )

Using `System.IO.Stream` should be perfectly fine, in fact I tried to exchange it for `DataReader` (from the sample) right now and the same exception occurred.

**Comment by PaulosV** [comment]
Follow-up: I've written my own stub text parser and formatter, and it seems that I've excluded Json.NET as a source of issues. It also happens when using my own text parser placed in my own project.

**Comment by darkl** [comment]
@PaulosV, we can try to ObserveOn the UI thread (subscribing using Reactive Extensions instead of subscribing directly to the MessageWebSocket event), maybe that can help?

**Comment by PaulosV** [comment]
@darkl, I might try that and see how it works out, maybe later today.

**Comment by darkl** [comment]
Hi @PaulosV,
I added the async modifier as you suggested to current WampSharp release (WampSharp v1.2.4.18-beta).

Best regards,
Elad
