### ISSUE TITLE
There's a way to handle the session like in Autobahn Python?

### ISSUE THREAD

**Issue by johnnywell** [Code-Sharp/WampSharp#126]
On Autobahn we can just extend ApplicationSession class and implement our own tasks attached to events like, onJoin or onLeave. The WampSharp examples I've found so far are a bit scary for me (a C# dumbass).

There's a SessionHandler that I can just extend or attach events on WampSharp?

**Comment by darkl** [comment]
Hi @johnnywell,

There is no such thing in WampSharp.

Elad

**Comment by johnnywell** [comment]
Thanks @darkl for the reply,

What a pity, so,  are the examples really the best way to use WampSharp?

**Comment by darkl** [comment]
It really depends what you want to achieve (The wiki contains a lot of code snippets, most of them are ported from AutobahnJS/AutobahnPython samples).

You can reference here a AutobahnPython official sample, and I'll try to suggest you how to implement it using WampSharp.

Elad
