### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by markentingh** [Code-Sharp/WampSharp#128]
I'd like to use this package within my project, which only uses dnxcore50 dependencies. Is it possible? I tried using "WampSharp.Default": "1.2.3.15-beta" with no avail.

**Comment by darkl** [comment]
Hi @markentingh,

This isn't possible right now. I'm planning to work on this, but I prefer to wait a bit till .NET core documentation and tooling becomes more mature, see [this issue](https://github.com/JamesNK/Newtonsoft.Json/issues/618) for instance. In my opinion, there is no point in making any progress on this before Newtonsoft.Json's issue is closed.

**Comment by SamLebarbare** [comment]
another potential issue is SignalR...

**Comment by johnnywell** [comment]
Any evolution on this? I would like to start moving to .NET Core but WampSharp is preventing me at the moment.

**Comment by darkl** [comment]
Started working on a port, you can see it on the dot-net branch. I tested it on a simple Console application and it seems to work, but:

* Doesn't work on Unix (ClientWebSocket throws PlatformNotSupportedException) - see this [issue](https://github.com/dotnet/corefx/issues/2486).
* Uses some rx unofficial bits - see this [issue](https://github.com/Reactive-Extensions/Rx.NET/issues/148).
* Doesn't use Castle.Core until this [issue](https://github.com/castleproject/Core/issues/165) is resolved.
* No router-side support yet.
* Can't port RawSocket implementation until Microsoft.IO.RecyclableMemoryStream supports CoreCLR - see [this issue](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/issues/11).
* Unit tests weren't converted yet and I don't know if they pass.
* There is no build for this branch yet, so you'll have to compile it yourself.

I understand the will to move to .NET Core, but this project has a couple of dependencies that also need to support this. I think we should wait for the final release. I guess that then things will be stable and more projects (including the dependencies) won't be afraid to port their code to .NET Core.

Elad

**Comment by qooroo** [comment]
@darkl thanks for the update!

The .NET Core team are very responsive to requests so please +1 the WebSockets on Unix issue: https://github.com/dotnet/corefx/issues/2486

**Comment by johnnywell** [comment]
Hey guys, do you think it will be working until late august? I'm working in other things and delaying the WAMP integration, so I can wait to see this feature shining until then.

**Comment by darkl** [comment]
Hi @johnnywell,
It really depends. I guess there will be a port until late August. It might rely on RX unofficial bits, depending whether a .NET Core (netstandard) version of rx will be released by that time.

Elad

**Comment by darkl** [comment]
Cool,
Most of the referenced issues here are solved/will be solved soon.
I think it is realistic to expect a WampSharp .NET Core version in the near future.

Elad

**Comment by qooroo** [comment]
@darkl awesome!

Saw the rx 3.0 tweet so I guess that's resolved. What do you plan on doing for the websocket issue? I saw that https://github.com/dotnet/corefx/pull/9258 got merged but it's marked for 1.1 release which doesn't yet have a date.

**Comment by darkl** [comment]
In case that anyone is interested, there are experimental NuGet packages available in the MyGet feed (https://www.myget.org/F/wampsharp/api/v3/index.json). You need to install WampSharp.NewtonsoftJson 1.2.4.8-netcoredev, WampSharp.WebSockets 1.2.4.8-netcoredev for client support. There is also AspNet support for router-side (WampSharp.AspNetCore.WebSockets.Server 1.2.4.8-netcoredev). Tests pass, these should work fine.

A bit more work is needed for a stable release (MsgPack support, polishing AspNetCore api, replacing DispatchProxy with Castle.Core once the latter is released).

Elad

**Comment by darkl** [comment]
WampSharp v1.2.4.18-beta is now available with .NET Standard 1.3 support.
