### ISSUE TITLE
Sample WAMP2\WampSharp.Samples.Callee does not work

### ISSUE THREAD

**Issue by derdasmachenmuss** [Code-Sharp/WampSharp#129]
There is some bug in WampSharp.Samples.Callee:

https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/Samples/WAMP2/WampSharp.Samples.Callee/Program.cs#L74

throws an WampException: "wamp.error.invalid_options: unknown match type".

Any idea how to fix this example?

Thomas

**Comment by darkl** [comment]
Hi, the sample (our maybe the router code) should be fixed.
It can be fixed by setting RegisterOptions.Match property to WampMatchPattern.Exact.

Elad

**Comment by derdasmachenmuss** [comment]
Hi Elad,

I got it, but I had also to set RegisterOptions.Invoke to WampInvokePolicy.single. I choose "single", because it seems to be the default value, but I've no idea what the invoke property is for. Is there any documentation about this? 

Thomas

**Comment by darkl** [comment]
Hi Thomas,

these are options from the WAMP spec regarding multiple callees registering
to the same procedure.

Anyways, I discourage you using the RpcOperationCatalog directly as in the
sample. Using RealmServices's RegisterCallee should be preferred (See wiki
for samples).

Best regards,
Elad

**Comment by derdasmachenmuss** [comment]
Hi Elad,

is there any reason not to use RpcOperationCatalog, or are there any drawbacks doing it this way? I've explicitly chosen this way as I need some dynamic procedure to register all available RPCs. My router code has not a fixed set of RPCs. It depends on all loaded DLLs to the router project. I could possibly do this with RegisterCallee, if one could call this function multiple times. Is it possible?

Thomas

**Comment by darkl** [comment]
Hi Thomas,

The main reasons to prefer IWampRealmServiceProvider is that it is a more high-level api (You don't need to deal with raw rpc operations yourself). 

Another thing, is that WAMP discourages you to register peers on the router itself ("Routers should not contain any application code"). If you use IWampRealmServiceProvider's methods, then an internal client is created, which communicates with the router's classes via WAMP messages. Using TopicContainer/RpcCatalog directly bypasses the WAMP messages communication, and can result with these kind of scenarios. (Some default values aren't set and etc)

Actually, the IWampRpcOperationCatalog and IWampTopicContainer interfaces are kind of internal, and have been slightly changed a couple of times. Maybe I should introduce official apis for raw peers for router-side, similarly to these that are present on client-side.
