### ISSUE TITLE
Possible to dump WAMP messages for debugging?

### ISSUE THREAD

**Issue by supermihi** [Code-Sharp/WampSharp#130]
Hi there,
first of all, thanks for your great library! One thing I am missing is the possibility to dump the in/out WAMP traffic for debugging reasons.

My current "workaround" is to manually create a `WebSocket4Net.Websocket` and subscribe to its `MessageReceived` event. However, this
- Only works for Websockets
- Does not work for outbound traffic (there's no `MessageSent` event).

Is it possible to dump the WAMP traffic from WampSharp?

**Comment by darkl** [comment]
Hi Michael,

This is actually possible. Just install a logging library (such as log4net) and enable logs from WampSharp namespace on DEBUG level. Incoming and outgoing messages are written to log.

Elad

**Comment by supermihi** [comment]
Hi darkl,

thanks a lot, this works like a charm! :) I'd suggest to document this (unless it already is, and I simply didn't find it ...)
