### ISSUE TITLE
Support RawSocket SSL Connections

### ISSUE THREAD

**Issue by supermihi** [Code-Sharp/WampSharp#131]
Hi,

I am using WampSharp to connect to a WAMP router that offers Websocket and Rawsocket, both secured with SSL. I am facing several problems:
### Websocket connection

In my test environment, I need to use a self-signed certificate with additionally unmatched hostname. I was able to work around the self-signedness errors by manually creating a websocket and:

```
var ws = new WebSocket(uri, null, WebSocketVersion.None);
ws.AllowUnstrustedCertificate = true;
var connection = new WebSocket4NetTextConnection<JToken>(ws, binding);
return factory.CreateChannel(realm, connection, binding);
```

However, `WebSocket` has no option to ignore host mismatch errors. My bloody workaround was to add the certificate's hostname in the Windows hosts file for 127.0.0.1. Is there an easier way to create "untrusted" SSL connections (for testing)?
### Rawsocket connection

How can I tell WampSharp to use SSL on a rawsocket, and is this supported at all? Using the RawSocket examples from the docs, I get a `Timeout connecting to server` error.

Thanks in advance for any hints!

**Comment by darkl** [comment]
Hi,
Regarding the WebSocket question, I suggest you to ask a similar question in WebSocket4Net repository, since it is more related to WebSocket4Net than WampSharp.

Regarding the RawSocket question - I haven't implemented yet RawSocket SSL support, so it shouldn't be supported yet.

I don't have much experience with SSL, but I guess in order to implement it, it is needed to wrap some of the streams with a SslStream and call authenticate as client method.

Elad

**Comment by supermihi** [comment]
Hi Elad,
thanks for your response. Ok, I'll ask the WS4Net guys about the first issue, then. Concerning rawsocket, I guess you are correct that a (relatively) simple stream wrapping should do the trick. I might try this myself if I can find some free time ...

Michael

**Comment by supermihi** [comment]
For reference: The answer to my first question is something like
```
#if DEBUG
ServicePointManager.ServerCertificateValidationCallback = (s, cert, chain, policy) => true;
#endif
```

**Comment by darkl** [comment]
[Done!](http://wampsharp.net/release-notes/wampsharp-v18.6.1-release-notes/#rawsocket-ssl-support)
