### ISSUE TITLE
how can I disconnect session from server?

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#133]
how can I disconnect session from server?

**Comment by darkl** [comment]
Hi,

Do you mean from the router-side? This is not currently possible.

Elad

**Comment by devfxplayer** [comment]
Is there a hack around it?

**Comment by darkl** [comment]
No

**Comment by devfxplayer** [comment]
How can this be implemented?

**Comment by darkl** [comment]
Hi

I'll try to add support for disconnecting a client manually (by sending a GOODBYE or an ABORT message) in a future release.

Elad

**Comment by devfxplayer** [comment]
Hi Elad,
Do we have any update on this?
Thanks

**Comment by darkl** [comment]
Sorry, not yet.
Elad

**Comment by thelloworldt** [comment]
Hi, Elad, 
Can you give me some recommendations how to implement it easily?
Thanks

**Comment by darkl** [comment]
I thought a bit about this a few months ago. I think the best idea would to implement the management api as in [crossbario](https://github.com/crossbario/crossbar/blob/4ea31df079ed690213d1d196f692473e29977130/crossbar/router/service.py), I started defining the api [here](https://github.com/Code-Sharp/WampSharp/commit/ebcc6c4506c477e6c4331fcefc6c743461234be1). The reason I didn't proceed is that according to the WAMP spec UNREGISTERED and UNSUBSCRIBED messages don't receive a reason parameter, but crossbario does provide it to these messages, if the unregistrations/unsubscriptions were done via this api.

Elad

**Comment by darkl** [comment]
v20.1.1 supports [session management api](https://wampsharp.net/release-notes/wampsharp-v20.1.1-release-notes/#session-management-api).
