### ISSUE TITLE
newtonsoft 7?

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#135]
Hi,
I have many dependent projects that use newtonsoft version 7 and yours is using version 6.
Is there a plan to upgrade to version 7 ??
and if i download and update myself what are the compliactions?
Thanks

**Comment by darkl** [comment]
Hi,
I'll update to Newtonsoft.Json 8 in the next version, and will not make the version strict (so you can use also 7 and etc).

Elad

**Comment by darkl** [comment]
@devfxplayer, I released a version that doesn't limit the installed version of Newtonsoft.Json. This will result with assembly bindings in your app.config.

**Comment by devfxplayer** [comment]
thanks
