### ISSUE TITLE
Backwards/Forwards compatible RPC methods

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#136]
Assume that you are using WampSharp on both caller and dealer sides and have a current RPC call configured on the dealer side with a callee that takes two parameters.  

You want to keep the same RPC method name, but deprecate the existing two parameter endpoint, as you want to add a third parameter that is truly optional (like a reason code or something), but still want to support older clients.  This case is simple - on the dealer/callee side you implement both endpoints, having the two parameter version call the three parameter version with a reasonable default 'no reason' that mirrors old behavior.

However, it gets more complicated when you have a caller that needs to talk to dealers that are of various versions - both with and without knowledge of the three parameter version.  Without getting into an API version dance and put the onus on the caller to call the most appropriate version based on version checking or try 3 param/catch/try 2 param paradigm, is there a way to accomplish this?  

In this particular case it is perfectly safe to 'ignore' the third parameter and allow routing to the two parameter method.  The other assumption would be that I would not want to need to change the existing dealer code that is only aware of the two parameter version.  It seems that this type of default behavior is not something I would want the dealer to perform.

It seems like I'd want to use a WampSharp attribute on the caller method with something that indicates to the dealer that it is OK to ignore the third parameter if there is no matching three parameter callee and try to route to a two parameter version if it happens to exist.  This seems like a caller opt-in feature to me.

I don't see anything in the WAMP specification that would enable the dealer to route in this manner.  Perhaps 'Options', but I don't see documentation regarding them as it relates to RPC.  Then again, the concept of overloading RPC methods is an abstraction provided by WampSharp.

Thoughts?

**Comment by darkl** [comment]
Not sure if my answer was satisfactory, but closing since it has been a while.

Elad
