### ISSUE TITLE
Size/Length of Messages

### ISSUE THREAD

**Issue by glgodoy** [Code-Sharp/WampSharp#137]
Hi to everyone !!!

I want to know what is the max length/size I could publish in a message. I'm sending a JSON serialization of a class.

Thanks a lot,
Gustavo.-

**Comment by darkl** [comment]
Don't have a clue. I suggest you try testing it.

**Comment by glgodoy** [comment]
I published a message with more than 4,000,000 characters and the subscriber received it perfectly !!!
