### ISSUE TITLE
Simple publish/subscribe not working?

### ISSUE THREAD

**Issue by ERPO-UK** [Code-Sharp/WampSharp#139]
Hi,

I might be just missing something because I cannot get publish/subscribe to work. I have router running with DefaultWampHost and I tried invoking functions for Caller and Callee with both wampy and Autobahn library with no problems.
Is there any simple way to log/debug what goes wrong, since I have only this within my server:

    private const string location = "ws://127.0.0.1:14003/";
    public static IWampHost host;
    
    if (host != null)
        host.Dispose();
    host = new DefaultWampHost(location);
    host.Open();

And I call from wampy like this:

    ws = new Wampy('ws://127.0.0.1:14003/', { realm: 'realm1' });

    ws.subscribe("com.bazinga", {
        onSuccess: function () { console.log('Successfully subscribed to topic'); },
        onError: function (err) { console.log('Subscription error:' + err); },
        onEvent: function (data) {
            console.log('Received topic event:' + data);
        }
    });

    ws.publish("com.bazinga", ["usr_msg"], {
        onSuccess: function () { console.log('Publish successful!'); },
        onError: function (err) { console.log('Publish failed :(' + err); }
    });

I subscribed and published successfully but I don't get event and OnEvent is not called. Since I tried the same with Autobahn and got the same result, I think I screwed something with router. Probably is something obvious but I don't see it. 

Thanks for any help.

**Comment by darkl** [comment]
Hi,

According to the spec, by default, a publisher doesn't receive its own publications.
In order to change this behavior, specify  'exclude_me': true in the publishOptions.

Elad
