### ISSUE TITLE
Crossbars and TLS1.2

### ISSUE THREAD

**Issue by jmortlock** [Code-Sharp/WampSharp#143]
Hi

To get Wampsharp to talk to a TLS enabled Crossbar server we need to be able to use TLS1.2.

This support was added to WebSocket4Net a while ago but a nuget package hadn't been released until now, is there a chance of updating the nuget dependencies to this new version?
https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta2

Thanks

**Comment by darkl** [comment]
WampSharp v1.2.4.20-beta released, compiled with WebSocket4Net 0.15.0-beta4.

Elad
