### ISSUE TITLE
Event handling in specified thread

### ISSUE THREAD

**Issue by Jopie64** [Code-Sharp/WampSharp#145]
Hi,

I'm experimenting with WampSharp which I'm very exited about. I discovered how to use interceptors to use dynamic ID's in procedure names while still using the high level API. Its very cool!

There is a thing however that I have troubles with. It seems that when I register a subscriber class implementation via RegisterSubscriber, that every method in that class is called from a thread that I didn't create. Apparently this is the WebSocket thread. When using this with a GUI (e.g. WPF) this is problematic because usually events change things in the GUI (e.g. by adding a value to a list or simply by setting a property).

Of course this can be circumvented by using e.g. Application.Current.Dispatcher.Invoke(_ => Name = newName); or something like that but I don't like to do this for each and every event. That is quite a lot of boilerplate.

Is there a way I can make WampSharp call the event handling methods via a self supplied dispatcher? (So that I can force it to handle the events in the GUI thread)

I hope someone can help me.

Greetings,
Johan

**Comment by darkl** [comment]
Hi Johan,

This is currently not possible. I'll try to design and implement this kind
of feature for a future release.

I'm thinking of adding overloads to RegisterSubscriber and RegisterCallee
that allow the user to specify an IScheduler which messages will be
observed on.

Elad

**Comment by Jopie64** [comment]
Hi Elad,

Thanks for taking this in consideration!
May I suggest that it would also be nice to be able to supply such an IScheduler to be used by default to the channel?

And thanks for this nice library!

Greetings,
Johan

**Comment by darkl** [comment]
Hi Johan,

This can already be done now: you can implement a IWampConnection that wraps a given IWampConnection but raises its MessageArrived handler on the right thread. This can be done by using Observable.FromEventPattern chained with ObserveOn(IScheduler).
(You can also use Dispatcher.Invoke directly)

If I find some time, I would post some sample code that does it.

Elad

**Comment by Jopie64** [comment]
Hi Elad,

If that's true then my problem with the library is solved!
I'll try to make it work this way soon. Thanks for the tip!

Greetings,
Johan

**Comment by Jopie64** [comment]
Oh yeah, it works!
I'm not too long into C# programming so it might look a bit ugly to you, but this is the crude code I used to make it work after following your tip.

Thanks again!

Johan

``` c#
    public interface IScheduler
    {
        void Invoke(Action action);
    }

    internal class DelegatorWampConnection : IControlledWampConnection<JToken>
    {
        public DelegatorWampConnection(IControlledWampConnection<JToken> delegateeConnection, IScheduler processingThread)
        {
            _delegateeConnection = delegateeConnection;
            _delegateeConnection.ConnectionClosed += (s, e) => ConnectionClosed(s, e);
            _delegateeConnection.ConnectionError += (s, e) => ConnectionError(s, e);
            _delegateeConnection.ConnectionOpen += (s, e) => ConnectionOpen(s, e);
            _delegateeConnection.MessageArrived += (s, e) =>
            {
                processingThread.Invoke(() => MessageArrived(s, e));
            };
        }

        private IControlledWampConnection<JToken> _delegateeConnection;

        public event EventHandler ConnectionClosed;

        public event EventHandler<WampConnectionErrorEventArgs> ConnectionError;

        public event EventHandler ConnectionOpen;

        public event EventHandler<WampMessageArrivedEventArgs<JToken>> MessageArrived;

        public void Connect()
        {
            _delegateeConnection.Connect();
        }

        public void Dispose()
        {
            _delegateeConnection.Dispose();
        }

        public void Send(WampMessage<object> message)
        {
            _delegateeConnection.Send(message);
        }
    }

    public static class Channel
    {
        public static async Task<IWampChannel> Create(string wampUrl, IScheduler processingThread)
        {
            IWampChannelFactory factory = new WampChannelFactory();
            JTokenJsonBinding binding = new JTokenJsonBinding();

            IWampChannel channel =
                factory.CreateChannel("realm1",
                                        new DelegatorWampConnection(
                                            new WebSocket4NetTextConnection<JToken>(wampUrl, binding),
                                            processingThread),
                                        binding);
            await channel.Open();
            return channel;
        }
    }
```

And a trivial scheduler implementation:
``` c#
        private class MainThreadScheduler : IScheduler
        {
            public void Invoke(Action action)
            {
                Application.Current?.Dispatcher?.Invoke(action);
            }
        }

        public static IScheduler CreateMainAppTdScheduler()
        {
            return new MainThreadScheduler();
        }

```

**Comment by darkl** [comment]
WampSharp now allows you to specify the scheduler you would receive WAMP messages on. See [here](http://wampsharp.net/release-notes/wampsharp-v18.6.1-release-notes/#observeon-extension-method).
