### ISSUE TITLE
.Net Core Message Deserialization issue (not reproduced in .net 4.5)

### ISSUE THREAD

**Issue by robborden** [Code-Sharp/WampSharp#148]
I'm connecting to a public WAMP data feed using WampSharp in .Net Core .  I'm having a problem where within 10-15 seconds of subscribing, the socket will raise an error event due to some serialization exception inside WampSharp.   This same code works with .NET 4.5 WampSharp without any issues.  

I have attached a sample solution with both a NET45 and NETCORE implementation.  The core version will crash within 10 seconds or so.  The NET45 version will keep running indefinitely. I'm still having trouble getting the WampSharp project to build, otherwise I would try and fix it myself as this has stopped my NETCORE migration dead in its tracks. 

https://storage.googleapis.com/temporaryfiles/WampTests.zip

Any help or advice would be greatly appreciated!

**Comment by darkl** [comment]
Thanks for reporting the issue!
Solved this, will release a version tomorrow.

**Comment by robborden** [comment]
OMG you're the best!  Thank you so much for looking at it quickly.

**Comment by darkl** [comment]
TeamCity server is down, we'll have to wait until it's back in order to release a version.

**Comment by robborden** [comment]
Any chance this version was released?

**Comment by darkl** [comment]
No sorry, [TeamCity is down](http://teamcity.codebetter.com/).

**Comment by darkl** [comment]
Meanwhile you can try using WampSharp.WebSocket4Net instead (remove WampSharp.Default.Client and WampSharp.WebSockets) via fluent syntax api.

**Comment by robborden** [comment]
Wow, I can't believe it's still down.  What a nightmare.  

I'll hang tight until everything is published, I have some other things I can work on still.  Thanks much for your prompt support.   Is this you guys? http://www.codesharp.nl/

**Comment by darkl** [comment]
No, not us :)
We have a [twitter page](twitter.com/codesharpco).

**Comment by robborden** [comment]
Do you guys take donations?

**Comment by darkl** [comment]
Yeah, there is a PayPal donate button on this repository's README.md.

Thanks!

**Comment by darkl** [comment]
It might take a while until the TeamCity server is fixed, see their [tweet](https://twitter.com/codebetterCI/status/785854074713468932).

Meanwhile I suggest you to use WampSharp.WebSocket4Net as I suggested in a previous comment.

**Comment by darkl** [comment]
TeamCity is sort of back. Released v1.2.5.23-beta version to NuGet. Sorry for the wait.

**Comment by robborden** [comment]
Wow... that is a LONG time for them to be down.  Thanks for your diligence.


Thanks,

Rob Borden
262-391-4025
