### ISSUE TITLE
Memory and handle leak, when WampHost.Start() has been called and disposed.

### ISSUE THREAD

**Issue by bigbearzhu** [Code-Sharp/WampSharp#151]
We experienced some memory leak when we have retry on starting a WampHost when there is socket port conflict. The logic is pretty basic: catch exception and retry after a while. Interestingly the memory leak is mostly in unmanaged code, and there are lots of handle leaks too. The handles are leaked mostly in the `WampBindingHost<TMessage>.GetEventSerializer` function, stack trace as below:

```
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget<TInterface>(IInterceptor interceptor)
WampSharp.Core.Serialization.WampMessageSerializerFactory<TMessage>.GetSerializer<TProxy>()
WampSharp.V2.WampBindingHost<TMessage>.GetEventSerializer(IWampOutgoingRequestSerializer outgoingSerializer)
```

Sample code for reproducing the leak:

```
using System;
using System.Threading;
using WampSharp.V2;
using WampSharp.V2.Authentication;
using WampSharp.V2.Core.Contracts;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main()
        {
            while (true)
            {
                try
                {
                    DefaultWampAuthenticationHost host = new DefaultWampAuthenticationHost($"ws://0.0.0.0:{4567}/ws", new WampSessionAuthenticatorFactory());
                    host.Open();
                    host.Dispose();
                }
                catch 
                {
                    Thread.Sleep(100);
                    GC.Collect();
                }
            }
        }
    }

    internal class WampSessionAuthenticatorFactory : IWampSessionAuthenticatorFactory
    {
        public IWampSessionAuthenticator GetSessionAuthenticator(WampPendingClientDetails details, IWampSessionAuthenticator transportAuthenticator)
        {
            return new MockWampSessionAuthenticator();
        }
    }

    internal class MockWampSessionAuthenticator : WampSessionAuthenticator
    {
        public override void Authenticate(string signature, AuthenticateExtraData extra)
        {
        }

        public override string AuthenticationId => "foo";
        public override string AuthenticationMethod => "bar";
    }
}
```

**Comment by darkl** [comment]
Will investigate this in the weekend.

**Comment by darkl** [comment]
I modified this a bit, [see here](https://gist.github.com/darkl/66f3bb32d43cf56576d177e9a445e329).
I think your conclusion regarding a possibility is false.

Instructions:

0. Open task manager.
1. Run [this program](https://gist.github.com/darkl/66f3bb32d43cf56576d177e9a445e329).
2. Wait until memory usage is high (say 700MB).
3. See that memory seems to decrease.
4. Hit Enter.
5. Memory usage now should be stable. It may decrease.
6. Wait a few minutes and hit Enter
7. Memory usage should decrease to around 6-10MB. If it doesn't hit Enter a few more times. If it still doesn't wait a bit and hit Enter a few more times.

Got from ~720MB to ~10MB several times by hitting Enter < 20 times.

Elad

**Comment by bigbearzhu** [comment]
Hmm, it doesn't decrease on my machine at all after pressing the enter key! I am using the latest commit: bbb24220b2ea26de706b7c2a7022b937272c503d on WampV2 branch. I have also created a solution using the latest nuget packages. They are having the same behaviour.
[WampMemoryLeakTest.zip](https://github.com/Code-Sharp/WampSharp/files/543278/WampMemoryLeakTest.zip)
.

**Comment by darkl** [comment]
I also used the latest commit and latest nuget packages.
Have you waited 5 minutes between the first enter till the next enter?
Please do and write here your results.

Elad

**Comment by bigbearzhu** [comment]
This is the comparison after over 1 hr wait. I have tried enter many times. And you can probably see how my w3wp.exe leaks too during that time.
![image](https://cloud.githubusercontent.com/assets/1924924/19588595/2673ae1a-97aa-11e6-8a40-d0bd13c16394.png)

**Comment by darkl** [comment]
The memory does decrease it just takes time.
I am attaching a boring screen capture showing how memory increases to 700MB and then decreases to 8MB. [See here](https://drive.google.com/open?id=0BwgVg3dzk-lRcl9TVjhDN0tMUm8).

**Comment by darkl** [comment]
After investigating this a bit, I found [this issue](https://github.com/castleproject/Core/issues/59). I tried to change the ProxyGenerator to be static in the develop branch. It seems that now memory doesn't increase rapidly. Please try this version by compiling the develop branch yourself or by using the dlls from MyGet feed (https://www.myget.org/F/wampsharp/api/v3/index.json or https://www.myget.org/F/wampsharp/api/v2) - version 1.2.4.156-develop.

Elad

**Comment by bigbearzhu** [comment]
Thanks for the update. The fix does fix the memory increase! Now the program sits around 12MB memory usage constantly.

**Comment by darkl** [comment]
I'll release a new version with the update sometimes this week.

**Comment by darkl** [comment]
v1.2.5.24-beta released to NuGet gallery with this fix.

Elad

**Comment by bigbearzhu** [comment]
Brilliant, thanks!
