### ISSUE TITLE
Limiting the number of sessions on Router

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#153]
Hi Elad,
I would like to limit the amount of clients connecting to my router to, let's say, 10. If 11th client makes a connection attempt, I want to deny that connection. Is there an easy way of doing this?

Thanks
Esso

**Comment by darkl** [comment]
Hi Esso,

This can be done using authentication. Write an authenticatior mechanism
that counts sessions and limits the number of current available sessions.
(You need decrease the number of sessions when a client disconnects, by
subscribing to the realm's SessionClosed event and checking that client
wasn't aborted)

**Comment by esso23** [comment]
Took me some time to implement but it works flawlessly. Thanks a lot!
