### ISSUE TITLE
How can I instantiate Wamp Router in ASP.NET 4.6

### ISSUE THREAD

**Issue by kasravi** [Code-Sharp/WampSharp#156]
We are using Microsoft.WebSocket. We could have a live web socket endpoint with routing in ASP.NET with events on being opened/closed, having error or message. What I want is to wrap it as a transport for the router.
First question would be - if it is even possible? and if this possibility is painless?
and if it is, where should we head to?

**Comment by darkl** [comment]
Hi, this should be straightforward, assuming that ASP.NET 4.6 WebSocket api uses System.Net.WebSockets api. See my implementation for [ASP.NET Core](https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/Extensions/WampSharp.AspNetCore.WebSockets.Server/AspNetCoreWebSocketTransport.csr).

**Comment by kasravi** [comment]
Yeah I tried to reuse that code. I will give it another shot tomorrow. Thanks.
