### ISSUE TITLE
Callee proxy hangs on calling methods when channel is opened using "await"

### ISSUE THREAD

**Issue by bigbearzhu** [Code-Sharp/WampSharp#160]
Hi, I have seen some strange behavior on callee proxy even with latest commit.

Check these two tests below. The first one hangs at line 44, while the second doesn't at all. The only difference is that the CallProxyAsync is awaiting the channel to open while the CallProxy version calls Wait() to wait for the channel to open. Mind having a look at it to see if there is something wrong in my code or WampSharp? Thanks.

```
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;
using NUnit.Framework;
using WampSharp.V2;
using WampSharp.V2.Core.Contracts;
using WampSharp.V2.Rpc;

namespace WampSharp.Tests.Wampv2
{
    [TestFixture]
    public class WampProxyTests
    {
        private DefaultWampHost _host;
        private int _port;

        [TestFixtureSetUp]
        public void Initialize()
        {
            _port = GetRandomUnusedPort();
            _host = new DefaultWampHost($"ws://0.0.0.0:{_port}/ws");
            _host.Open();
        }

        [Test]
        [ExpectedException(typeof(WampException))]
        public void CallProxyAsync_ShouldComplete()
        {
            CallProxyAsync().Wait(); //hangs.
        }

        [Test]
        [ExpectedException(typeof(WampException))]
        public void CallProxy_ShouldComplete()
        {
            CallProxy(); //not hang.
        }

        private async Task CallProxyAsync()
        {
            var channel = new DefaultWampChannelFactory().CreateJsonChannel($"ws://localhost:{_port}/ws", "Foo");
            await channel.Open();
            var proxy = channel.RealmProxy.Services.GetCalleeProxy<IInterface>();
            proxy.DoSomeThing(); //hangs here.
        }

        private void CallProxy()
        {
            var channel = new DefaultWampChannelFactory().CreateJsonChannel($"ws://localhost:{_port}/ws", "Foo");
            channel.Open().Wait();
            var proxy = channel.RealmProxy.Services.GetCalleeProxy<IInterface>();
            proxy.DoSomeThing();
        }

        public static int GetRandomUnusedPort()
        {
            var listener = new TcpListener(IPAddress.Any, 0);
            listener.Start();
            var port = ((IPEndPoint)listener.LocalEndpoint).Port;
            listener.Stop();
            return port;
        }
    }

    public interface IInterface
    {
        [WampProcedure(nameof(IInterface) + "." + nameof(DoSomeThing))]
        void DoSomeThing();
    }
}
```

**Comment by darkl** [comment]
When await channel.Open returns, you are returned on the listener thread
and calling a synchronous method blocks that thread from getting new
messages. This is a phenomenon that is not unique to WampSharp (See here:
http://stackoverflow.com/questions/19481964/calling-taskcompletionsource-setresult-in-a-non-blocking-manner).
In order avoid it, you are suggested to use the async callee proxy.

Elad

**Comment by bigbearzhu** [comment]
Thanks @darkl and the SO link. It indeed explains the behavior. I have tried converting proxy methods to return `Task`. Seems working as expected. For existing proxy methods which are not async, what is the best way to call them? Wrap in `await Task.Run(()=>proxy.DoSomeThing())` (confirmed it works)?

**Comment by darkl** [comment]
I don't consider myself a concurrency expert. However here are my thoughts:
I think you should avoid synchronous calls, since these block threads. Calling a synchronous proxy method in ```Task.Run( )``` seems like something which would only block more threads and eventually choke your application. I would suggest avoiding synchronous calls in general, and using a dedicated thread (using a producer/consumer model) if you really want synchronous calls.

Also, in my opinion the Task.Yield() approach is a bit more elegant than the Task.Run() approach. (Which I'd avoid both)

Elad
