### ISSUE TITLE
IWampChannel.Close(string,GoodbyeDetails) causes UnobservedTaskException

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#167]
I'm at that stage in the process where I am adding more diagnostic logging, and decided it would be interesting to use the IWampChannel.Close(string,GoodbyeDetails) overload to provide some context to log on the server side.  

When using this method, the Server side sees the goodbye message coming across and gets the close.  Unfortunately, this causes an UnobservedTaskException being raised (eventually) on the client side, (hook event as in #155 to see it, and GC.Collect() after close to see it faster).  It doesn't cause anything to 'break' but this is probably not a good thing to happen.

The Task in question appears to be the mOpenTask, set to "Connection closed before connection established." in  WampSessionClient<TMessage>::OnConnectionClosed().

The IWampChannel.Close() with no arguments does not have this same effect, nor (of course) does it provide anything to the server side.  The implementations are very different.

**Comment by darkl** [comment]
Hopefully I fixed this and a few other potential issues regarding to the reconnector mechanism.
