### ISSUE TITLE
Wampsharp uses deprecated AspNetCore.WebSockets package 

### ISSUE THREAD

**Issue by lukaszkrzywizna** [Code-Sharp/WampSharp#172]
WampSharp.AspNetCore.WebSockets.Server uses deprecated websockets package: Microsoft.AspNetCore.WebSockets.Server. Please update it to Microsoft.AspNetCore.WebSockets package (https://www.nuget.org/packages/Microsoft.AspNetCore.WebSockets/1.0.0). More details: https://github.com/aspnet/IISIntegration/issues/240

**Comment by darkl** [comment]
Its a shame that I'm now stuck with the name "WampSharp.AspNetCore.WebSockets.Server"...

**Comment by lukaszkrzywizna** [comment]
Maybe You should consider rename it to "WampSharp.AspNetCore.WebSockets" or create the new one (package)?

**Comment by darkl** [comment]
I thought about it, but I'll also need to rename the namespaces and  I'd probably like to rename also WampSharp.AspNet.WebSockets.Server to WampSharp.AspNet.WebSockets or even WampSharp.AspNet as well.

Elad
