### ISSUE TITLE
Query about RegisterSubscriber and GetSubject().Subscribe()

### ISSUE THREAD

**Issue by drweeto** [Code-Sharp/WampSharp#183]
Firstly, thank you very much for creating the WampSharp library. It has been a great help as I start to try and understand WAMP and wss.

My question: Is there a difference between using RegisterSubscriber() and GetSubject().Subscribe()?

I am attempting to use WampSharp in the context provided by [this post on issue 60](https://github.com/Code-Sharp/WampSharp/issues/60#issuecomment-269669073). I am using the Poloniex api having read [issue 6](https://github.com/Code-Sharp/WampSharp-docs/issues/6) on the documentation github. 

Using the first approach, I can get the symbol, the bid price and the ask price from the Arguments property of eventObject. When I use the second approach, eventObject seems to be a single string that contains a symbol, when I might expect a string array.

1.
`channel.RealmProxy.Services.GetSubject("ticker").Subscribe(ActionOnMessage);`

ActionOnMessage is a function with the following signature:

`public override void ActionOnMessage(IWampSerializedEvent eventObject)`

2.
`channel.RealmProxy.Services.RegisterSubscriber(mySubscriber);`

Where mySubscriber is an instance of a class that has a method with the following signature:

```
[WampTopic("ticker")]
public void OnMessage(object eventObject)
```

**Comment by darkl** [comment]
For the second example, you are supposed to receive all arguments in the subscriber handler. WampSharp unpacks those:

```csharp
[WampTopic("ticker")]
public void OnMessage(string currencyPair, double priceLast, double orderTopSell, double orderTopBuy, double priceChangePercentage, double volume24HourBase, double volume24HourQuote, byte isFrozenInternal)
```

**Comment by drweeto** [comment]
Ah, of course. Thank you very much for the clarification.
