### ISSUE TITLE
Possibility for the Client to create a topic

### ISSUE THREAD

**Issue by maciejjarzynski** [Code-Sharp/WampSharp#184]
Is there any possibility to create a topic by the client/channel, which may be separate from the IWampHost? (so no access to TopicContainer's method CreateTopicByUri?
If not, is there an option of adding this feature?
I would like to have separate instance/service of the web app as a WAMP router, and then clients which would be able to create topics on which I am trying to publish something.
I could do this on my own, like creating specified endpoint to add a topic, but I am thinking of some more solid solution within a library itself.

**Comment by darkl** [comment]
Just publish to the topic. It will be created when subscribers subscribe to
it.

**Comment by maciejjarzynski** [comment]
1. Publishing to the topic that not exists ends with an WampException (wamp.error.invalid_topic).
I could catch them, but I'd like to avoid this kind of flow.
2. My subscribers are using pattern topic matching (run with AutobahnJS), so they won't create any topics upon the subscription.

**Comment by darkl** [comment]
1. The exception is caught on the server side by WampSharp.
2. If your subscribers are subscribed using pattern topic matching, and the
uri matches the pattern, then they'll receive the event and 1. won't happen.

Elad

**Comment by maciejjarzynski** [comment]
@1 in my case it's throwing exception outside the WampSharp, I'm running it on .NET Core 1.1 (example):
```
topicProxy = channel
                .RealmProxy
                .TopicContainer
                .GetTopicByUri(topic);

await topicProxy.Publish(publishOptions, new object[] { eventMessage });
```
@2 yes, that's true, thank you for the clue and confirmation ;) Because that exception from point 1. was misleading me that something went wrong.

**Comment by darkl** [comment]
2. Great. Please close the issue if this fixed your problem.
1. The exception is internally caught by WampSharp - [see here](https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/WampSharp/WAMP2/V2/PubSub/WampPubSubServer.cs#L70).

**Comment by maciejjarzynski** [comment]
1-  ok, I found out why it was throwing that exception - the setting in PublishOptions for `Acknowledge = true` was responsible for that..

That should be all by now, thank you for your help, therefore I'm closing this issue.
