### ISSUE TITLE
How to check and re-open connection?

### ISSUE THREAD

**Issue by Oleg26Dev** [Code-Sharp/WampSharp#185]
How I can check, close and open connection? 
For example, I'd like to have a re-enterable function to start server like this:

private void StartServer()
{
 const string serverAddress = "ws://127.0.0.1:8080/ws";
            WampHost host = new DefaultWampHost(serverAddress);
            host.Open();
}

**Comment by darkl** [comment]
Not sure what you're asking. You are supposed to close the Host using Dispose.
Otherwise I don't understand what you're asking.

Elad

**Comment by Oleg26Dev** [comment]
I mean: how I can check inside of this function if host already created and open and I do not need to open it again? to avoid an error because it was already open

WampHost host;
private void StartServer()
{
if( CHECK_IF_HOST_ALREADY_OPEN()) return; // ???

const string serverAddress = "ws://127.0.0.1:8080/ws";
host = new DefaultWampHost(serverAddress);
host.Open();
}

**Comment by darkl** [comment]
You'll have to maintain this state by yourself.

Elad
