### ISSUE TITLE
Does it require WebSockets?

### ISSUE THREAD

**Issue by Oleg26Dev** [Code-Sharp/WampSharp#186]
Is it possible to use the WampSharp applications in Windows 7? 
or it requires WebSockets protocol?

**Comment by darkl** [comment]
It is possible. The default host uses Fleck which is a non-native WebSocket
implementation that works on Windows 7. If you don't want to use WebSockets
anyway, you can use RawSocket protocol which is implemented directly above
Tcp.

Elad
