### ISSUE TITLE
Error WampSharp Windows XP

### ISSUE THREAD

**Issue by leonardodistasio** [Code-Sharp/WampSharp#188]
Hi,

I have a problem with my program who has WampSharp.Default.Router installed.
I create a DefaultWampHost with the server address "ws://0.0.0.0:8080/ws". On Windows 7 I have no problem, the program launch normally and can create the WampHost.
But when I install my program I have an error SocketException (0x80004005) : an invalid argument was supplied.
I have disable my firewall to be sure that was not a problem of port but it isn't. 
Is the library (or one of it's dependencies) incompatible with XP ?

Thank you in advance

**Comment by darkl** [comment]
From Googling, this seems to mean that the port is already in use by
another application. Try changing it. If it doesn't help, try specifying a
different IP such as 127.0.0.1.

I never however tried WampSharp on Windows XP, but I think there is no
reason for it not to work.

Elad

**Comment by leonardodistasio** [comment]
I've tried but it does not work in my ccase. I suppose i must check the configuration of my computer. 
Thank you for help.
