### ISSUE TITLE
WampSharp Client Python Crossbar Server Exception

### ISSUE THREAD

**Issue by alek5k** [Code-Sharp/WampSharp#189]
I'm running the python crossbar example server ('hello') and attempting to connect to it via C# client. When I run the following code I get a System.AggregateException thrown on the last line with a message of 'unknown server protocol version':

`DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();`
`IWampChannel wampChannel = channelFactory.CreateJsonChannel(serverAddress, "realm1");`
`wampChannel.Open().Wait();`

![err](https://cloud.githubusercontent.com/assets/20435565/25556169/6fe9901a-2d3b-11e7-821e-54a0c190a9f0.PNG)

Note that I am not creating a DefaultWampHost when this exception occurs (is this required for a client only?)

Curiously, If I add the following lines before the code above:

`WampHost host = new DefaultWampHost(serverAddress);`
`host.Open();`

I can connect to the python server correctly, however **only if** I start the C# client before I start the python server. This also results in unintended behaviour, for instance when I close the C# client the python server will be terminated.

Is the exception intended or is this a bug?

Or if we are expected to use the WampHost then how do we use it as a client only? (I take it we're not expected to as its found under WampSharp.Default.Router)
I found a related issue here where they pass in an origin to their WebSocket constructor in WebSocket4Net library:
https://github.com/kerryjiang/WebSocket4Net/issues/8

**Comment by darkl** [comment]
You are not supposed to use the WampHost in the same process where you use the WampChannel.
Which example are you talking about? Can you please link to it?

Elad

**Comment by alek5k** [comment]
Hi Elad

Yes I thought so. Curious that it would talk to the python server when i run this 'shadow server' via wamphost.

The example can be found at:
https://github.com/crossbario/crossbar-examples/tree/master/hello/python

It is a barebones crossbar server example. The javascript client front end as part of the example works fine. Just the c# client that's having issues.

Thanks!
Aleks

**Comment by darkl** [comment]
How do you run it? I can't run it crossbar start doesn't work for me.

**Comment by alek5k** [comment]
Make sure you have installed it first:

pip install crossbar

If you are running a mingw terminal (the one that comes with git) on Windows then use:

winpty crossbar start

**Comment by darkl** [comment]
It is installed, of course.

I get [this kind](https://github.com/crossbario/crossbar/issues/1002) of exception.

What versions are you using?

Elad

**Comment by alek5k** [comment]
I am running it on Python 3.6.1. Autobahn and crossbar from pip freeze:

autobahn==0.18.1
crossbar==17.3.1

**Comment by darkl** [comment]
Installed Python 3.6.1. Still get the same exception.
Setting up a fresh crossbar instance (by crossbar init) and running examples from [here](https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/wamp) works fine (including the C# client part).

Elad

**Comment by alek5k** [comment]
I tried running the example you linked. I get the same error (unknown server protocol version). 

I noted this error on the wamp server this time:

2017-04-30T18:29:28+1000 [Router       5788] failing WebSocket opening handshake ('HTTP Origin header invalid: No host part in Origin '127.0.0.1'')
2017-04-30T18:29:28+1000 [Router       5788] dropping connection to peer tcp4:127.0.0.1:62407 with abort=False: HTTP Origin header invalid: No host part in Origin '127.0.0.1'

**Comment by darkl** [comment]
Ok, try these instructions (they work fine for me):

* Create an empty directory and run crossbar init
* run crossbar start
* Run this code

```csharp
DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();
IWampChannel wampChannel = channelFactory.CreateJsonChannel("ws://127.0.0.1:8080/ws", "realm1");
wampChannel.Open().Wait();
Console.WriteLine("Connected");
```

For me this works without any exception (The AutobahnPython code is irrelevant here).

Elad

**Comment by alek5k** [comment]
Hi Elad,

Followed these instructions. Still get the exception (unknown server protocol version).
Server still reports:

2017-04-30T18:55:53+1000 [Router       2652] failing WebSocket opening handshake ('HTTP Origin header invalid: No host part in Origin '127.0.0.1'')
2017-04-30T18:55:53+1000 [Router       2652] dropping connection to peer tcp4:127.0.0.1:62566 with abort=False: HTTP Origin header invalid: No host part in Origin '127.0.0.1'


Maybe you are running a different version of crossbar to me?

**Comment by darkl** [comment]
This is the output log
> 2017-04-30T11:58:32+0300 [Controller   3632] File permissions on node public key fixed!
> 2017-04-30T11:58:32+0300 [Controller   3632] File permissions on node private key fixed!
> 2017-04-30T11:58:32+0300 [Controller   3632]      __  __  __  __  __  __      __     __
> 2017-04-30T11:58:32+0300 [Controller   3632]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
> 2017-04-30T11:58:32+0300 [Controller   3632]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
> 2017-04-30T11:58:32+0300 [Controller   3632]                                         
> 2017-04-30T11:58:32+0300 [Controller   3632] Version:     Crossbar.io COMMUNITY 17.3.1
> 2017-04-30T11:58:32+0300 [Controller   3632] Public Key:  b070799e2f17a33daa89a6dd57c41f8054f80343cb5e6d7d84671c6c314fe2be
> 2017-04-30T11:58:32+0300 [Controller   3632] 
> 2017-04-30T11:58:32+0300 [Controller   3632] Node starting with personality "community" [crossbar.controller.node.Node]
> 2017-04-30T11:58:32+0300 [Controller   3632] Running from node directory "C:\Users\Elad\Documents\GitHub\crossbarexamples\newdemo\.crossbar"
> 2017-04-30T11:58:32+0300 [Controller   3632] Node configuration loaded from "C:\Users\Elad\Documents\GitHub\crossbarexamples\newdemo\.crossbar\config.json"
> 2017-04-30T11:58:32+0300 [Controller   3632] Controller process starting [CPython-IOCPReactor] ..
> 2017-04-30T11:58:32+0300 [Controller   3632] No extra node router roles
> 2017-04-30T11:58:32+0300 [Controller   3632] Using default node shutdown triggers ['shutdown_on_worker_exit']
> 2017-04-30T11:58:32+0300 [Controller   3632] Configuring node from local configuration ...
> 2017-04-30T11:58:32+0300 [Controller   3632] Starting 1 workers ...
> 2017-04-30T11:58:32+0300 [Controller   3632] Router worker "worker-001" starting ..
> 2017-04-30T11:58:33+0300 [Router       7484] Router worker "worker-001" process 7484 starting on CPython-IOCPReactor ..
> 2017-04-30T11:58:34+0300 [Router       7484] Router worker "worker-001" session 8772742271421838 initializing ..
> 2017-04-30T11:58:34+0300 [Router       7484] Router worker "worker-001" session ready
> 2017-04-30T11:58:34+0300 [Controller   3632] Router worker "worker-001" process 7484 started
> 2017-04-30T11:58:34+0300 [Controller   3632] Router 'worker-001': realm 'realm-001' (named 'realm1') started
> 2017-04-30T11:58:34+0300 [Router       7484] Realm 'realm1' started
> 2017-04-30T11:58:34+0300 [Controller   3632] Router 'worker-001': role 'role-001' (named 'anonymous') started on realm 'realm-001'
> 2017-04-30T11:58:34+0300 [Router       7484] role role-001 on realm realm-001 started
> 2017-04-30T11:58:34+0300 [Controller   3632] Router 'worker-001': transport 'transport-001' started
> 2017-04-30T11:58:34+0300 [Controller   3632] Local node configuration applied successfully!
> 2017-04-30T11:58:34+0300 [Router       7484] UniSocketServerFactory starting on 8080
> 2017-04-30T11:59:04+0300 [Router       7484] >>>>> session 6846332944269758 JOINED "realm1" >>>>>
> 
> {'session': 6846332944269758, 'authid': 'R4WL-QVSX-VTHJ-JW96-YACJ-CY5U', 'authrole': 'anonymous', 'authmethod': 'anonymous', 'authprovider': 'static', 'transport': {'type': 'websocket', 'protocol': 'wamp.2.json', 'peer': 'tcp4:127.0.0.1:54324', 'http_headers_received': {'upgrade': 'WebSocket', 'connection': 'Upgrade', 'sec-websocket-version': '13', 'sec-websocket-key': 'NWVmMjE1YzQtZTcxOC00Yw==', 'host': '127.0.0.1:8080', 'origin': 'ws://127.0.0.1:8080', 'sec-websocket-protocol': 'wamp.2.json'}, 'http_headers_sent': {}, 'websocket_extensions_in_use': [], 'cbtid': None}}
> 
> 2017-04-30T11:59:05+0300 [Router       7484] <<<<<< session 6846332944269758 LEFT "realm1" <<<<<<
> 
> {'session': 6846332944269758, 'authid': 'R4WL-QVSX-VTHJ-JW96-YACJ-CY5U', 'authrole': 'anonymous', 'authmethod': 'anonymous', 'authprovider': 'static', 'transport': {'type': 'websocket', 'protocol': 'wamp.2.json', 'peer': 'tcp4:127.0.0.1:54324', 'http_headers_received': {'upgrade': 'WebSocket', 'connection': 'Upgrade', 'sec-websocket-version': '13', 'sec-websocket-key': 'NWVmMjE1YzQtZTcxOC00Yw==', 'host': '127.0.0.1:8080', 'origin': 'ws://127.0.0.1:8080', 'sec-websocket-protocol': 'wamp.2.json'}, 'http_headers_sent': {}, 'websocket_extensions_in_use': [], 'cbtid': None}}
> 
> 2017-04-30T11:59:12+0300 [Controller   3632] Node shutdown requested ..
> 2017-04-30T11:59:12+0300 [Controller   3632] sending TERM to subprocess 7484
> 2017-04-30T11:59:12+0300 [Controller   3632] waiting for 7484 to exit...
> 2017-04-30T11:59:12+0300 [Controller   3632] Node worker worker-001 ended with error ([Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 1.
> ])
> 2017-04-30T11:59:12+0300 [Controller   3632] Checking for node shutdown: worker_exit_success=False, shutdown_requested=True, node_shutdown_triggers=['shutdown_on_worker_exit']
> 2017-04-30T11:59:12+0300 [Controller   3632] Node worker ended, and trigger 'shutdown_on_worker_exit' active

**Comment by alek5k** [comment]
Looks like I have the exact same output as you until you actually connect  at 2017-04-30T11:59:04+0300.

That is where my error messages appear. Interestingly you have an origin header being sent in yours:
origin': 'ws://127.0.0.1:8080

Which versions do you have in your packages.config in VS? Mine are:

  <package id="WampSharp" version="1.2.0.2-beta" targetFramework="net45" />
  <package id="WampSharp.Default" version="1.2.0.2-beta" targetFramework="net45" />
  <package id="WebSocket4Net" version="0.10" targetFramework="net45" />

**Comment by darkl** [comment]
Oh, that's very old.

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Castle.Core" version="3.3.1" targetFramework="net45" />
  <package id="MsgPack.Cli" version="0.6.2" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.5" targetFramework="net45" />
  <package id="Newtonsoft.Msgpack" version="0.1.10" targetFramework="net45" />
  <package id="SuperSocket.ClientEngine.Core" version="0.8.0.6" targetFramework="net45" />
  <package id="System.Collections.Immutable" version="1.2.0" targetFramework="net45" />
  <package id="System.Reactive" version="3.0.0" targetFramework="net45" />
  <package id="System.Reactive.Core" version="3.0.0" targetFramework="net45" />
  <package id="System.Reactive.Interfaces" version="3.0.0" targetFramework="net45" />
  <package id="System.Reactive.Linq" version="3.0.0" targetFramework="net45" />
  <package id="System.Reactive.PlatformServices" version="3.0.0" targetFramework="net45" />
  <package id="System.Reactive.Windows.Threading" version="3.0.0" targetFramework="net45" />
  <package id="System.Threading.Tasks.Dataflow" version="4.6.0" targetFramework="net45" />
  <package id="System.ValueTuple" version="4.0.0-rc3-24212-01" targetFramework="net45" />
  <package id="WampSharp" version="1.2.5.35-beta" targetFramework="net45" />
  <package id="WampSharp.Default.Client" version="1.2.5.35-beta" targetFramework="net45" />
  <package id="WampSharp.NewtonsoftJson" version="1.2.5.35-beta" targetFramework="net45" />
  <package id="WampSharp.NewtonsoftMsgpack" version="1.2.5.35-beta" targetFramework="net45" />
  <package id="WampSharp.WebSocket4Net" version="1.2.5.35-beta" targetFramework="net45" />
  <package id="WebSocket4Net" version="0.15.0-beta4" targetFramework="net45" />
</packages>
```

**Comment by alek5k** [comment]
Ah okay, I will try upgrade. I found this example project in the crossbar examples repo.

https://github.com/crossbario/crossbar-examples/blob/master/hello/csharp/src/Hello/packages.config

Maybe it needs to be updated.

**Comment by darkl** [comment]
Yeah, it should be updated.

**Comment by alek5k** [comment]
Yep, works perfectly now. Thanks for your help!

The hello example in the crossbar repo seems to be using the objects from the old version also.
