### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kwaazaar** [Code-Sharp/WampSharp#190]
I'm using WAMPSharp for subscriber and running as a console app on .NET core. I'm receiving a maximum of 5 messages per second, but CPU usage is almost 100% (both on my Win10 dev machine and on a Win2016 VM on azure). Do you have any idea what's going wrong?

**Comment by darkl** [comment]
No idea, maybe further details would help (small/large objects? sample code?).

Elad

**Comment by kwaazaar** [comment]
Tried to create a simple repro (https://github.com/kwaazaar/poloniextickerimporter), but it doesn't show the same problem. It actually hardly shows any CPU usage at all 👍 
So must have been my own code construction that somehow caused this.
