### ISSUE TITLE
Publishing to non-existing topic results in Error-level log entry

### ISSUE THREAD

**Issue by maciejjarzynski** [Code-Sharp/WampSharp#192]
While publishing to the topic, to which no one is subscribed, the log entry with the Error level is being saved:
https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/WampSharp/WAMP2/V2/PubSub/WampPubSubServer.cs#L71

In my opinion, with the setting set to publish Errors/acknowledge: false it should rather be stored as an Info or a Warning entry.
This is the normal flow of the pub/sub pattern for the publisher to be independent from the subscribers, whether they are existing or not.

**Comment by darkl** [comment]
I don't mind changing the log level. Do you think it should remain an error in the case that the publisher requested acknowledgement?

Elad

**Comment by darkl** [comment]
Fixed in v1.2.6.41-beta.
