### ISSUE TITLE
Support for Universal Windows Platform (UWP)

### ISSUE THREAD

**Issue by RSFalcon7** [Code-Sharp/WampSharp#195]
The available NuGet packages don't work on a vanilla UWP app

Follows the output of Install-Package from the version 1.2.4.18-beta, that according to #134 should work, default installation is `Unable to find package 'WampSharp.Default'`

```
PM> Install-Package WampSharp -Version 1.2.4.18-beta -Pre
Restoring packages for 'App1'.
Restoring packages for c:\users\rafael.caldeira\documents\visual studio 2015\Projects\App1\App1\project.json...
  GET https://api.nuget.org/v3-flatcontainer/system.componentmodel.typeconverter/index.json
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='System.ComponentModel.TypeConverter'
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='System.ComponentModel.TypeConverter' 148ms
  OK https://api.nuget.org/v3-flatcontainer/system.componentmodel.typeconverter/index.json 584ms
Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is 
no run-time assembly compatible with win10-arm-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.Lightweight 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no 
run-time assembly compatible with win10-arm-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is 
no run-time assembly compatible with win10-x64-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.Lightweight 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no 
run-time assembly compatible with win10-x64-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is 
no run-time assembly compatible with win10-x86-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.Lightweight 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no 
run-time assembly compatible with win10-x86-aot.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Package restore failed for 'App1'.
Install-Package : Package restore failed. Rolling back package changes for 'App1'.
At line:1 char:1
+ Install-Package WampSharp -Version 1.2.4.18-beta -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>
```

**Comment by dancgr** [comment]
I'm having the same issue with my UWP project!

**Comment by darkl** [comment]
Did you two try installing latest version?

Elad

**Comment by dancgr** [comment]
I tried installing using the command:
`Install-Package WampSharp.Default -Pre`

Which resulted in the errors listed above.

**Comment by RSFalcon7** [comment]
@darkl Thanks for the fast reply!

My packet manager is unable to find WampSharp.Default, but version `1.2.5.36-beta` results in the same errors.

**Comment by Jopie64** [comment]
Maybe I'm wrong here but from the error I get the idea that a WampSharp dependency (System.Reflection.Emit.ILGeneration) is not compatible with Windows for ARM (win10-arm-aot). Are you targetting ARM?
Maybe [this link](https://social.msdn.microsoft.com/Forums/en-US/856751dc-8331-4076-bf31-ba0563f0125d/uwp-some-packages-are-not-compatible-with-uapversionv100?forum=wpdevelop) will help?

**Comment by darkl** [comment]
Can you trace which dependency requires System.Reflection.Emit.Lightweight?

Elad

**Comment by dancgr** [comment]
@Jopie64 The first error is arm, but the next two following errors are x64 and x86 for the same package! So I think the error is not platform specific.

@RSFalcon7 Were you able to trace the dependency? In my case, I am only able to see the errors, the console does not show which dependency generated the errors.

**Comment by RSFalcon7** [comment]
@Jopie64 I'm targeting ARM, x86 and x64, but all platforms results in `no 
run-time assembly compatible`

@darkl @dancgr Sure I can, how do I trace it?

**Comment by darkl** [comment]
Maybe I'm doing something wrong? Created a new Blank App (Windows Universal) project  in Visual Studio 2017, installed WampSharp.Default, it was installed successfully 

>   GET https://www.nuget.org/api/v2/Packages(Id='WampSharp.Default',Version='1.2.5.36-beta')
>   OK https://www.nuget.org/api/v2/Packages(Id='WampSharp.Default',Version='1.2.5.36-beta') 232ms
> Restoring packages for c:\users\elad\documents\visual studio 2017\Projects\App1\App1\App1.csproj...
> Committing restore...
> Writing lock file to disk. Path: c:\users\elad\documents\visual studio 2017\Projects\App1\App1\obj\project.assets.json
> Restore completed in 1.97 sec for c:\users\elad\documents\visual studio 2017\Projects\App1\App1\App1.csproj.
> Successfully installed 'Newtonsoft.Json 9.0.1' to App1
> Successfully installed 'System.Reactive 3.0.0' to App1
> Successfully installed 'System.Reactive.Core 3.0.0' to App1
> Successfully installed 'System.Reactive.Interfaces 3.0.0' to App1
> Successfully installed 'System.Reactive.Linq 3.0.0' to App1
> Successfully installed 'System.Reactive.PlatformServices 3.0.0' to App1
> Successfully installed 'System.Reactive.Windows.Threading 3.0.0' to App1
> Successfully installed 'System.Reactive.WindowsRuntime 3.0.0' to App1
> Successfully installed 'System.ValueTuple 4.0.0-rc3-24212-01' to App1
> Successfully installed 'WampSharp 1.2.5.36-beta' to App1
> Successfully installed 'WampSharp.Default 1.2.5.36-beta' to App1
> Successfully installed 'WampSharp.Default.Client 1.2.5.36-beta' to App1
> Successfully installed 'WampSharp.NewtonsoftJson 1.2.5.36-beta' to App1
> Successfully installed 'WampSharp.Windows 1.2.5.36-beta' to App1
> Executing nuget actions took 3.13 sec
> Time Elapsed: 00:00:05.4731099
> ========== Finished ==========

Elad

**Comment by RSFalcon7** [comment]
I'm using VS 2015 Professional. Could be a issue of the Visual Studio version? or maybe some missing dependency on my machine?

**Comment by darkl** [comment]
I don't know. I never managed to make Windows Universal applications to
work on my computer with Visual Studio 2015 (and I tried a couple of times).

Maybe you could try Visual Studio 2017, its installation is short and it
doesn't take much space.

Elad

**Comment by RSFalcon7** [comment]
So, it seems to me that the issue is related to vs2015's packet manager.

Are there build from the source instructions anywhere?

**Comment by darkl** [comment]
No need to build from source, just add manually the dll references from the
UWP folder. (You will need to install manually System.Reactive 3.10 and
Newtonsoft.Json 9.0.1 as well)

Elad

**Comment by RSFalcon7** [comment]
Successfully installed System.Reactive and Newtonsoft.Json, where can I find the dll to reference?

**Comment by darkl** [comment]
Get the WampSharp packages from NuGet (using the command line for
instance), the dlls are there (in the lib folder).

Elad

**Comment by RSFalcon7** [comment]
Which dlls should I include?

I tried to include the WampSharp.Default.Client.dll from the `portable-win81+wpa81` dir, but the simplest `Getting started with a WAMPv2 Client` doesn't work because of missing symbols (e.g. IWampChannel and IWampRealmProxy).

**Comment by darkl** [comment]
Include WampSharp.dll, WampSharp.NewtonsoftJson.dll, WampSharp.Windows.dll, WampSharp.Default.Client.dll. You would also need to install System.ValueTuple which I forgot to mention before.

Elad

**Comment by RSFalcon7** [comment]
Thanks a lot for your support, now I'm able to compile a simple test code.
But in runtime, `DefaultWampChannelFactory` is generating this exception:

```
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Is this related?

**Comment by darkl** [comment]
Did you try updating Microsoft.NETCore.UniversalWindowsPlatform to version
5.2.2?

**Comment by RSFalcon7** [comment]
I was using the manually added dlls, just cleaned the project and updated the project.json to 5.2.2 and it is making progress.

**Comment by darkl** [comment]
@RSFalcon7, did it work for you?

**Comment by RSFalcon7** [comment]
Yes! Thank you very much!

Perhaps it would be nice to upgrade the UWP version on the mainstream repo as a workaround while this isn't fixed on the right place, so less people are affected by this.

**Comment by darkl** [comment]
I'll release a NuGet package with a Microsoft.NETCore.UniversalWindowsPlatform version >= 5.2.2 dependency sometime on this weekend.

**Comment by RSFalcon7** [comment]
awesome

**Comment by dancgr** [comment]
Thank you @darkl! You have been very helpfull, we were able to finish our app.

**Comment by darkl** [comment]
[Done](https://www.nuget.org/packages/WampSharp).
