### ISSUE TITLE
Dependencie problem

### ISSUE THREAD

**Issue by Driky** [Code-Sharp/WampSharp#196]
When I use 
`
Install-Package WampSharp.Default -Pre
`
to install the library  and then try the client snippet you can find in the client tutorial. I get: 
`
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.'`

When I resolve this part by installing the package by specifying to nuget the version I want , I get another dependencie error. Do I misunderstand something or is there a real problem with the dependencies ?

**Comment by darkl** [comment]
This is somehow because of the new Rx4.0 package. After installing, update
manually System.Reactive to the lower version 3.1 (or something like that).
I need to check why this happens though.

**Comment by Driky** [comment]
I already installed the good version manually now I get : 
`System.IO.FileNotFoundException: 'Could not load file or assembly 'WampSharp.WebSocket4Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'`

**Comment by allatrue** [comment]
I experienced similar problems till I upgraded NuGet package manager to the latest version.

**Comment by yohsk10** [comment]
Have you a list of the different libraries (and versions) their are missing ? Or have you found a way to install WampSharp correctly ?

**Comment by darkl** [comment]
Hi all,
Please try installing Microsoft.NETCore.UniversalWindowsPlatform version
5.2.2 before installing WampSharp on Visual Studio 2015. I think this
should work.

Elad

**Comment by yohsk10** [comment]
Hi, thanks for reply. It does not install it for me beacause I am on a project on VS2017 and in .NET 4.6.2. It is possible that WampSharp (or one of its libraries) is not compatible with the new .NET framework ?

**Comment by darkl** [comment]
No, it should work fine.

> Attempting to gather dependency information for package 'WampSharp.Default.1.2.5.36-beta' with respect to project 'ConsoleApp6', targeting '.NETFramework,Version=v4.6.2'
> Gathering dependency information took 6 sec
> Attempting to resolve dependencies for package 'WampSharp.Default.1.2.5.36-beta' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'WampSharp.Default.1.2.5.36-beta'
> Resolved actions to install package 'WampSharp.Default.1.2.5.36-beta'
> Retrieving package 'Castle.Core 3.3.1' from 'nuget.org'.
> Retrieving package 'Fleck 0.13.0.57' from 'nuget.org'.
> Retrieving package 'MsgPack.Cli 0.6.2' from 'nuget.org'.
> Retrieving package 'Newtonsoft.Json 6.0.5' from 'nuget.org'.
> Retrieving package 'Newtonsoft.Msgpack 0.1.10' from 'nuget.org'.
> Retrieving package 'System.Collections.Immutable 1.2.0' from 'nuget.org'.
> Retrieving package 'System.Reactive 4.0.0-preview00001' from 'nuget.org'.
> Retrieving package 'System.Threading.Tasks.Dataflow 4.6.0' from 'nuget.org'.
> GET https://www.nuget.org/api/v2/package/WampSharp.WebSockets/1.2.5.36-beta
> Retrieving package 'System.ValueTuple 4.0.0-rc3-24212-01' from 'nuget.org'.
> Retrieving package 'WampSharp 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.Default 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.Default.Client 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.Default.Router 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.Fleck 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.NewtonsoftJson 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.NewtonsoftMsgpack 1.2.5.36-beta' from 'nuget.org'.
> Retrieving package 'WampSharp.WebSockets 1.2.5.36-beta' from 'nuget.org'.
> Adding package 'Castle.Core.3.3.1' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> OK https://www.nuget.org/api/v2/package/WampSharp.WebSockets/1.2.5.36-beta 855ms
> Installing WampSharp.WebSockets 1.2.5.36-beta.
> Added package 'Castle.Core.3.3.1' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Castle.Core.3.3.1' to 'packages.config'
> Successfully installed 'Castle.Core 3.3.1' to ConsoleApp6
> Adding package 'Fleck.0.13.0.57' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Fleck.0.13.0.57' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Fleck.0.13.0.57' to 'packages.config'
> Successfully installed 'Fleck 0.13.0.57' to ConsoleApp6
> Adding package 'MsgPack.Cli.0.6.2' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'MsgPack.Cli.0.6.2' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'MsgPack.Cli.0.6.2' to 'packages.config'
> Successfully installed 'MsgPack.Cli 0.6.2' to ConsoleApp6
> Adding package 'Newtonsoft.Json.6.0.5' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Newtonsoft.Json.6.0.5' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Newtonsoft.Json.6.0.5' to 'packages.config'
> Executing script file 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages\Newtonsoft.Json.6.0.5\tools\install.ps1'...
> Successfully installed 'Newtonsoft.Json 6.0.5' to ConsoleApp6
> Adding package 'Newtonsoft.Msgpack.0.1.10' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Newtonsoft.Msgpack.0.1.10' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'Newtonsoft.Msgpack.0.1.10' to 'packages.config'
> Successfully installed 'Newtonsoft.Msgpack 0.1.10' to ConsoleApp6
> Adding package 'System.Collections.Immutable.1.2.0' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Collections.Immutable.1.2.0' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Collections.Immutable.1.2.0' to 'packages.config'
> Successfully installed 'System.Collections.Immutable 1.2.0' to ConsoleApp6
> Adding package 'System.Reactive.4.0.0-preview00001' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Reactive.4.0.0-preview00001' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Reactive.4.0.0-preview00001' to 'packages.config'
> Successfully installed 'System.Reactive 4.0.0-preview00001' to ConsoleApp6
> Adding package 'System.Threading.Tasks.Dataflow.4.6.0' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Threading.Tasks.Dataflow.4.6.0' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.Threading.Tasks.Dataflow.4.6.0' to 'packages.config'
> Successfully installed 'System.Threading.Tasks.Dataflow 4.6.0' to ConsoleApp6
> Adding package 'System.ValueTuple.4.0.0-rc3-24212-01' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.ValueTuple.4.0.0-rc3-24212-01' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'System.ValueTuple.4.0.0-rc3-24212-01' to 'packages.config'
> Successfully installed 'System.ValueTuple 4.0.0-rc3-24212-01' to ConsoleApp6
> Adding package 'WampSharp.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.Fleck.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Fleck.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Fleck.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.Fleck 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.NewtonsoftJson.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.NewtonsoftJson.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.NewtonsoftJson.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.NewtonsoftJson 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.NewtonsoftMsgpack.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.NewtonsoftMsgpack.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.NewtonsoftMsgpack.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.NewtonsoftMsgpack 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.Default.Router.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.Router.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.Router.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.Default.Router 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.WebSockets.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.WebSockets.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.WebSockets.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.WebSockets 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.Default.Client.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.Client.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.Client.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.Default.Client 1.2.5.36-beta' to ConsoleApp6
> Adding package 'WampSharp.Default.1.2.5.36-beta', which only has dependencies, to project 'ConsoleApp6'.
> Adding package 'WampSharp.Default.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.1.2.5.36-beta' to folder 'c:\users\elad\documents\visual studio 2017\Projects\ConsoleApp6\packages'
> Added package 'WampSharp.Default.1.2.5.36-beta' to 'packages.config'
> Successfully installed 'WampSharp.Default 1.2.5.36-beta' to ConsoleApp6
> Executing nuget actions took 25.17 sec
> Time Elapsed: 00:00:31.9469483
> ========== Finished ==========

Elad

**Comment by nunobaraujo** [comment]
Yes, I'mhaving the same problem with a NET4.6 test project, Nuget installed packages like in the above post, but there is a error when connecting: 
"Could not load file or assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.". 

Tried downgrading all Reactive libraries from System.Reactive.4.0.0-preview00001 to 3.0 but no luck. 
Anyone got any luck solving this?

This is the stack:
  at WampSharp.V2.Client.WampRealmProxy`1..ctor(String name, IWampServerProxy proxy, IWampBinding`1 binding, IWampClientAuthenticator authenticator)
   at WampSharp.V2.Client.WampChannelBuilder`1.WampRealmProxyFactory.Build(WampClient`1 client)
   at WampSharp.V2.Client.WampClient`1..ctor(IWampRealmProxyFactory`1 realmFactory)
   at WampSharp.V2.Client.WampChannelBuilder`1.CreateChannel(String realm, IControlledWampConnection`1 connection)
   at WampSharp.V2.Client.WampChannelFactory.CreateChannel[TMessage](String realm, IControlledWampConnection`1 connection, IWampBinding`1 binding)
   at WampSharp.V2.Client.WampChannelFactory.CreateChannel[TMessage](String realm, Func`1 connectionFactory, IWampBinding`1 binding)
   at WampSharp.V2.DefaultWampChannelFactory.CreateChannel[TMessage](String address, String realm, IWampTextBinding`1 binding)
   at WampSharp.V2.DefaultWampChannelFactory.CreateJsonChannel(String address, String realm)
   at ConsoleApp1.WampTestClient.Connect(String serverAddress) in D:\dev\nbsoft\NBsoft.InvXPress\test\ConsoleApp1\WampTestClient.cs:line 20

Nuno

**Comment by darkl** [comment]
Trying installing manually System.Reactive 3.0 to an empty project and only
then install WampSharp.

Elad

**Comment by nunobaraujo** [comment]
Only today ai got time to check it out. So it worked out with that hack and 1 more:

> Installed System.Reactive 3.0.0
Error =
{"Could not load file or assembly 'SuperSocket.ClientEngine, Version=0.8.0.6, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"SuperSocket.ClientEngine, Version=0.8.0.6, Culture=neutral, PublicKeyToken=null"}

> Installed SuperSocket.ClientEngine 0.8.0.6
Connection succeded, its done.

**Comment by nunobaraujo** [comment]
Well this is weird.
I created the project as console (Console2.exe), when console2 project is referenced on another (.NET 4.6) project and call the connect method the line:

var factory = new DefaultWampChannelFactory();

throws the error:

{"Could not load file or assembly 'System.Reactive.Interfaces, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.":"System.Reactive.Interfaces, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263"}

Its weird because "System.Reactive.Interfaces, Version=3.0.1000.0" doesn't exist on nuget
I even copied all output from console2\bin to mainproject\bin and the result is the same.

If I run console2 it connects OK

Nuno

**Comment by nunobaraujo** [comment]
Ops, problem solved. It was a bad App.config file on mainproject, I just added som many references to it regarding wampsharp and system.reactive that App.config had the following:

```
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" /></startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Interfaces" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1000.0" newVersion="3.0.1000.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Core" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.3000.0" newVersion="3.0.3000.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reactive.Linq" publicKeyToken="94bc3704cddfc263" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.3000.0" newVersion="3.0.3000.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

After removing the <runtime> section everything went OK.

Hope this helps anyone. :)

Best regards, 
Nuno

**Comment by pantonis** [comment]
Same problem here. Tried to remove <runtime> but no luck

**Comment by Stanger007** [comment]
Tools -> NuGet Package Manager -> Package Manager Console

Install-Package System.Reactive.Interfaces

Worked for me. I have just started using  WampSharp today, so I don't if this is a working fix because i have no working application yet.

Good luck

**Comment by Stanger007** [comment]
I have managed to get a working wss authentication. Doing so, I stumbled on another exception:
C#
`IWampSubject topic = realmProxy.Services.GetSubject();`

This line optained a FileNotFoundException caused by System.Reactive.Linq.

My fix was: Delete System.Reactive from reference tree. Add the problematic packages manually:

Install-Package System.Reactive.Interfaces
Install-Package System.Reactive.Linq

**Comment by pantonis** [comment]
Yes I did the same

**Comment by jaimewyant** [comment]
I had to do the same myself.

**Comment by darkl** [comment]
Should work fine now.

Elad
