### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by yohsk10** [Code-Sharp/WampSharp#197]
Hi all,

I have a strange problem with the reception of the notification in my client Subscriber. I have two programs, one is the router publisher and the other is the client subscriber. When I connect for the first time to my router I do not receive notifications in my client application. The problem is not always true, sometimes it will receive the notifications but it is rare.
When I connect to the router with a second client then I will receive notifications without any problem.

I checked to my router publisher and it sends the notification on the good topic and with the good data. I subscribe to this topic in my client and I implement the Action<Error> but I have no message.

It is a problem of Wampsharp or maybe with the communication library ? My NuGet packages are :

Castle.Core version="3.3.1" targetFramework="net40"
"Ix-Async" version="1.2.5" targetFramework="net40"
"MsgPack.Cli" version="0.6.2" targetFramework="net40"
"Newtonsoft.Json" version="6.0.5" targetFramework="net40"
"Newtonsoft.Msgpack" version="0.1.10" targetFramework="net40"
"Rackspace.Collections.Immutable" version="1.1.36" targetFramework="net40"
"Rx-Core" version="2.2.5" targetFramework="net40"
"Rx-Interfaces" version="2.2.5" targetFramework="net40"
"Rx-Linq" version="2.2.5" targetFramework="net40"
"Rx-Main" version="2.2.5" targetFramework="net40"
"Rx-PlatformServices" version="2.2.5" targetFramework="net40"
"SuperSocket.ClientEngine.Core" version="0.8.0.6" targetFramework="net40"
"WampSharp" version="1.2.5.36-beta" targetFramework="net40"
"WampSharp.Default.Client" version="1.2.5.36-beta" targetFramework="net40"
"WampSharp.NewtonsoftJson" version="1.2.5.36-beta" targetFramework="net40"
"WampSharp.NewtonsoftMsgpack" version="1.2.5.36-beta" targetFramework="net40"
"WampSharp.WebSocket4Net" version="1.2.5.36-beta" targetFramework="net40"
"WebSocket4Net" version="0.15.0-beta4" targetFramework="net40"

Thank you !

**Comment by darkl** [comment]
By default, a client does not receive its own publications. You can change that by setting exclude_me = false.
I'm guessing this is what you are referring to.

**Comment by yohsk10** [comment]
I think my explanation is not so clear. My router publisher will receive data from a third program and it will publish the data to the clients who are connected :

[Program] --- send new data to router ---> [Router publisher] --- publish the value ---> [Client subscriber]

But the "publish the value" part does not work always.

**Comment by darkl** [comment]
Please add some simple code (two console applications) that reproduce the
problem, so I can check it.

Elad

**Comment by yohsk10** [comment]
I try with two console applications but I notice that the problem is exclusively a problem of timing, I cannot reproduce it... I think the problem is on the [Program/Router] side. I will investigate on it.
Excuse me for the lost time.

**Comment by yohsk10** [comment]
If someone has the same problem I solved him using the function "Realm.TopicContainer.Publish" instead of the "OnNext" method.

Leo
