### ISSUE TITLE
Custom pub/sub message handling/pipelining

### ISSUE THREAD

**Issue by maciejjarzynski** [Code-Sharp/WampSharp#198]
Hello,
I would like to wrap my message with a context with my own tracing data when publishing, then in Router to unwrap that and put that context data into the logging like it's done here with SessionId:
https://github.com/Code-Sharp/WampSharp/blob/f9f24a132fd039ba3a422124ff64432976f952ea/src/net45/WampSharp/Core/Listener/WampListener.cs#L103

The problem is, I cannot replace WampListener with my own implementation, because as I see in the code it's always instantiated with `new` keyword. The same with `IWampIncomingMessageHandler`, all here:

https://github.com/Code-Sharp/WampSharp/blob/f9f24a132fd039ba3a422124ff64432976f952ea/src/net45/WampSharp/WAMP2/V2/Api/Server/WampBindingHost.cs

Is there any other way it can be done per message scope?

**Comment by darkl** [comment]
It is possible.
One possible way is to pass your own IWampRealmContainer to the WampHost constructor and create a Realm class that wraps the TopicContainer with your own TopicContainer where you will override the publish methods to do as you wish.

Elad
