### ISSUE TITLE
Issue with Xamarin Code

### ISSUE THREAD

**Issue by Pseudocode99** [Code-Sharp/WampSharp#200]
I trying to connect to poloniex with this sample code.

`  var channelFactory = new DefaultWampChannelFactory();

            var channel = channelFactory.CreateJsonChannel("wss://api.poloniex.com", "realm1");

            Func<Task> connect = async () =>

            {
                await channel.Open();

                var tickerSubject = channel.RealmProxy.Services.GetSubject("ticker");

                var subscription = tickerSubject.Subscribe(evt =>

                    {
                        var currencyPair = evt.Arguments[0].Deserialize<string>();

                        var last = evt.Arguments[1].Deserialize<decimal>();

                        Console.WriteLine($"Currencypair: {currencyPair}, Last: {last}");
                    },
                    ex => { Console.WriteLine($"Oh no! {ex}"); });
            };

            var reconnector =
                new WampChannelReconnector(channel, connect);

            reconnector.Start();`

In a standard console app, i have no problems to connect to the subscription.
But in a Xamarin Android app, they try endless to connect to the server.
Manifest is set:
 <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

Can i use WampSharp with Xamrin and has anyone else this issues or some hints?
Thanks for help

**Comment by darkl** [comment]
@RyanMelenaNoesis

**Comment by darkl** [comment]
My first guess would be to add ConfigureAwait false on all awaited Tasks.

Elad
