### ISSUE TITLE
MsgPack and wampcc problem

### ISSUE THREAD

**Issue by Green7** [Code-Sharp/WampSharp#203]
Hello
I want to call remote procedure from wampsharp to wampcc C++ app (rawsockets).
With json serialization everything works ok. But after switch to msgpack I can't get RPC results.

I checked why and it looks like the message is not properly decoded.
For example cpp application send RPC result message:
[50, 572903043586859, {}, ["hello test"], {}]
but after decoding (in MessagePackParser.WampMessage<JToken> Parse(Stream stream)) I have:
{[50, 1650940715, {}, ["hello test"],{}]}

so message id is invalid and RPC response can't be handled.

**Comment by darkl** [comment]
Can you somehow attach the serialized array in base64? I need to check how it is decoded via other libraries/languages.

Elad

**Comment by Green7** [comment]
Of course.
Cpp sent: 
[50, 677475426309296, {}, ["hello test"], {}]

CSharp received (base64):  
lTLOCiEUsICRqmhlbGxvIHRlc3SA

and CSharp after decoding:
{[50,169940144, {}, ["hello test"],{}]}

**Comment by darkl** [comment]
This is probably a bug with wampcc. Here are the results of deserialization with other libraries.

### u-msgpack-python:

> import umsgpack
> import base64
> message = "lTLOCiEUsICRqmhlbGxvIHRlc3SA"
> bytes = base64.b64decode(message)
> deserialized = umsgpack.unpackb(bytes)
> deserialized
`[50, 169940144, {}, ['hello test'], {}]`

### msgpack-python:
> import msgpack
> import base64
> message = "lTLOCiEUsICRqmhlbGxvIHRlc3SA"
> bytes = base64.b64decode(message)
> deserialized = msgpack.unpackb(bytes)
> deserialized
`[50, 169940144, {}, [b'hello test'], {}]`

### msgpack-cli

```csharp
var array =
    MessagePackSerializer
        .UnpackMessagePackObject
        (new MemoryStream
             (Convert.FromBase64String("lTLOCiEUsICRqmhlbGxvIHRlc3SA")));
```csharp

`[ 50, 169940144, {}, [ "hello test" ], {} ]`

### MessagePack-CSharp

```csharp
string json =
    MessagePackSerializer.ToJson
        (Convert.FromBase64String("lTLOCiEUsICRqmhlbGxvIHRlc3SA"));
```

**Comment by darkl** [comment]
Note that [677475426309296 mod 2^32 = 169940144](http://www.wolframalpha.com/input/?i=677475426309296+mod+2%5E32). Hope this helps finding the problem.

**Comment by Green7** [comment]
Thank you. You're right.
This is error on cpp side, I found it. 
Integer was always serialized as 32bit this is the cause of the problems.
