### ISSUE TITLE
How to send binary data ?

### ISSUE THREAD

**Issue by Green7** [Code-Sharp/WampSharp#204]
MsgPack support binary data. How to send it in WampSharp ?

**Comment by darkl** [comment]
For the reflection based roles, just declare a parameter of type byte[].

Elad

**Comment by Green7** [comment]
I tried but I have exception:
'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. '

So it's looks that byte[] should be streamed as base64 string ?

**Comment by darkl** [comment]
I'm not sure. I suspect this has something to do with the fact that msgpack introduced some way to distinguish between strings and byte arrays. Please attach your serialized message in base 64 and I'll try to investigate it.

**Comment by Green7** [comment]
Here is:
json: 
[50, 294229051280563, {}, ["\u0000\u0001\u0002"], {}]

base64: lTLPAAELmYoVjLOAkaMAAQKA

But I think that the problem problem lies in wapmcc (I'm sending data from wampcc). 
In wampcc I found only option to stream bytes as string, so probably also msgpack used string type.

**Comment by darkl** [comment]
This is again a problem with wampcc. The expected serialized value should be lTLPAAELmYoVjLOAxAMAAQKA. The values differ in the 12 and 13 positions: wampcc output has 0x91 in its 12th position which represents a beginning of a new array of length 1 and then has 0xa3 in its 13th position which represents a beginning of a string of length 3. While the expected output is to have 0xc4 in the 12th position which indicates a short array and 0x03 in the 13th position which indicates length 3.

[The MessagePack spec](https://github.com/msgpack/msgpack/blob/master/spec.md).

Elad

**Comment by Green7** [comment]
Thank you for help.
As I thought wampcc does not support binary data :(
https://github.com/darrenjs/wampcc/issues/7#issuecomment-319593379
