### ISSUE TITLE
"no procedure 'wamp.subscription.list' registered"

### ISSUE THREAD

**Issue by petrovalex** [Code-Sharp/WampSharp#205]
Is MetaApi supported in AspNet.Core? 
I am starting WampHost in AspNet.Core application and then from the client using that metadata api:
AvailableGroups groups = _meta.GetAllSubscriptionIds();
before pushing message in order to find if there are subscribers to the topic. 
But getting the error "no procedure 'wamp.subscription.list' registered".

Am I doing something wrong?
Using 1.2.5.40-beta version.

Thanks.

**Comment by darkl** [comment]
You need to add this kind of call before opening the host:

var disposable =
host.RealmContainer.GetRealmByName("myrealm").HostMetaApiService();

Elad

**Comment by petrovalex** [comment]
Thanks a lot. That works.
