### ISSUE TITLE
.NET Core Compatibility

### ISSUE THREAD

**Issue by alek5k** [Code-Sharp/WampSharp#207]
Hi Elad,

I tried to run the WampSharp client in a docker container for dot net core derived from image: 

`microsoft/dotnet:1.1-sdk`

But i would get the exception:

`Unhandled Exception: System.AggregateException: One or more errors occurred. (The WebSocket protocol is not supported on this platform.) ---> System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.`

I noticed the WampSharp.Default nuget package is not infact using WebSocket4Net, so I assume it is trying to fall back to a native .netcore websocket implementation that isn't supported yet. 

Please also note that the nuget package description says that it uses WebSocket4Net in the nuget package description ["WampSharp above Fleck, Newtonsoft.Json Newtonsoft.Msgpack and WebSocket4Net"](https://www.nuget.org/packages/WampSharp.Default/1.2.5.40-beta)

I managed to get my program running in the dotnet1.1 container by only installing the following:

`Install-Package WampSharp.WebSocket4Net -Pre `
`Install-Package WampSharp.NewtonsoftJson -Pre`

I then noticed that this combination of packages does not contain a reference to the DefaultWampChannelFactory class.

I took the class from [this .net45 code](https://github.com/Code-Sharp/WampSharp/blob/f9f24a132fd039ba3a422124ff64432976f952ea/src/net45/WampSharp.Default.Client/WAMP2/V2/DefaultWampChannelFactory.cs) and trimmed out the msgpack implementations for my purposes.

Is there a better way of getting WampSharp to work on .net core using WebSocket4Net? Are there plans to fall back to WebSocket4Net implementation for .net core, or provide some configurability for which type of websocket mechanism is being used?

Alternatively, a simpler solution might be for the DefaultWampChannelFactory class to be included with the WampSharp.WebSocket4Net package, and some documentation on how to use the WebSocket4Net implementation in a README or docs somewhere.

**Comment by darkl** [comment]
You don't need DefaultWampChannelFactory, just use fluent syntax. (Add a
`using WampSharp.V2.Fluent; `directive).

**Comment by alek5k** [comment]
OK, I have used the new form, I will leave it here for reference in case anyone else is searching:

```
IWampChannel channel =
                factory.ConnectToRealm("realm1")
                       .WebSocketTransport("ws://127.0.0.1:8080/ws")
                       .JsonSerialization()
                       .Authenticator(authenticator)
                       .Build();
```
I suppose the docs are all referencing the old method.
Thanks for your help.

**Comment by Andyriod** [comment]
@alek5k thank you for leaving your code, but where from is the 'factory' object?

**Comment by darkl** [comment]
`new WampChannelFactory()` or `new DefaultWampChannelFactory()`.
