### ISSUE TITLE
Target .Net Standard 2.0

### ISSUE THREAD

**Issue by burningice2866** [Code-Sharp/WampSharp#210]
Is there any chance WampSharp will be updated to target .Net Standard 2.0 in the nearest future?

**Comment by darkl** [comment]
It already targets netstandard 1.3, which from my understanding implies
that it is netstandard 2.0 compatible (lower version is better because it
is compatible with more targets).

Elad

**Comment by burningice2866** [comment]
@darkl Issue with .net standard before 2.0 is that a 4.6.1 project will pull in a ton-load of unreleated packages and assemblies which has been fixed in .net standard 2.0 where 4.6.1 is a 1:1 compatible and therefor won't pull in any other dependencies.

**Comment by darkl** [comment]
Can't this be handled by updating the dependencies to the latest version?
If it can, I prefer updating these.
If it can't be handled this way, we need to wait that all WampSharp's
dependencies update to support netstandard 2.0 (these are mainly
Newtonsoft.Json, msgpack-cli, System.Reactive and WebSocket4Net). This
makes me feel as if we have returned back in time to the previous summer.

Elad

**Comment by burningice2866** [comment]
As i understand it, and i'm sure i've got it all wrong anyway since the .Net Standard is confusing business, but the issue is not that the references no-op packages are old and should be updated, but they shouldn't be there in the first place.

When you target .Net Standard 1.3, NuGet will pull in all these (when using framework 4.6+) irrelevant packages

![image](https://user-images.githubusercontent.com/333952/29298892-cee1c36e-8149-11e7-895e-10fae711e70d.png)

while .Net standard 2.0 simply has no dependencies.

![image](https://user-images.githubusercontent.com/333952/29298925-0a42a37e-814a-11e7-8979-00e1062e44b9.png)

**Comment by darkl** [comment]
Ok, but if we depend on System.Reactive and it has these kind dependencies,
then we will have them too.

Maybe @onovotny or someone that is more involved in the netstandard world
can clear these things out.

Elad

**Comment by onovotny** [comment]
They're not all no-op, some of them are type forwarders and some of them add functionality. The best solution really is to use `PackageReference` everywhere instead of `packages.config` and most of it will be hidden. You can use `PackageReference` in any project type and can specify the default in the Options -> NuGet settings.

**Comment by burningice2866** [comment]
@darkl you're right... System.Reactive still targets NETStandard.Library 1.6.1 which is the real sinner here.

If we look at [NETStandard.Library 1.6.1](https://www.nuget.org/packages/NETStandard.Library/1.6.1) vs [2.0.0](https://www.nuget.org/packages/NETStandard.Library/2.0.0) we clearly see the difference where [2.0](https://www.nuget.org/packages/NETStandard.Library/2.0.0) has a explicit target for 4.6.1 which doesn't have any dependencies while [1.6.1](https://www.nuget.org/packages/NETStandard.Library/1.6.1) didn't have a explicit 4.6.1 target and therefor defaulted back to NetStandard 1.3 which has a ton of dependencies :(

Its like Async, if you want the real benefits it has to be all-the-way.

**Comment by darkl** [comment]
Newtonsoft.Json [netstandard 2.0 support is available](https://github.com/JamesNK/Newtonsoft.Json/commit/ab3315f1d5e57c70203c904be79d8e951bf09794). Waiting for Castle.Core, System.Reactive.

Elad

**Comment by darkl** [comment]
Hi I worked on this today, and I think it should work now. Please try WampSharp v1.2.7.45-beta from NuGet.

Elad

**Comment by darkl** [comment]
I'm closing this. Please write here if something does not work for you.
