### ISSUE TITLE
Breaking change in latest 41beta

### ISSUE THREAD

**Issue by llehn** [Code-Sharp/WampSharp#211]
Hi Guys,

did you really just introduce a breaking change in a patch release? 
https://github.com/Code-Sharp/WampSharp/commit/913e3b92a51dcb25de1efa08436a7e2a632da982#diff-43b1bc2152baa1e81859a7cae18e576b

Changing return values in src/net45/WampSharp/WAMP2/V2/Rpc/Interfaces/IWampRpcOperation.cs does break code.

Was it on purpose? I need to know, because when a version looks like semver, I did assume the version adheres to semver logic, i.e. breaking changes do increment major number. Knowing WampSharp doesn't care about that means we need explicitely evaluate whether new versions break something.

**Comment by darkl** [comment]
The release notes say that this version breaks this interface.

WampSharp uses its own (non standard) versioning scheme. Version names are
1.2.major.buildindex-beta. 2 stands for the WAMP protocol version.

Elad
