### ISSUE TITLE
Publish and Subscribe on Same channel

### ISSUE THREAD

**Issue by rdegelo** [Code-Sharp/WampSharp#212]
Hello, I'm trying to create a single channel that will be used to publish and subscribe.
The problem is that subscriber is not receiving the messages.

It works when I use two channels.

My question is, is there any way to publish and subscribe in the same channel?
Thanks,

**Comment by darkl** [comment]
You need to publish the message with PublishOptions.ExcludeMe = false.

Elad

**Comment by rdegelo** [comment]
Hello Elad, thanks!

Is there any way to set this option in the subject instead of sending this option every time?

**Comment by darkl** [comment]
There is no such option currently. You might want to wrap this in a custom
class of yours.

Elad

**Comment by rdegelo** [comment]
Alright, thank you!
