### ISSUE TITLE
Fluent syntax with .net core 2.0: WebSocketTransport not found

### ISSUE THREAD

**Issue by Jopie64** [Code-Sharp/WampSharp#213]
Hi,

I'm trying to use WampSharp with .net core 2.0 using the Fluent syntax to create a channel.
When I try to do this, it doesn't seem to find the `WebSocketTransport()` method. I tried to narrow it down, and it seems that this method should be an extension method of `IRealmSyntax`. But it looks like that isn't the case for me, and now I am unable to build a channel.
Am I missing something?
I tried to add the `using WampSharp.V2.Transports;` and some other directives but it didn't help...

**Comment by darkl** [comment]
Please add the `using WampSharp.V2.Fluent;` directive.
You also need to install WampSharp.Default.Client (or alternatively install WampSharp.NewtonsoftJson and WampSharp.WebSockets or WampSharp.WebSocket4Net).

See also this [comment](https://github.com/Code-Sharp/WampSharp/issues/207#issuecomment-320882316).

Elad

**Comment by Jopie64** [comment]
Wow this was such a quick answer!
Adding `WampSharp.Default.Client` resolved the issue. I can continue now, thanks so much! :)
