### ISSUE TITLE
adding hosting of static websites

### ISSUE THREAD

**Issue by dimoMacke** [Code-Sharp/WampSharp#216]
Hello,

Crossbar.io has the nice feature that it can also serve static files to a browser. What would be the best approach to do something similar for the  wampsharp router?

Best regards,
Dieter

**Comment by darkl** [comment]
Probably using one of the ASP.NET Core/ASP.NET/Owin transports. All support static files.
For instance, this is a usage of ASP.NET Core static file hosting:

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseStaticFiles();

    WampHost host = new WampHost();

    app.Map("/ws", builder =>
    {
        builder.UseWebSockets(new WebSocketOptions());

        host.RegisterTransport(new AspNetCoreWebSocketTransport(builder),
            new JTokenJsonBinding());
    });

    host.Open();
}
```

Elad
