### ISSUE TITLE
WampSharp.V2.Core.Contracts.WampConnectionBrokenException

### ISSUE THREAD

**Issue by marcoaal** [Code-Sharp/WampSharp#218]
Hi
I'm sending String objects by publisher in C# each one millisecond to a Crossbar's topic. When I suscribe in this topic for a long time, the onError exception prints: **"WampSharp.V2.Core.Contracts.WampConnectionBrokenException"** and close the connection. The broker Crossbar only print that the suscriber left the topic.
What happened?
This is the publisher's code:
                `DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();`
                `IWampChannel channel = channelFactory.CreateJsonChannel(wsuri, realm);`
                `IWampClientConnectionMonitor monitor = channel.RealmProxy.Monitor;`
                `monitor.ConnectionBroken += OnClose;`
                `monitor.ConnectionError += OnError;`
                `await channel.Open().ConfigureAwait(false);`
                `IWampRealmServiceProvider services = channel.RealmProxy.Services;     `
                `crossbarSubject = services.GetSubject<String>(myTopic);`
               ` crossbarSubject.OnNext(randomString);`

This is the suscriber code:
                `DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();`
               ` IWampChannel channel = channelFactory.CreateJsonChannel(wsuri, realm);`
               ` IWampClientConnectionMonitor monitor = channel.RealmProxy.Monitor;`
                `monitor.ConnectionBroken += OnClose;`
                `monitor.ConnectionError += OnError;`
                `await channel.Open().ConfigureAwait(false);`
                `IWampRealmServiceProvider services = channel.RealmProxy.Services; `    
                `crossbarSubject = services.GetSubject<String>(myTopic);`
                `IDisposable disposable = crossbarSubject .Subscribe(`
                   ` x => { `                       
                        `ProccessString(randomString);`
                    `},`
                    `onError => {`
                        `Console.WriteLine("error:  " + onError);`
                   ` },`
                    `() => Console.WriteLine("Done...")`
                ` );`

I'm using crossbar for python 3.6 64 bits, WampSharp v2 and .NET Framework 4.6.1

**Comment by darkl** [comment]
Can you please attach the exception details?
Have you considered using the WampChannelReconnector mechanism?

**Comment by marcoaal** [comment]
Sure, the publisher and suscriber work great for a long time. After that the OnError Exception in the suscription throws:
  `error: WampSharp.V2.Core.Contracts.WampConnectionBrokenException`
Debugging, the subject in the error is: `WampSharp.V2.WampTopicSubject`1[String]`
I thinked that the Crossbar broker was queueing the objects messages and the suscriber got the queue so failed, then I edited its file configuration:
`"store": {`
                        `"type": "memory",`
                        `"call-queue": [`
                            `{`
                                `"uri": "",`
                                `"match": "prefix",`
                               ` "limit": 0`
                           ` }`
                       ` ]`
                    `}`
But the exception throwed the same message

**Comment by darkl** [comment]
[WampConnectionBrokenException](https://github.com/Code-Sharp/WampSharp/blob/f9f24a132fd039ba3a422124ff64432976f952ea/src/net45/WampSharp/WAMP2/V2/Core/Contracts/WampConnectionBrokenException.cs) has several properties (CloseType, Reason, etc). Can you please attach these details?

**Comment by marcoaal** [comment]
Sure the only output is:
`WampSharp.V2.Core.Contracts.WampConnectionBrokenException`
`Additional information: Connection got broken. CloseType:Disconnection`

The WampChannelReconnector mechanism was considered but I don´t want to lost messages in the reconnection process

**Comment by darkl** [comment]
Can you provide two simple Program.cs files (one for publisher and one for subscriber) and a crossbario config file that reproduce this?
How long does it take to reproduce this (what is a long time)?

Elad

**Comment by marcoaal** [comment]
There is the publisher and suscriber with the crossbario config:
[subpubString.zip](https://github.com/Code-Sharp/WampSharp/files/1399031/subpubString.zip)

**Comment by darkl** [comment]
Code doesn't compile.
