### ISSUE TITLE
Custom headers for SignalR transport

### ISSUE THREAD

**Issue by siberianguy** [Code-Sharp/WampSharp#222]
I'm trying to communicate to a SignalR hub that is hidden behind CloudFlare. To bypass CloudFlare you need to pass a couple of custom headers but unfortunately SignalR client doesn't support it. I see WampSharp supports SignalR transport, so I got curious if it's possible to implement this scenario using WampShart.

**Comment by darkl** [comment]
I don't think that anyone ever used this SignalR transport.
Anyway, it uses the lower level of SignalR (the transport layer), and
therefore it won't work with hubs (which is higher level).

**Comment by siberianguy** [comment]
Thanks for your response! Sad though. For a second I felt like a found a cool workaround :)
