### ISSUE TITLE
Problem sending UTF-8 strings

### ISSUE THREAD

**Issue by andeb91** [Code-Sharp/WampSharp#223]
Hi everybody, 
I'm having big problems sending to the router a UTF-8 encoded string, so big that I can't received it UTF-8 coded. 
Is there a manner to manage this kind of string encoding?

Thanks in advance!

**Comment by darkl** [comment]
Too many details are missing. What router are you using? What client?
Is this similar to this issue? https://github.com/crossbario/autobahn-js/issues/312

Elad

**Comment by andeb91** [comment]
Sorry for details missing. 
The router is a Crossbar.io WAMP router running on a Ubuntu machine; the client is implemented in C# on Windows with the lastest release of the WampSharp library.
I'm sending a UTF-8 string from the client to the router, but when I call the mystring.decode('utf-8') router-side an exception is raised. Printing the hexadecimal value of mystring I can see that non-ASCII chars aren't UTF-8 encoded. For example if mystring contains the char à I see the hexadecimal value e0 while the exact hexadecimal value will be c3:a0.
And finally no, is not similar to the issue that you linked in the previous comment.
Thanks.
Andrea

**Comment by andeb91** [comment]
No simple code. 
Think about this. Client-side I have a call of a WampProcedure where i pass it a string 
```
[WampProcedure("path.call.connect")]
void connect(string pcName);
```
And in c# code I call 
`proxy.connect("tèstèr");`

On python router I have the function
```
def connect(self, name, details):
     self._name = name.decode('utf-8')
```
This istruction raise an exception. If in this python function I print the hexadecimal value of name I see that non-ASCII chars don't have the exact UTF-8 coding translation.

Andrea

**Comment by darkl** [comment]
Sorry, I'm unable to reproduce it myself. Would like to help you, but I can't without some code reproducing the problem.

Elad

**Comment by darkl** [comment]
Also, please trying sending this string from JavaScript for instance and see if the problem occurs. If it does, then it might be an issue with AutobahnPython.

Elad
