### ISSUE TITLE
Router memory leak in long running channels

### ISSUE THREAD

**Issue by mbett7** [Code-Sharp/WampSharp#225]
`OnConnectionClosed` in `WampRpcOperationCallback` is only unregistered when the connection closes.  Should probably be unregistered after if finishes handling the callback.

![image](https://user-images.githubusercontent.com/32408685/34636320-6e5a6f92-f2ea-11e7-943a-b03605e6ec30.png)

**Comment by darkl** [comment]
Thanks! Should be fixed in latest version.
