### ISSUE TITLE
Callee receiving a class object

### ISSUE THREAD

**Issue by nanodesu88** [Code-Sharp/WampSharp#227]
Hello everybody. Sorry for my bad english. I will try to describe a issue as very short.
i have a classes
```csharp
interface IObj { }
class Obj : IObj { }
```
i want to receive a Obj object
```csharp
interface ICalleeService
{
    [WampProcedure("*")]
    void Method(Obj obj);
}
```
and i call procedure with Obj instance argument
```csharp
rpcProxyLocator.Get<ICalleeService>().Method(new Obj());
```
and it works well.
but when i am trying to receive a instance of IObj interface
```csharp
interface ICalleeService
{
    [WampProcedure("*")]
    void Method(IObj obj);
}
```
i am getting an exception
```
WampSharp.V2.Core.Contracts.WampException: wamp.error.invalid_argument
   в WampSharp.V2.CalleeProxy.WampCalleeProxyInvocationHandler.Invoke[T](ICalleeProxyInterceptor interceptor, MethodInfo method, IOperationResultExtractor`1 extractor, Object[] arguments)
   в WampSharp.V2.CalleeProxy.SyncCalleeProxyInterceptor`1.Invoke(MethodInfo method, Object[] arguments)
   в WampSharp.V2.CalleeProxy.CalleeProxyInterceptorBase.Intercept(IInvocation invocation)
   в Castle.DynamicProxy.AbstractInvocation.Proceed()
```
its probably a bug. can we fix it please?

**Comment by darkl** [comment]
This is not a bug. In order to make your example work, you need to specify
some JSON.net serialization options, which tell JSON.net to write the type
of the serialized value (see
https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm).
You can specify the JsonFormatter settings on various ways, such as via
fluent syntax.

Elad

**Comment by nanodesu88** [comment]
hmm... okay, thanks. where can i read about serialization configuration and fluent syntax?

**Comment by nanodesu88** [comment]
I found a place where i can change a serialization options 
```csharp
new DefaultWampChannelFactory().CreateChannel(
                "ws://127.0.0.1:8001",
                "...",
                new JTokenJsonBinding(JsonSerializer.Create(new JsonSerializerSettings{TypeNameHandling = TypeNameHandling.All})),
                authenticator)
```
its a right place? when i am trying to change the options here i am taking a other exception
```
Необработанное исключение: System.AggregateException: Произошла одна или несколько ошибок. ---> WampSharp.V2.Core.Contracts.WampConnectionBrokenException: Connection got broken. CloseType:Disconnection
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.Wait()
   в Descent.Game.BeginLobby() в C:\Users\urusai\RiderProjects\descent\descent\Game.cs:строка 88
   в Frontend.ConsoleFrontend.Begin() в C:\Users\urusai\RiderProjects\descent\Frontend\ConsoleFrontend.cs:строка 36
   в Frontend.Program.Main(String[] args) в C:\Users\urusai\RiderProjects\descent\Frontend\Program.cs:строка 19
```
i am also change the serialization options while build router:
```csharp
new DefaultWampAuthenticationHost(
    "ws://127.0.0.1:8001/",
    new WampSessionAuthenticatorFactory(),
    new List<IWampBinding>
    {
        new JTokenJsonBinding(jsonSerializer)
    }
);
```

**Comment by darkl** [comment]
Hi,

Please read this (
http://skrift.io/articles/archive/bulletproof-interface-deserialization-in-jsonnet/)
for a discussion of interface serialization/deserialization using JSON.net.

Try following one of the best practices suggested in this blog post.

I will try to troubleshoot a sample that you said that fails later this
week.

**Comment by darkl** [comment]
[Here](https://gist.github.com/darkl/138659f49c0b83e973fc43d5d8dcd0a7) is a complete example for what you are trying to achieve.

You might want to decode the Animal type in a more minimal way which is less CLR-specific (although this naturally makes your service more coupled, and less cross-platform).

Elad
