### ISSUE TITLE
Castle.Core versioning problem

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#228]
Hello Elad,
I've had the need to update some dependencies and I'm having an issue with Castle.Core - the version referenced by WampSharp has an assembly version of 4.1.1.0, and it looks like they changed the assembly version to 4.0.0.0 in the latest 4.2.1 (or likely 4.2.0) nuget package.  That results in the need to do the following:

`<bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.0.0.0" />`

Which I don't really want to do.  Could you please update WampSharp to use 4.2.1, which is apparently their go-forward versioning strategy?  Moq and others have also released versions to coincide with their change.  Reference this (and other) discussions: [#288 Castle.Core](https://github.com/castleproject/Core/issues/288)

Thanks, as always!

**Comment by darkl** [comment]
Done (v1.2.7.47-beta).

Elad
