### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by dandcg** [Code-Sharp/WampSharp#229]
Hi,

What the recommended way to use InMemoryTransport for use in integration tests?

For clarity (and not recommended as you suggest) but should I be able to implement both a publisher and subscriber at router level? Is there a way of opening an in memory channel against the router directly? 

I have looked through the source tests and came across WampPlayground but still a bit opaque as I'm sure this is for internal testing.

Dan

**Comment by darkl** [comment]
Dear Daniel,

You can do something like [this](https://gist.github.com/darkl/c87c33e2fe40c5103c353355aed3b7a8).

Elad
