### ISSUE TITLE
Connection refused Xamarin

### ISSUE THREAD

**Issue by yohsk10** [Code-Sharp/WampSharp#231]
Hi all,

I try to connect with a Xamarin.Forms application to a remote Publisher. For this I used the sample in GitHub and make some modification to it. Here is the code :

`
const string serverAddress = "ws://0.0.0.0:8080/ws";

            WampHost host = new DefaultWampHost(serverAddress);

            var Realm = host.RealmContainer.GetRealmByName("realm1");

            IDisposable disposable = 
                Realm.HostMetaApiService();

            host.Open();

            Realm.TopicContainer.CreateTopicByUri("com.myapp.topic1", true);

            Realm.SessionCreated += Realm_SessionCreated;
            Realm.SessionClosed += Realm_SessionClosed;

            int counter = 0;

            IObservable<long> timer =
                Observable.Timer(TimeSpan.FromMilliseconds(0),
                    TimeSpan.FromMilliseconds(1000));

            IDisposable disposableSubscription =
                timer.Subscribe(x =>
                {
                    counter++;
                    Console.WriteLine("Publishing to topic 'com.myapp.topic1': " + counter);
                    Realm.Services.GetSubject<int>("com.myapp.topic1").OnNext(counter);
                });

            Console.ReadLine();

            disposable.Dispose();

            Console.ReadLine();
`

Now I create a Xamarin.Forms application (with iOS and Android) with a .NetStandard 2.0 class library who contains my common code. I try to connect to my remote Publisher but I have a WebSocketException who said me :

"System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Sockets.SocketException (0x80004005): Connection refused".

The code used for the connection is :

`
DefaultWampChannelFactory channelFactory =
                    new DefaultWampChannelFactory();

            IWampChannel wampChannel =
                channelFactory.CreateJsonChannel("ws://localhost:8080/ws", "realm1");

            Func<Task> connect = async () =>
            {
                try
                {
                    await wampChannel.Open().ConfigureAwait(false);

                    ISubject<int> subject = wampChannel.RealmProxy.Services.GetSubject<int>("com.myapp.topic1");

                    IDisposable disposable = subject.Subscribe(GetValue,
                        ex => { Console.WriteLine($"{ex}"); });
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            };

            var reconnector = new WampChannelReconnector(wampChannel, connect);
            reconnector.Start();
`

I have set the AndroidManifest to permit the INTERNET connection. Do you have some idea to fix the problem ? I used the "WampSharp.Default.Client" library into the common library with version 1.2.7.47-beta.

Thanks in advance !
Yohsk

**Comment by darkl** [comment]
Can you try to connect to a different server? For instance to wss://demo.crossbar.io/ws, realm crossbardemo?

Elad

**Comment by yohsk10** [comment]
I try to connect to the `wss://demo.crossbar.io/ws` server and I can do it. But only when I use the synchronous connection : `wampChannel.Open().Wait(5000);`

**Comment by darkl** [comment]
Do you get the same exception in this case?

Elad

**Comment by yohsk10** [comment]
Ah yes excuse me, I do not have any exception. It hangs on this line `await wampChannel.Open().ConfigureAwait(false);`. Only when I do the synchronous connection it works.

Probably, in my test project with Xamarin, I have something that block the connection but I do not know what. The only difference is that in the publisher program I create a WampHost on the `ws://0.0.0.0:8080/ws` address and I am in local on my computer.

Yohsk

**Comment by darkl** [comment]
Are you using ConfigureAwait(false)?

**Comment by yohsk10** [comment]
Yes `await wampChannel.Open().ConfigureAwait(false);` . It remains blocked on it, it does not go further

**Comment by darkl** [comment]
Can you upload the entire code and the cspro?

**Comment by yohsk10** [comment]
Here is my Xamarin.Forms project :

[TestXamarinWamp.zip](https://github.com/Code-Sharp/WampSharp/files/1643023/TestXamarinWamp.zip)

**Comment by darkl** [comment]
Using your sample in a UWP application works just fine.
![image](https://user-images.githubusercontent.com/1126390/35107460-fc23b3f8-fc3e-11e7-933b-d169fe3614ce.png)

**Comment by yohsk10** [comment]
Yes with a Windows application if works just fine. But with the Android emulator I have this issue. Perhaps the problem is the emulator, I will check that and let you know.
Thank you.

Yohsk

**Comment by yohsk10** [comment]
I try to open the connection with a console application and the same code. It throw me an error :

`
   à System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   à System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   à System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   à SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)

   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   à XamarinWamp.WampConnection.<>c__DisplayClass4_0.<<CreateConnection>b__0>d.MoveNext()
` 

I do not know if it can help you

**Comment by yohsk10** [comment]
Sorry, I found the "problem"... The Android emulator has is own IP address, so when you connect on the "127.0.0.1" address it will search the publisher program on the localhost of the emulator and not of the computer.
I change the connection IP with my PC's address and it works.
Sorry for wasting your time, it was my mistake.

Yohsk

**Comment by darkl** [comment]
Glad you found it. Can you please help @kitkat14 with #230?

Thanks
Elad
