### ISSUE TITLE
Filter events on a topic

### ISSUE THREAD

**Issue by ygoe** [Code-Sharp/WampSharp#235]
How can I add an event filter to the router? I'm looking for a solution to intercept, manipulate and drop event objects as they arrive in the router and before they're sent to subscribers. I'd also need to know the sender of the event to decide what to do with the data. This filter must process events for each topic in-order, so that I can alter or insert events without reordering them.

Is that possible with WampSharp? If not, how could I add that feature? It is a required feature of my software and I'm currently evaluating whether WAMP can be used for it. Until now it looks very good.

**Comment by Jopie64** [comment]
I think I can answer this one.
This is not a WampSharp specific question but one that has to do with the architecture of Wamp itself.
It is not possible to filter data the way you suggest, by acting as a middleman between the sender and the router.
What you can do however is create a Wamp node that subscribes on the unfiltered topics, and resubmits  (republish) the events on filtered topics (with different URI's).
You can do this with WampSharp or with any other Wamp client.

**Comment by darkl** [comment]
It is possible to do such thing.
The WampHost constructors accept a IWampRealmContainer object. You can provide your own implementation for this interface (wrapping WampSharp's WampRealmContainer class) and override GetRealmByName, such that it returns a wrapped IWampRealm. In IWampRealm, you can override the implementation of IWampTopicContainer, such that it wraps WampSharp's WampTopicContainer. This allows you to intercept Publish messages received by the router and do with them as you wish.

Elad

**Comment by ygoe** [comment]
Thank you! This has led to rather long code, essentially just passing through calls to a wrapped object. (115 loc, and the two events from `IWampTopicContainer` aren't even connected yet.) But it does work as I need it. At least with the simple `int` messages from the samples. I'll clean this up a little and see what it does when I'll send more complex objects through the system.

One question: What am I supposed to return from the `Publish` method? It's not documented in the XML documentation and I can't find the relevant source line here on GitHub to see what it usually does. Is it the number of published elements? So would I just return 0 when I discard an item? Or a greater number when I add an additional item?

**Comment by darkl** [comment]
Yeah, this isn't something that WAMP is actually designed for. This is one
of the reasons why this is not user-friendly nor documented.

You are supposed to return the publicationId. You should actually call the
Publish method of the wrapped IWampTopicContainer and let it generate a
publicationId for you.

**Comment by darkl** [comment]
You can actually return any number from this method, as the framework
currently appears not to make any use of the result. The result is actually
for framework users, who call the WampTopicContainer.Publish themselves.

Elad

**Comment by ygoe** [comment]
Hm, ok, so I just return whatever I get from the original method when I call it, and return 0 if I don't call it. If I call it more than once to insert additional items, then I'll just drop the return value from that.

I'm going to take a look at identifying the sender when I have one and also use authentication. I'm currently just publishing items right from the router process, an ASP.NET Core application. But that won't be the normal case in my application, it's just for experimenting and getting things to work.

**Comment by darkl** [comment]
Sorry about the previous reply, it was wrong. The framework does use the publicationId value returned from the publish method. It is sent in a PUBLISHED method to a client which request Acknowledge=true.

Elad
