### ISSUE TITLE
Can I configure WampSharp.V2 to use a http proxy?

### ISSUE THREAD

**Issue by HlebLuckyBoy** [Code-Sharp/WampSharp#239]
I have web socket client implementation that needs to go throw a http proxy, can I configure WampSharp.V2 to use a http proxy?

Thanks for attention.

**Comment by darkl** [comment]
Make sure you are using WebSocket4Net. Here is a sample code for this. You need to initialize httpConnectProxy with your proxy settings (see also WebSocket4Net documentation).

```csharp
WampChannelFactory factory = new WampChannelFactory();

// TODO: initialize HttpConnectProxy
HttpConnectProxy httpConnectProxy = null;

IWampChannel channel =
    factory.ConnectToRealm("realm1")
        .WebSocketTransport(subProtocol =>
            new WebSocket("ws://127.0.0.1:8080/ws", subProtocol) {Proxy = httpConnectProxy})
        .JsonSerialization()
        .Build();
```

Elad

**Comment by HlebLuckyBoy** [comment]
Thank you.
