### ISSUE TITLE
Why WebSocket Version 8 instead of 13?

### ISSUE THREAD

**Issue by konsultaner** [Code-Sharp/WampSharp#240]
I tried WampSharp with my latest release of [connectanum](https://www.connectanum.com/). I saw that [netty](https://netty.io/) used The WebSocket Protocol Version 8 instead of 13. Do you actually use WebSockets in Version 8 or may that be a Netty issue?

**Comment by darkl** [comment]
It is possible to change this. The default value is WebSocketVersion.Rfc6455, which seems to be the RFC version. If you really want, you can change the WebSocketVersion value as following (although I'd recommend you to figure out why Netty defaults to DraftHybi10 and not to Rfc6455).

```csharp
WampChannelFactory factory = new WampChannelFactory();

IWampChannel channel =
    factory.ConnectToRealm("realm1")
        .WebSocketTransport(subProtocol =>
            new WebSocket("ws://127.0.0.1:8080/ws", subProtocol, version:WebSocketVersion.DraftHybi10))
        .JsonSerialization()
        .Build();
```

Elad

**Comment by konsultaner** [comment]
@darkl I'm not quite sure who causes the error. I opened an [issue in netty](https://github.com/netty/netty/issues/7767)

**Comment by konsultaner** [comment]
Its a logging issue from netty
