### ISSUE TITLE
In-Memory transport

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#250]
Hi Elad,
is there a way to use client - router transport that works in-memory and does not use any serialization? On many of our applications we have the router and most clients on one machine so, in order to speed things up, we decided to use Microsoft's MEF to dynamically compose an application from clients and optionally a router. In order to fully leverage this solution we would need to be able to somehow establish a channel that is in-memory (like some sort of Queue or something similar).
I noticed InMemoryTransport in WampSharp's code but I can't find a way to use it.
Any advice would be much appreciated.

Thanks
Esso

**Comment by esso23** [comment]
Thanks a lot, that was very helpful.

**Comment by esso23** [comment]
HI Elad,
I finally found the time to start working on this and implemented something based on your example (simple publish/subscribe) and it's always failing with WampSessionNotEstablishedException.

I thought I'm doing something wrong so I copy-pasted your example (only removed async Main cuz my compiler does not like that) and the exception is still there:

![sadface](https://user-images.githubusercontent.com/5548662/41629850-134ac624-742c-11e8-9157-a93cddad2524.PNG)

Complete code: https://pastebin.com/61kSsXzH

Using WampSharp 18.6.1 & .NET Framework 4.6.1

**Comment by darkl** [comment]
This [variant](https://gist.github.com/darkl/818088f00e7397b4cceffadb85f8679b) works, I don't have time now to understand why.

Elad

**Comment by Jopie64** [comment]
Isn't that simply because you don't await the Open() call?
If your compiler doesn't like async Main(), you can create a new async function that is called by main like this:

.... static void Main ()
{
  AsyncMain().Wait();
}

static async Task AsyncMain()
{
  ...
}

**Comment by esso23** [comment]
Yeah, I guess I should have gone to bed rather than coding at 2AM... Thanks guys and sorry to waste your time. 
For reference, here's the working example without using async.
https://pastebin.com/RMuPFNDN
