### ISSUE TITLE
WampSharp.Default.Router & .NET Standard 2.0

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#251]
This package does not work in .NET Standard 2.0 projects, apparently because Fleck does not support it.

**Comment by darkl** [comment]
Will address this in the next few weeks. Fleck does support .NET Standard 2.0 now.

Elad

**Comment by quynh-ng** [comment]
Fleck is supports for .NET Standard 2.0, but still got error while running on Linux and Mac, because the "Socket.IOControl" method (used by the SetKeepAlive method of SocketWrapper class) is only available on Windows platform

**Comment by darkl** [comment]
>
> Please open an issue for Fleck with a simple sample code.


Thanks
Elad

**Comment by quynh-ng** [comment]
A pull request was created, but the CI got some errors and they don't take a look...

If you want a single component for working with WebSocket (both server and client role) on .NET Standard 2, just create an empty project and tell me, I'll port my little code with minimum dependencies for you (https://github.com/vieapps/Components.WebSockets)

**Comment by darkl** [comment]
Please modify your pull request a bit so the build won't fail, and they'll merge it, as discussed [here](https://github.com/statianzo/Fleck/pull/232).

Thanks!
Elad

**Comment by quynh-ng** [comment]
Thanks for your information.
Some test methods were modified and now the build is pass.

**Comment by darkl** [comment]
[Done!](https://www.nuget.org/packages/WampSharp.Default.Router)
