### ISSUE TITLE
RawSocket

### ISSUE THREAD

**Issue by map12** [Code-Sharp/WampSharp#254]
Trying to connect to a rawsocket channel a System.Security.VerificationException raises coming from MsgPack.MessagePackStreamPacker.EncodeString. 
Last Version WampSharp 18.6.1
and
MsgPack.Cli 1.0.0

**Comment by darkl** [comment]
Can you please explain how to reproduce this issue?

Thanks
Elad

**Comment by darkl** [comment]
>
> What operating system are you using? Are you using .NET Core or .NET
> Framework?


Elad

**Comment by map12** [comment]
.NET framework 4.7.1

**Comment by map12** [comment]
Extraction from my code is complicated; I reduced accompanying package MsgPack.Cli to version 0.6.2 then I receive no verification error now. Thank you for support.

**Comment by darkl** [comment]
I'll release in the near future a version that targets the latest version
of Msgpack.Cli.

Elad

**Comment by darkl** [comment]
WampSharp v19.8.2 is now available and targets the latest MsgPack.Cli version.

Elad
