### ISSUE TITLE
Duplicate session ID generation

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#263]
Hi Elad,
when I connect in-memory client to a router (using auth) and then I connect websocket client, often the websocket client gets a duplicate session ID. It also happens when I connect WS client first and in-memory client second.
But if I use **only** WS clients, or **only** in-memory clients, it never happens.

Repro here:
https://gist.github.com/esso23/f04702909ac40799075b5221b406b009

Notice that if you call `CreateInMemoryClient()` multple times, `CreateWebSocketClient()` always gets session ID of the first in-memory client created.
Also it does not happen reliably in this repro (although it **always** happens in my solution).

Thanks
Esso

**Comment by darkl** [comment]
Different bindings now share the same Id generator instance. Should be fixed in v18.8.2.

**Comment by esso23** [comment]
Tried it just now, all good.
Thanks a lot for the fix.
