### ISSUE TITLE
Is it possible to set timeout for a connection attempt?

### ISSUE THREAD

**Issue by jaimewyant** [Code-Sharp/WampSharp#264]
When using WampSharp on Android, connection failures take quite some time.  For instance, if I don't start my crossbar router, and attempt to connect with WampSharp, on android the connection takes a while to fail.

I was wondering is there a way to specify a timeout for a connection attempt?  From what I've read channel.Open does not take any parameters.

**Comment by darkl** [comment]
This isn't supported by WampSharp currently. I don't plan supporting
timeout functionality in the near future. You can use something like `await
Task.WhenAny(Task.Delay(5000), openTask)` as a workaround.

**Comment by jaimewyant** [comment]
This works well, thanks.
