### ISSUE TITLE
Memory leak when unregistering a callee service

### ISSUE THREAD

**Issue by Brushedoctopus** [Code-Sharp/WampSharp#272]
After disposing the result of `IWampRealmServiceProvider.RegisterCallee`, the registered service should no longer be referenced.

`WampCallee` holds onto the registered service in `mRegistrations`. The `TryRemove` _is_ being run in `Registered` but isn't actually removing anything since the `requestId` is used to remove entries that were added using a `registrationId`.

**Comment by darkl** [comment]
Should be resolved in 18.9.2.

Elad
