### ISSUE TITLE
Client web socket closed twice on goodbye message

### ISSUE THREAD

**Issue by mbett7** [Code-Sharp/WampSharp#274]
When calling `Close(string, GoodByeReason)` I noticed WampSharp was logging this error
```
A connection error occured
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```

After debugging it appeared that the WebSocket4Net websocket was being closed twice.  Once as expected, then again when responding to the close event raised by the websocket.

![image](https://user-images.githubusercontent.com/32408685/46644634-76aedd00-cbc4-11e8-8527-ad8279d06cae.png)

**Comment by darkl** [comment]
Can you try 18.10.1.0-develop from develop (will be available in about 15 minutes) and tell me if it works better?

**Comment by mbett7** [comment]
Not quite.

`WampSessionClient` relies on the close event being fired to complete the close task.  Without it `IWampChannel.Close(string, GoodbyeDetails)` never completes.

Also I'm guessing that `WebSocket.Dispose()` will abort open websockets leading to an error being logged on the router side.

**Comment by darkl** [comment]
Please try 18.10.1.1-develop whenever it becomes available.

Elad

**Comment by mbett7** [comment]
That did the trick.
Thanks
