### ISSUE TITLE
Unable to connect to wss using wamp2 Fluent syntax

### ISSUE THREAD

**Issue by ganeshw27** [Code-Sharp/WampSharp#284]

**Comment by ganeshw27** [comment]
Below is my C# code
I am trying to implement wss in my application but before that, I am just trying to create the demo for crossbar example https://demo.crossbar.io/votes/index.html

```
            var factory = new WampChannelFactory();

            IWampChannel channel = factory
                .ConnectToRealm("ws")
                .WebSocketTransport(name => new WebSocket("wss://demo.crossbar.io/ws", "wamp.2.msgpack")) // WebSocket4Net

                .SetSecurityOptions(o =>
                {
                    o.EnabledSslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
                    o.AllowNameMismatchCertificate = true;
                    o.AllowUnstrustedCertificate = true;
                })
                .MsgpackSerialization()
                .Build();

            ServicePointManager.ServerCertificateValidationCallback = (s, crt, chain, policy) => true;

            Console.WriteLine(channel.RealmProxy.Name);
            IWampClientConnectionMonitor wampChannelMonitor = channel.RealmProxy.Monitor;
            Console.WriteLine(wampChannelMonitor.IsConnected);
            wampChannelMonitor.ConnectionEstablished += OnConnectionEstablised;

            channel.Open();
            Console.WriteLine(wampChannelMonitor.IsConnected);
```

But it is not able to connect to the crossbar. There is no error or exception and code executes and runs successfully and terminates after last line.

**Comment by esso23** [comment]
Use NLog or some other logging library to see errors in the log.
Also the realm name is "realm1", not "ws" (see https://crossbar.io/docs/Try-out-without-Installation/)
Anyway, I'm getting this error:

```
2019-01-08 16:19:56.7084|ERROR|WampSharp.WebSocket4Net.WebSocket4NetTextConnection`1[Newtonsoft.Json.Linq.JToken]|A connection error occured|EXCEPTION OCCURRED:System.Exception unknown server protocol version
2019-01-08 16:19:56.7582|ERROR|WampSharp.WebSocket4Net.WebSocket4NetTextConnection`1[Newtonsoft.Json.Linq.JToken]|A connection error occured|EXCEPTION OCCURRED:System.Net.Sockets.SocketException A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
```

**Comment by darkl** [comment]
Console applications have the nature that they terminate after the Main
method is done. You should try to make the program not terminate, for
instance by adding a Console.ReadLine call.

Elad

**Comment by darkl** [comment]
Here is a modified code that works using WampSharp.WebSockets instead of WampSharp.WebSocket4Net

```csharp
var factory = new WampChannelFactory();

IWampChannel channel = factory
                       .ConnectToRealm("crossbardemo")
                       .WebSocketTransport(new Uri("wss://demo.crossbar.io/ws"))
                       .MsgpackSerialization()
                       .Build();

Console.WriteLine(channel.RealmProxy.Name);
IWampClientConnectionMonitor wampChannelMonitor = channel.RealmProxy.Monitor;
Console.WriteLine(wampChannelMonitor.IsConnected);
wampChannelMonitor.ConnectionEstablished += OnConnectionEstablised;

await channel.Open();
Console.WriteLine(wampChannelMonitor.IsConnected);
```

I don't know why the WebSocket4Net code throws an exception regarding the protocol. Don't have time to investigate this.

**Comment by darkl** [comment]
Debugged WebSocket4Net. Apparently crossbar doesn't like the default origin provided by WebSocket4Net. You need to specify the origin yourself.

```csharp
var factory = new WampChannelFactory();

IWampChannel channel = factory
                       .ConnectToRealm("crossbardemo")
                       .WebSocketTransport(name => new WebSocket("wss://demo.crossbar.io/ws", subProtocol:name, origin: "https:/
                       .MsgpackSerialization()
                       .Build();

Console.WriteLine(channel.RealmProxy.Name);
IWampClientConnectionMonitor wampChannelMonitor = channel.RealmProxy.Monitor;
Console.WriteLine(wampChannelMonitor.IsConnected);
wampChannelMonitor.ConnectionEstablished += OnConnectionEstablised;

await channel.Open();
Console.WriteLine(wampChannelMonitor.IsConnected);
```

**Comment by ganeshw27** [comment]
Dear Darkl,

Thank you very much for your guidance. The above code was giving an exception saying “A call to SSPI failed, see inner exception”, basically the authentication error. So I added the lines to set certificate options and now it's working fine.

`var factory = new WampChannelFactory();

IWampChannel channel = factory
                       .ConnectToRealm("crossbardemo")
                       .WebSocketTransport(name => new WebSocket("wss://demo.crossbar.io/ws", subProtocol:name, origin: "https://demo.crossbar.io/"))
                       .SetSecurityOptions(o=>{
                                           o.EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls | SslProtocols.Ssl3 | SslProtocols.Ssl2;
                                           o.AllowCertificateChainErrors = true;
                                           o.AllowNameMismatchCertificate = true;
                                           o.AllowUnstrustedCertificate = true;
                                       })
                       .MsgpackSerialization()
                       .Build();

ServicePointManager.ServerCertificateValidationCallback = (s, crt, chain, policy) => true;
Console.WriteLine(channel.RealmProxy.Name);
IWampClientConnectionMonitor wampChannelMonitor = channel.RealmProxy.Monitor;
Console.WriteLine(wampChannelMonitor.IsConnected);
wampChannelMonitor.ConnectionEstablished += OnConnectionEstablised;

await channel.Open();
Console.WriteLine(wampChannelMonitor.IsConnected);`

Thank you very much once again!
