### ISSUE TITLE
Show Http Client Example

### ISSUE THREAD

**Issue by hawkerm** [Code-Sharp/WampSharp#287]
**Describe the bug**
https://wampsharp.net/wamp2/router/transports/websocket/#wampsharp-httplistener

Shows how to setup the http transport on the Server, but it doesn't show the corresponding client code.  If other client examples are used, get an invalid transport exception.

**To Reproduce**
Use any client example and change the transport to the HttpListener shown in the above docs.

**Expected behavior**
Show example of how to configure a client to connect to an http transport.

**.NET platform variant**
.NET Core 2.2 on Windows 10 1803

**Comment by darkl** [comment]
This [example](https://gist.github.com/darkl/ff9cc15b0d51e96c8538f2ad1c9f56bb) works just fine on .NET Framework 4.5. Please note the WampSharp.HttpListener is [only available](https://www.nuget.org/packages/WampSharp.HttpListener) for .NET Framework 4.5 and .NET Framework 4.6.

Elad

**Comment by hawkerm** [comment]
Thanks @darkl, I was trying to use "http" on the client as well for the protocol, so I was confused.  I'm having trouble using a non-local address to connect a client to the server, so I was hoping http would be the solution.

**Comment by darkl** [comment]
WampSharp only supports the WebSocket and RawSocket transports of the WAMP protocol. WampSharp.HttpListener is just an implementation of the WebSocket transport using .NET Framework's HttpListener's class. WampSharp does not support (and will not support) the long polling http implementation.

Elad

**Comment by hawkerm** [comment]
Thanks @darkl, to clarify, to support connecting a C# client to a C# server on another machine, would I need to use the RawSocket instead of the WebSocket or is this just not possible since there's no http long poll?

**Comment by darkl** [comment]
You could use either the WebSocket transport or the RawSocket transport. WampSharp is not limited to processes running on the same machine.

Elad

**Comment by hawkerm** [comment]
Alright, that's good to know, I'll have to double-check my firewall maybe, as I'm getting these errors when trying to open the connection from the client:

```
Inner Exception 1:
WebSocketException: Unable to connect to the remote server

Inner Exception 2:
HttpRequestException: No connection could be made because the target machine actively refused it

Inner Exception 3:
SocketException: No connection could be made because the target machine actively refused it
```

**Comment by hawkerm** [comment]
@darkl any thoughts on why the connection is being refused?  I've tried connecting via the network ip address to both my own machine and another on the local network, also while adding the application exception to the firewall.  But they refuse to connect.

All the examples show connecting to a remote `ws://` uri, is there something I'm missing about how to connect to a remote system via IP address?  Is it not also just `ws://192.168.0.x:8080/`?  I did seem to be able to connect to `wss://demo.crossbar.io/ws`, so I'm a bit confused.  Is there some other configuration I need on the server to allow remote connections?

**Comment by darkl** [comment]
What transport are you using?

Elad

**Comment by hawkerm** [comment]
@darkl trying to use `ws` with the default channel on .NET Core 2.2 on port 8080.

Here's server setup:
```
                var location = $"ws://127.0.0.1:{port}/";
                using (IWampHost host = new DefaultWampHost(location))
                {
                    IArgumentsService instance = new ArgumentsService();
                    IWampHostedRealm realmClient = host.RealmContainer.GetRealmByName("client");

                    // Callee
                    await realmClient.Services.RegisterCallee(instance);

                    host.Open();
```

and Client:

```
            var location = $"ws://{address}:{port}/";

            // Caller
            DefaultWampChannelFactory factory = new DefaultWampChannelFactory();

            IWampChannel channel = factory.CreateMsgpackChannel(location, "client");

            channel.Open().ContinueWith((task) =>
            {
                if (task.IsCompletedSuccessfully)
                {
                    IArgumentsService proxy = channel.RealmProxy.Services.GetCalleeProxy<IArgumentsService>();

                    proxy.Ping("From Client");
                    Console.WriteLine("Client Pinged!");
                }
                else
                {
                    Console.WriteLine("Error Connecting: " + task.Exception.Message);
                }
            });
```

It works if they're both on the same box and I use localhost or 127.0.0.1.  But if I try and setup the server on another machine and use it's local IP address in the client I get a timeout:

```
{System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at WampSharp.WebSockets.WebSocketWrapperConnection`2.Connect() in D:\a\1\s\src\net45\Extensions\WampSharp.WebSockets\WebSockets\WebSocketWrapperConnection.cs:line 62}
```

If I try and use `http` in the client code instead, then it says 'http' isn't an allowed uri.

**Comment by darkl** [comment]
The problem is with 127.0.0.1 on the server side setup. Try using the
computer name explicitly.

>

**Comment by hawkerm** [comment]
Thanks @darkl, that allowed me to connect the two machines on my local network, by using the internal IP in both cases (machine name didn't seem to work).

If I'm exposing a server on my local network machine but want someone to connect a client from the internet, how could I accomplish this?  If I tried to use my public IP on the client it wouldn't go through.

**Comment by darkl** [comment]
These are questions for Fleck. But anyway try ws://0.0.0.0:8080

Elad

**Comment by hawkerm** [comment]
Thanks @darkl, I was able to test this finally after a trip and that worked. I just had to enable port forwarding on my router as well. This is going to work great!
