### ISSUE TITLE
Need help Router solution

### ISSUE THREAD

**Issue by golukas** [Code-Sharp/WampSharp#293]
I'm new to wamp. Please suggest how to implement such solution , that Router listens some API's and forwards request to specific realm Callee to execute RPC. Please give an code example of Router instance...

**Comment by darkl** [comment]
Have you tried looking at the documentation?

Elad

**Comment by golukas** [comment]
tried ;) please help am i in good direction.. my concern is whether is good solution to implement caller on API controllers to call callee proxy via router?

**Comment by darkl** [comment]
I guess that as long as you use the Task based api it should be ok.

Elad

**Comment by golukas** [comment]
When using caller approach to call a RPC from MVC Controller makes everytime new channel which isn't very good I aspect. Is it possible to inject wamp host context into a controller? how?

**Comment by darkl** [comment]
I need more context. What transport are you using?

**Comment by golukas** [comment]
API serves HTTP requests, then respecting requestor must execute specific connected realm and return response.

**Comment by darkl** [comment]
Are you using FleckTransport? AspNetCoreTransport? crossbario?

Elad

**Comment by golukas** [comment]
AspNetCoreTransport

**Comment by darkl** [comment]
If you're using AspNetCoreWebSocketTransport, you can simply use ASP.NET
Core dependency injection in order to inject the WampHost or the hosted
realm to the controller.

Elad

**Comment by golukas** [comment]
Thanks for help Elad!
