### ISSUE TITLE
Reconnect questions

### ISSUE THREAD

**Issue by golukas** [Code-Sharp/WampSharp#294]
Testing reconect function on RPC pattern. Callee service has reconnecting implemented using [example ](https://gist.github.com/darkl/28380eced333ac8ff0fcc4df6cb2f21e). Couple of questions:

1. default websocket ping is 1minute - can I change ping time to some smaller interval?
2. when swopping to another Wifi on Callee mashine, it recconects, but seems that it isn't creating new ws channel (used Fiddler to track) and it's unable to make calls from Server. Is it known issue and how to solve it?

**Comment by darkl** [comment]
You can configure the ping interval using for instance fluent syntax api:
```csharp
factory.ConnectToRealm("MyRealm")
.WebSocketTransport(subprotocolName => new WebSocket("ws://127.0.0.1:8080/ws",subprotocolName)
{
    AutoSendPingInterval = 30
})
.JsonSerialization()
.Build();
```

Can't say anything smart about the second issue.

**Comment by golukas** [comment]
Please clarify, my factory instance hasn't got _ConnectToRealm_ function:

Callee channel:
```csharp
DefaultWampChannelFactory channelFactory = new DefaultWampChannelFactory();
IWampChannel channel = channelFactory.CreateJsonChannel(_SERVER_ADDRESS, clientId);
```
Server side:
```csharp
DefaultWampHost host = new DefaultWampHost(_SERVER_ADDRESS);
host.Open();
```

**Comment by golukas** [comment]
Regarding 2nd issue:

Still investigating. But seems when you unplug network from Callee mashine Server doesn't get disconnect message so Callee channel remains open from Server perspective. Then Callee reconnects (shows success), but on Server side it doesn't instantiate new realm proxy as old one still open or something like that. 

Similar happens when you connect two Callees with the same realm name - both are connected from Callees perspective but Server is able to send message only to first one.

**Comment by darkl** [comment]
You need to add a `using WampSharp.V2.Fluent;` directive for the fluent syntax.

**Comment by golukas** [comment]
still something is wrong, got error "Cannot convert lambda expression to type 'Uri' because it is not a delegate type". WebSocketTransport expects Uri or WebSocketFactory + Uri, which isn't correct as in your example. please clarify...

**Comment by golukas** [comment]
Thanks. This works perfectly

**Comment by golukas** [comment]
one more question - is it possible to track all connections of new clients from host side? Goal is to have monitor how many realms are connected and have some control over it, e.g. log connections or send some data to all realms..

**Comment by darkl** [comment]
You can use a realm's `SessionCreated/SessionClosed` event handlers.

Elad
