### ISSUE TITLE
ASP.NET Core reverse proxy

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#295]
Hello,
Is there a way how to create a reverse proxy from ASP.NET Core to some backend WampSharp router? My web is running on https://www.somepage.sk and currently I have a router on wss://www.somepage.sk:50000, but what I want is to have a router on wss://www.somepage.sk/ws (part of ASP.NET Core) 443 port as the web.
I want my backend router to remain hidden and use WS and ASP.NET Core reverse proxy to use WSS on the outside.
Is this even possible? Are there any libraries to implement this? Or am I going in the wrong direction?

Thanks a lot for any help
Esso

**Comment by darkl** [comment]
You can try an approach like the one discussed [here](https://github.com/Code-Sharp/WampSharp/issues/88).

Elad

**Comment by quynh-ng** [comment]
Hi,

I was tried with your code (from old gist code - 2015), but the class ForwardingRpcCatalog is not implements all members of IWampRpcOperationCatalog.

**Comment by esso23** [comment]
Hi,

here is my updated implementation:
https://gist.github.com/esso23/e66b19283836e8dea4b9303c05830a09
It does not support registration and publishing, it only forwards requests to some other router.
