### ISSUE TITLE
AspNetCoreWebSocketTransport

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#297]
Hi,
AspNetCoreWebSocketTransport is not working for me.

I tried configuring it based on these issues.
https://github.com/Code-Sharp/WampSharp/issues/179
https://github.com/Code-Sharp/WampSharp/issues/216

Here is my configure method:
```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            mHost =
                new WampHost
                (
                    new ForwardingRealmContainer("ws://10.8.0.250:50000/ws",
                        new TicketAuthenticator("Backend", "648g684g4864==[")),
                    new LooseUriValidator());

            app.Map("/ws", builder =>
            {
                builder.UseWebSockets();

                mAspNetCoreWebSocketTransport = new AspNetCoreWebSocketTransport(builder);

                mHost.RegisterTransport(mAspNetCoreWebSocketTransport,
                    new JTokenJsonBinding(),
                    new JTokenMsgpackBinding());
            });

            app.UseHttpsRedirection();
            app.UseAuthentication();

            app.UseMiddleware<AuthMiddleware>();

            app.UseStaticFiles();
            app.UseSpaStaticFiles();

            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
            });
        }
```

First problem I found is that the connection is never opened, Open() method is never called so it keeps using `EmptyHandler`. Do I need to open it manually, or should that be handled somewhere in WampSharp? When I force `WebSocketHandler` in the constructor, it fails here (requests are properly sent from wss://xxx.xxx/ws to this handler):
```cs
IEnumerable<string> possibleSubProtocols =
                    context.WebSockets.WebSocketRequestedProtocols
                           .Intersect(this.SubProtocols);

string subprotocol =
                    possibleSubProtocols.FirstOrDefault();
```
because `this.SubProtocols` is empty.
I noticed that in RegisterTransport of WampHostBase here:
```cs
if (bindingArray.Any())
            {
                mTransportDefinitions.Add(new WampTransportDefinition()
                {
                    Transport = transport,
                    Bindings = bindingArray
                });
            }
```
the transport itself has no SubProtocols and empty mBindings after initialization.
At this point I stopped as there seems to be too many problems and I might be doing something wrong.

Any help would be appreciated
Esso

**Comment by darkl** [comment]
There are not enough details here, to debug this I need a full project that does not work. One common pitfall is to forget to call `.Run()` if you construct the Host yourself, see [this issue](https://github.com/Code-Sharp/WampSharp/issues/247).

Elad

**Comment by darkl** [comment]
I just used the example in the issue I referred to, and it works fine.
If you're using IIS, you might need to enable WebSockets.

Elad

**Comment by esso23** [comment]
Oh my god, I can't believe I spent so much time on this :D
Thanks a lot

**Comment by esso23** [comment]
Ok, I have another problem. When I test my application locally, everything works fine.
But when I deploy to IIS and host it on public domain, the request arrives, but `context.WebSockets.IsWebSocketRequest` is `false`.
![debugview](https://user-images.githubusercontent.com/5548662/56966663-e0da9f80-6b5f-11e9-9130-ff06fac5ea10.png)

**Comment by darkl** [comment]
You need to enable IIS WebSockets.

Elad

**Comment by esso23** [comment]
Thanks, leaving this here for any other IIS noobs like me :X (for Win 10):
![Screenshot 2019-04-30 16 02 26](https://user-images.githubusercontent.com/5548662/56967445-7e829e80-6b61-11e9-80df-1fad82cbc49d.png)
