### ISSUE TITLE
WampHost Dispose bug

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#304]
Hi Elad,
I have the following bug:

**Describe the bug**
WampHost dispose method does not disconnect connected clients. No new connections can be made but it countinues to route requests for already connected clients.

**To Reproduce**
https://gist.github.com/esso23/28eb4c68c62e09450d29e71e1124d564

Run the gist, press enter -> Dispose is called, and everything just continues to work.

**Expected behavior**
Dispose should disconnect all clients from the server and completely deinitialize all components of the WampHost instance.

**External WAMP libraries involved**
None.

**.NET platform variant**
.NET 4.7.2, Windows 10 Pro

**Additional context**
I'm using forwarding router (solution from this issue https://github.com/Code-Sharp/WampSharp/issues/295) which connects to 2 redundant remote routers and when the current one becomes unavailable I need to dispose of the current WampHost and then completely reinitialize everyhing. Everything works except this one thing. When I simulate it (both remote routers work, I just force it to switch) the clients remain connected to disposed WampHost and all their requests are still routed to the first client. What I want is disconnect the clients and then they automatically reconnect to restarted WampHost.

Thanks in advance,
Esso

**Comment by darkl** [comment]
This will probably require some serious work. I will try to include this in the January 2020 version.

**Comment by darkl** [comment]
Should be fixed in v20.1.1.
