### ISSUE TITLE
SetSecurityOptions on NETstandard 2.1

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#305]
Hi Elad,

I'm migrating from .NET 4.6.1 to .NET Core 3.1 and .NET Standard 2.1 and I encountered this problem:

**Error message:**

> Connection\RealmConnection.cs(41,22,41,40): error CS1061: 'IWebSocketTransportSyntax' does not contain a definition for 'SetSecurityOptions' and no accessible extension method 'SetSecurityOptions' accepting a first argument of type 'IWebSocketTransportSyntax' could be found (are you missing a using directive or an assembly reference?)

**Project:**
.NET Standard 2.1

**Packages used:**
WampSharp.Default.Client (I also tried WampSharp.Default)

**Code:**
```cs
            mChannel = factory.ConnectToRealm(realmName)
                    .WebSocketTransport(new Uri(serverAddress))
                    .SetSecurityOptions(o =>
                    {
                        o.AllowNameMismatchCertificate = true;
                        o.AllowUnstrustedCertificate = true;
                    })
                    .MsgpackSerialization()
                    .Authenticator(authenticator)
                    .Build();
```

Thanks in advance
Esso

**Comment by darkl** [comment]
Hi Esso,

You need to reference `WampSharp.WebSocket4Net` instead of `WampSharp.Default.Client`. This is one of the breaking changes (`WampSharp.WebSockets` is the default now).

**Comment by esso23** [comment]
That helped. Thanks a lot.

**Comment by bharath3719** [comment]
Hi Elad, 

Do we have to use the WampSharp.WebSocket4Net  or  WampSharp.V2.Fluent; ?

I am trying to do this :

            var factory = new WampChannelFactory();

            IWampChannel channel = factory
                                   .ConnectToRealm("realm")
                                   .WebSocketTransport(new Uri("wss://abcd127026/"))
                                   .SetSecurityOptions(o => {
                                       o.EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls | SslProtocols.Ssl3 | SslProtocols.Ssl2;
                                       o.AllowCertificateChainErrors = true;
                                       o.AllowNameMismatchCertificate = true;
                                       o.AllowUnstrustedCertificate = true;
                                   })
                                   .MsgpackSerialization()
                                   .Build();

**Comment by esso23** [comment]
@bharath3719 It's hard to understand what you're asking. Are you getting an exception? Or what exactly is the question?

**Comment by bharath3719** [comment]
@esso23  , Elad said we need to reference wampSharp.WebSocket4Net to get the above code running. But it's not working. VS IntelliSense suggesting using WampSharp.V2.Fluent .  So wanted to make sure which lib to refer ..

**Comment by darkl** [comment]
You do need to add a using directive `using WampSharp.V2.Fluent` for the fluent syntax.

**Comment by bharath3719** [comment]
And do we need to use  WampSharp.V2.Client; or WampSharp.WebSocket4Net ?

**Comment by darkl** [comment]
Here's a complete program with the code you mentioned:

```csharp
using System.Security.Authentication;
using WampSharp.V2;
using WampSharp.V2.Client;
using WampSharp.V2.Fluent;

namespace Example
{
    public class Program
    {
        static void Main(string[] arguments)
        {
            WampChannelFactory channelFactory = new WampChannelFactory();

            var factory = new WampChannelFactory();

            IWampChannel channel = factory
                                   .ConnectToRealm("realm")
                                   .WebSocket4NetTransport("wss://abcd127026/")
                                   .SetSecurityOptions(o =>
                                                       {
                                                           o.EnabledSslProtocols =
                                                               SslProtocols.Tls12 | SslProtocols.Tls11 |
                                                               SslProtocols.Tls | SslProtocols.Ssl3 | SslProtocols.Ssl2;
                                                           o.AllowCertificateChainErrors = true;
                                                           o.AllowNameMismatchCertificate = true;
                                                           o.AllowUnstrustedCertificate = true;
                                                       })
                                   .MsgpackSerialization()
                                   .Build();
        }
    }
}
```

NuGet packages referenced: `WampSharp.WebSocket4Net`, `WampSharp.Msgpack`.

I won't do this again, your IDE should help you suggest which using directives to use other than `WampSharp.V2.Fluent` (that's how I produced this code).

**Comment by bharath3719** [comment]
@darkl  , Yes this is the code i had .. But in earlier comments u mentioned :

 ' You need to reference WampSharp.WebSocket4Net instead of WampSharp.Default.Client '

Hence the confusion...
