### ISSUE TITLE
Publisher channel connects to host with DefaultWampAuthenticationHost but not WampAuthenticationHost.

### ISSUE THREAD

**Issue by bharath3719** [Code-Sharp/WampSharp#312]
DefaultWampAuthenticationHost is hosted as an .net core service in IIS.

When we are trying to publish from another application , if we have used DefaultWampAuthenticationHost , the channel gets opened and connected.

If we have used WampAuthenticationHost , then I get this error while opening channel -

The remote certificate is invalid according to the validation procedure.

Q : Where is this 'validation procedure' occurring ? I don't see debugger hitting the service.
How can i resolve this issue ?
Can i provide a certificate to the channel ? Any leads on the same ?

Edit :

I am doing the below 
{
             IWampChannel channel = factory.ConnectToRealm("realm")
                                .WebSocketTransport(new Uri("wss://ABCD127026/notifications"))
                                .SetClientWebSocketOptions(x =>
                                {
                                    x.RemoteCertificateValidationCallback += new 
                                                               RemoteCertificateValidationCallback(ValidateCertificate);    
                                }) .JsonSerialization() .Build();

 channel.Open().Wait();
}

        static bool ValidateCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
        {
            return true;
        }

But getting this error 

System.AggregateException: 'One or more errors occurred. (The server returned status code '503' when status code '101' was expected.)'

**Comment by darkl** [comment]
See [here](https://stackoverflow.com/questions/9983265/the-remote-certificate-is-invalid-according-to-the-validation-procedure) for details about the error.

See [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1) for information about how to use certificates in ASP.NET Core, including how to enable SSL certificates on IIS.

Elad

**Comment by darkl** [comment]
See also the code in [this issue](https://github.com/dotnet/runtime/issues/21916) as an example of how to set the SSL certificate on the client side.

**Comment by bharath3719** [comment]
Hi Elad , 

Thanks for your suggestion.

I did a couple of things and in fiddler, I am getting this below error(warning)

12:29:06:3294 HTTPSLint> Warning: ClientHello record was 508 bytes long. Some servers have problems with ClientHello's greater than 255 bytes

Might this be the issue why I am not able to connect to my Host? Can I maybe reduce the size of ClientHello somehow?
