### ISSUE TITLE
How to get topic in Realm_SessionCreated

### ISSUE THREAD

**Issue by bharath3719** [Code-Sharp/WampSharp#313]
private void  Realm_SessionCreated(dynamic sender, WampSessionCreatedEventArgs e)
        {
            _logger.LogInfo("A session is opened. ID: " + e.SessionId.ToString());

          

            SessionManager.Instance.AddSession(new SessionInfo
            {
                SessionId = e.SessionId,
                UserName = e.HelloDetails?.AuthenticationId,
               // Topic = sender.TopicContainer.Topics[2] -- How can i get this value ? I see that sender's topic collection has an array Topics , which has the required value ,but position of the array value keeps chaning. Is there any other way to acheive the same ?

            }) ;
        }

**Comment by darkl** [comment]
Your realm has a `TopicContainer` which has methods like `GetTopicByUri` etc.

**Comment by darkl** [comment]
You can also register to `TopicContainer.TopicCreated` if you want to get a notification when a new topic has been created.

**Comment by bharath3719** [comment]
I want to know which user has subscribed to which topic.

Registering to  TopicContainer.TopicCreated , i dont get sessionId in WampTopicCreatedEventArgs e to make a mapping..

**Comment by darkl** [comment]
Register to `TopicCreated` and there register to the `SubscriptionAdded`, `SubscriptionRemoved` events. Also consider using the WampMetaApi mechanism which keeps track of these for you.

Elad

**Comment by bharath3719** [comment]
Hi Elad,

In my case, i don't know the topics that my clients are going to subscribe to(it will be dynamic)

`SubscriptionAdded ` is getting called the first time when we add authorizedTopics . (Correct me if im wrong)

When client(autobahn.js) initiates a connection with router with a user specific topic ,   `SubscriptionAdded ` is not getting called.

`helloDetails `and `welcomeDetails` in `WampSessionCreatedEventArgs ` is not giving me the topic which the user has subscribed to.

And i hostedmetaAPI service like below: and there also i dont see which topic user has subscribed to

`_metaApiService = _realm.HostMetaApiService();`

![image](https://user-images.githubusercontent.com/19222968/74934805-01d0f180-540d-11ea-8839-05214987534b.png)

**Comment by darkl** [comment]
You are wrong. These events are raised whenever a new topic is created,
even if a client initiated the topic creation. You are probably not using
the correct realm name on the server side. Another possibility is that you
opened several WampHosts and you are looking at the wrong one.

The fact that the topics don't appear also in the meta-api service only
suggests that you're looking at the wrong realm or the wrong WampHost.

Elad

**Comment by darkl** [comment]
If you want to continue discussing this and want my help please provide a *standalone* repro (a single minimal cs file) that doesn't work. Respect me and my time by using the bug template for issues that I set for this repository.

Elad

**Comment by bharath3719** [comment]
i have only one realm and wampHost.  
where can i find bug template

**Comment by bharath3719** [comment]
i am getting below error if client initiates topic creation and if that topic is not there in authorizedTopics.

Potentially unhandled rejection [1] {"error":"wamp.error.not_authorized","args":[],"kwargs":{}}

**Comment by darkl** [comment]
When you open a new issue, choose the bug template.

Your current problem is that your clients are not allowed to subscribe to these topics. Implement a WampAuthorizer that allows them to subscribe by returning true from the `CanSubscribe` method. If you're using the built in `WampCraDb` implementation, maybe try using `Prefix` or `Wildcard`, I don't exactly remember the name.

**Comment by bharath3719** [comment]
looks like clients cannot subscribe to topics which are not in authorizedTopics list. Its fixed now . thanks for your inputs

**Comment by darkl** [comment]
`authorizedTopics` is not something that is defined in WampSharp, it is part of your code. Please be more careful with this in the future, I have no idea what is going on in your codebase.

Elad
