### ISSUE TITLE
Docker/Kubernetes best approach  

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#314]
Hi,
Do you think a console app will be the best choice when using Docker/Kubernetes infrastructure? 
Or willl ASP.NET app be a better choise? 
Thanks for your help
Andy

**Comment by darkl** [comment]
I can't help you, because I'm not a docker expert. You can see [an example](https://docs.docker.com/engine/examples/dotnetcore/) here ([GitHub](https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp) here). They use ASP.NET core and run their app as a Console application.

**Comment by devfxplayer** [comment]
thanks you can close it
