### ISSUE TITLE
Unobtrusive callee registration

### ISSUE THREAD

**Issue by GitEsprit** [Code-Sharp/WampSharp#315]
Add support for an unobtrusive callee registration using [namespace].[type].[methodname] for generating the procedure name.

This would enable easy addition of services/callees that are defined in external projects or packages, without having to implement and maintiain _any_ adaptor code.

**Comment by darkl** [comment]
Implement a callee registration interceptor that does that in your project.

Elad

**Comment by GitEsprit** [comment]
Thanks for the info, works just fine!
/Martin
