### ISSUE TITLE
ERR_SSL_OBSOLETE_VERSION

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#319]
WebSocket connection to 'wss://*/ws' failed: Error in connection establishment: net::ERR_SSL_OBSOLETE_VERSION

Is there a way to define the TLS 1.2?

**Comment by darkl** [comment]
What transport are you using for the router side? Fleck?

**Comment by devfxplayer** [comment]
Sorted, i added the transport:
                    var transportSec = new FleckWebSocketTransport(Address, cert, () => SslProtocols.Tls12, true);
