### ISSUE TITLE
Meta API Kill procedure raises no_such_procedure error

### ISSUE THREAD

**Issue by STL1811** [Code-Sharp/WampSharp#326]
Hello,
**Describe the bug**
Even if Meta Api Service is activated on the realm, wamp.session.kill procedures don't work. they raise no_such_procedure error.
Note that other procedures such as wamp.session.list or wamp.session.get returns expected result.

**To Reproduce**
after adding 
`IDisposable disposable = realm.HostMetaApiService();`
javascript call `wamp.session.list` on this realm using autobahn.js
the result is OK
then javascript call `wamp.session.kill` on a session_id or `call wamp.session.kill_all` or `call wamp.session.kill_by_authid`
and they raise `no_such_procedure` error

**External WAMP libraries involved**
autobahn.min.js V20.9.2

**.NET platform variant**
WAMPSharp V20.1.1
Behavior is the same on
* .NET Framework 4.6.1 on Windows 10
* .NET Core 3.1 on Windows 10

**Comment by darkl** [comment]
You need to activate Session Management Service using `realm.HostSessionManagementService()`.

Elad

**Comment by STL1811** [comment]
Thank you very much, Elad.
It's OK now.
