### ISSUE TITLE
How to handle wamp.error.procedure_already_exists when callee reconnects?

### ISSUE THREAD

**Issue by jcam7044** [Code-Sharp/WampSharp#332]
Hoping someone can advise me on how to best handle reconnections for clients connecting as callees.  The problem I am running into is when a callee client loses its connection to the router. I have logic that reconnects the client to the router but when I try to register the callee procedures again I get a wamp.error.procedure_already_exists error.  If I try to reconnect without registering again(using WampChannelReconnector) any RPC calls from a caller never finds the callee again. (I think this is because of a different session id? I'm not really sure here.) 

Is there a way I can unregister the callee from the router or have new registrations override existing registrations?

Below is connection logic. 

```
`var factory = new WampChannelFactory();
                IWampClientAuthenticator authenticator = new TicketAuthenticator(_agentId, _agentSecret);
                channel = factory
                            .ConnectToRealm(_agentId)
                            .WebSocketTransport(name => new WebSocket(_wsUrl, subProtocol: name, origin: ConvertToHttpsString(_wsUrl)))
                            .SetSecurityOptions(o =>
                            {
                                o.EnabledSslProtocols = SslProtocols.Tls12;
                                o.AllowCertificateChainErrors = false;
                                o.AllowNameMismatchCertificate = false;
                                o.AllowUnstrustedCertificate = false;
                            })
                            .JsonSerialization()
                            .Authenticator(authenticator)
                            .Build();
                ServicePointManager.ServerCertificateValidationCallback = (s, crt, chain, policy) => true;

                await channel.Open().ConfigureAwait(false);`
```

Thanks

**Comment by darkl** [comment]
You can solve this by registering with RegisterOptions having Invoke=
WampInvokePolicy.Last.

Elad

**Comment by jcam7044** [comment]
Thanks Elad.  Is done on the client or the router?

**Comment by darkl** [comment]
Wherever you register your Callee (probably client side).

Elad

**Comment by jcam7044** [comment]
Got it. Thank you so much Elad!
