### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by balauru** [Code-Sharp/WampSharp#43]
Hi,

I have web socket client implmentatin that needs to go throw a proxy, can I configure WampSharp to use a proxy? 

I found out that WebSocket4Net has support for proxy https://websocket4net.codeplex.com/discussions/351442, maybe there is a way to levrage this throw WampSharp?

**Comment by darkl** [comment]
Closed due to inactivity.

**Comment by balauru** [comment]
I've used the WebSocket instance like in your last comment and all was good, thanks.

Sorry for the late response :)
