### ISSUE TITLE
WampSharp publishing to Javascript kwargs

### ISSUE THREAD

**Issue by bradws** [Code-Sharp/WampSharp#45]
Hi,

I'm wanting to publish a topic from WampSharp to Javascript.
The javascript (autobahn.js) event is described thus:

    function onPlayerMove( args, kwargs, details ) { }

I can send data to 'args' and access my payload like args[0].DataField1, args[0].DataField2, etc
but writing args[0] is a bit ugly. 

I'm wanting to code my Javascript like: kwargs.payload.DataField1, kwargs.payload.DataField2, etc. I have got this code working sending/receiving topics to/from Javascript (autobahn.js), and I'm wanting to keep this same style of coding to access my payload from my C# peer.

Is there a way in WampSharp to publish to the 'kwargs' parameter ? I wasn't able to see any documnetation on this - can you assist?

Also as a note, might there not be some JSON serialisation involved as well ?

UPDATE: I can receive events in Wampsharp from the kwargs in javascript (autobahn.js). I just don't know how WampSharp can 'publish' data to kwargs.

Cheers,
Brad.

**Comment by darkl** [comment]
Closed due to inactivity.

**Comment by keshavkumar20** [comment]
I'm having a similar issue.
Below links doesn't seem to work.
https://github.com/Code-Sharp/WampSharp/wiki/Publisher-role
https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/basic/pubsub/complex

**Comment by darkl** [comment]
See this link (the autobahjs example is also referenced in this page)

https://github.com/Code-Sharp/WampSharp-docs/blob/master/WAMP2/Roles/Publisher/Rx-based-Publisher.md

**Comment by keshavkumar20** [comment]
Many thanks for the quick reply.
I'm using the same method.
Could the problem be due to generic type is specified in the GetSubject method?
`ISubject<dynamic> subject = realm.Services.GetSubject<dynamic>("com.myapp.topic1");`

My subject is a `string` which was generated through `JsonConvert.SerializeObject`(library from Newtonsoft.Json) method. 

Hence my code looks like this:
`ISubject<string> subject = realm.Services.GetSubject<string>("com.myapp.topic1");`.

What could be the quickest workaround?
Thank you in advance.

**Comment by darkl** [comment]
I'm not sure why you serialized your objects to strings, but you can simply de-serialize them

```csharp
var converted = subject.Select(x => JsonConvert.DeserializeObject<MyClass>(x));
```

Or
```csharp
var converted = subject.Select(x => JsonConvert.DeserializeObject<dynamic>(x));
```

But you can avoid this by not serializing objects to JSON by yourself from the beginning.

Elad

**Comment by keshavkumar20** [comment]
Right now I'm publishing MyClass but It doesn't work with kwargs. 
Do I need to use WampEvent?
MyClass is {string timestamp, array}, where array is a collection of 7 dictionaries{string, object}.

**Comment by darkl** [comment]
You in order to use that api, you need to convert MyClass to a dictionary.
Another option is to use the cool [tuples api](https://github.com/Code-Sharp/WampSharp-docs/blob/master/Release-notes/WampSharp-v1.2.5.21-beta-release-notes.md#rx-based-publishsubscribe-tuples-support).

**Comment by keshavkumar20** [comment]
Yeah, now it works!
But I'm getting another error.
`EVENT received for non-subscribed subscription ID`
