### ISSUE TITLE
Details on wiki of Auth support

### ISSUE THREAD

**Issue by delaneyj** [Code-Sharp/WampSharp#50]
Saw there are changes to the code base to support auth but nothing on the wiki.

**Comment by darkl** [comment]
Can't do it soon.
There's an example based on AutobahnPython ticket sample. Maybe @Badgerr
can help, he helped with this feature implementation.

Cheers

**Comment by darkl** [comment]
Available now in v1.2.1.6-beta [release notes](https://github.com/Code-Sharp/WampSharp/wiki/WampSharp-v1.2.1.6-beta-release-notes#authentication).
