### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by jordan-** [Code-Sharp/WampSharp#51]
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.  Using TrySetException instead of SetException fixes the issue for me.

**Comment by darkl** [comment]
Please write more details on how to restore this exception.
Sample code will be useful.

Thanks

**Comment by darkl** [comment]
Closed due to inactivity. Please reopen it with details how to reproduce this error, and what lines have been changed.
