### ISSUE TITLE
MsgPack over RawTcp

### ISSUE THREAD

**Issue by codeandroid** [Code-Sharp/WampSharp#52]
The following code snippet:

    WampHost host = new WampHost();
    host.RegisterTransport(
      new RawTcp.RawTcpTransport(8080),
      new Binding.JTokenMsgpackBinding()
    );

... fails in RawTcpTransport::GetListener() due to a cast to IWampTextBinding.

As far as I can see WampSharp.RawTcp does not support MsgPack, is that correct or am I missing something in setting up the WampHost?

Thanks for your help

**Comment by darkl** [comment]
Hi @codeandroid,

Thanks for opening this issue.

Raw Socket transport isn't officially implemented yet by WampSharp.

I've started working on it but never finished.

Do you want to work on it?

**Comment by codeandroid** [comment]
Thanks for getting back to me so quick.

For a custom remote API we need a C# WAMP client communicating with an AutobahnCpp client. The latter only supports raw tcp + msgpack, so that's where the requirement comes from.

Personally, while I have a strong C++ background my C#-fu is not en par so I'm a bit reluctant ... do you have some (hackable) code for this feature somewhere or would I need to start from scratch? It looks to me as if something like a RawTcp.RawBinaryConnection along with a RawTcpTransport.BinaryConnectionListener would be required?

**Comment by darkl** [comment]
Hi, @codeandroid 

If you want a C# client to communicate with a C++ client, that it possible using a suitable router such as Crossbar.

If you want AutobahnCpp to connect to a WampSharp router, there is some work to be done. You can try hacking my previous attempt of implementing raw socket as you suggested, it might work. I think I found some strange bugs with that implementation, maybe I wasn't using SuperSocket the right way.
Another option is to implement the raw socket completely over, using TcpListener. You can consult the Vtortola implementation - it should have similar api as the TcpListener.

https://github.com/Code-Sharp/WampSharp/tree/wampv2/src/net45/Extensions/WampSharp.Vtortola

**Comment by darkl** [comment]
Hi @codeandroid,
I pushed some work on rawsocket to the raw-socket branch. Please test it and give some feedback.

Thanks

**Comment by darkl** [comment]
Fixed in v1.2.1.6-beta. See [release notes](https://github.com/Code-Sharp/WampSharp/wiki/WampSharp-v1.2.1.6-beta-release-notes#rawsocket-transport-support).
