### ISSUE TITLE
Possible to set http headers for connection establishment?

### ISSUE THREAD

**Issue by PunditSharp** [Code-Sharp/WampSharp#53]
Hi,

Rusty dev here and a complete n00b when it comes to WAMP...is it possible to set http headers in WampSharp to be used when establishing the connection?  I have a server to connect to which requires a particular header to be sent.

Thanks in advance!

**Comment by darkl** [comment]
Hi,
Please check if this can be done using a WebSocket library such as vtortola or Fleck.
If so, it could be done with WampSharp. Some slight modifications might be needed, but it should be possible.

**Comment by PunditSharp** [comment]
Hi,

So I've been doing a little more digging into this.

The header that I actually need to set is the one that is used to specify the websocket subprotocol to be used.  Since websocket4net takes this as an input parameter I engineered a custom Channel Factory and Binding to achieve my needs.

**Comment by darkl** [comment]
Great, glad it worked for you.
