### ISSUE TITLE
Broken connection cause application crush

### ISSUE THREAD

**Issue by Shad0wSn1per** [Code-Sharp/WampSharp#58]
Application crushed when connection physically broken or wrong port will be provided for an channel connection. Catch state below is never entered. Finally block is never entered too: 
```sharp
channelFactory = new DefaultWampChannelFactory();
IWampClientAutenticator authenticator = new ClientAuthenticator(username, password);
channel = channelFactory.CreateJsonChannel( url, realm, authenticator );

try
{
          Task task = channel.Open();
          task.Wait();
}
catch ( Exception e )
{
        // The code below is never has been called. Application will be crushed.
        Console.WriteLine( e.Message );
}
finally
{
         // The code below is also has not being called
            Console.WriteLine( "Connection error!" );
}
```

**Comment by darkl** [comment]
Hi @Shad0wSn1per,

It seems you're using a old version of WampSharp (You are using the IWampClientAutenticator interface which was renamed to IWampClientAuthenticator in WampSharp v1.2.1.6).

I've tested your sample with WampSharp v1.2.1.6, and It works fine. Please update WampSharp and reopen issue if this problem still occurs.
