### ISSUE TITLE
Question about Instances when I Call a Remote Procedure...

### ISSUE THREAD

**Issue by jogibear9988** [Code-Sharp/WampSharp#74]
As I see I can only register a Callee to a Instance of a Object. Is it not possible to set a Type for a Callee, so that for every new Connection, a new instance will be created. Like in WCF where I have different instancecontext modes: Single, PerSession (means per Connection) or PerCall.

Is it possible to realize this with WampSharp?

**Comment by darkl** [comment]
Hi @jogibear9988,

There is no such thing currently in WampSharp. The most closest thing you can do is identify the client by registering with DiscloseCaller = true, and then try in your class to create an inner instance per the session id (which is accessible via WampInvocationContext.Instance), but it's kind of hard to manage this (Removing empty instances, and making sure one request occurs concurrently per client).
This kind of feature might be added to a future release, but I was wondering - can you please elaborate a bit more about your issue?

Thanks

**Comment by jogibear9988** [comment]
I have this architecture existing in my App, using WCF and a Silverlight CLient. And WCF supports such options, in WCF you can give a instance for a Callback, then this is used like in WampSharp. But when you give a Type, a Instance is created for each connection, or each Call. And also you can say if a Call's to a instance can be run in parallel or one after each other.

**Comment by jogibear9988** [comment]
If I will work on this, will this have a change to be included in the main Branch? (If it does not break anything?)

**Comment by darkl** [comment]
We need to first understand this feature entirely. [Routers are discouraged of running application code](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#application-code), so I don't want to make a router-only feature.

Please describe the feature: From my understanding you want to route calls to a specific a instance of a reflection-based callee class, per session id. When do these instances die? Should there be a limit of the number of parallel calls for a given session id?

**Comment by jogibear9988** [comment]
If I use WCF, I can say this Interface (Contract) is implemented by a given Type. Then WCF will create a Instace of the type per Connection to the Server. But I also can give a Instance instead of a type, then WCF will use the same instance for every connection to the server. And at least I can switch to a per call instanciation, then for each Method Call (RPC Call) a instance of the Type is created, not only for each connection

**Comment by darkl** [comment]
The per call feature is indeed well defined since this is defined for a
router callee client.

Will per call be enough for you?

A per session/connection feature is defined only in the router scope, since
a arbitrary callee that lives outside the router is not aware of client
connections/disconnections. (Unless metaapi is available)

**Comment by BrannonKing** [comment]
I suggest that you go with registering a Func<> instead of a type or instance. Whenever you register a type to be created on the fly you also need some way to inject parameters. Using a factory approach leaves that up to the end user, which is preferred IMHO.

**Comment by darkl** [comment]
Yeah, I thought about a Func&lt;&gt; but it is kind of ugly. Maybe this will be added as an extension method in a separate dll or so.

**Comment by darkl** [comment]
I made some work on this one on func-support branch if any of you want to try it.

**Comment by darkl** [comment]
Supported in [v1.2.5.21-beta](https://github.com/Code-Sharp/WampSharp-docs/blob/master/Release-notes/WampSharp-v1.2.5.21-beta-release-notes.md#instance-providers-for-reflection-based-callee).
