### ISSUE TITLE
Split Up WampSharp -> Reduce dependecys

### ISSUE THREAD

**Issue by jogibear9988** [Code-Sharp/WampSharp#75]
If I would work on splitting up Wamp, to reduce the Dependecys, for Example if I use TCP, I don't need Fleck. Or if I use JSON I don't need msgpack! Will a change like this have a change to go into main Branch?

I'd also like to use my nugget (https://github.com/jogibear9988/nugget) fork instead of fleck, so I don't need this dependency.

**Comment by darkl** [comment]
I'd like to discuss this,
I think it is appropriate to split the library into a couple of packages, but it costs with complexity - It makes the quick start more hard. Maybe we should separate the library, but still remain some quick-start packages, for example: WampSharp.Default package which is dependent on all packages, a WampSharp.Router.Default which is dependent on Fleck and Json and WampSharp.Client.Default which is dependent on WebSocket4Net and Json.

**Comment by darkl** [comment]
This actually happened, see develop branch and [MyGet](https://www.myget.org/feed/Packages/wampsharp) feed. Will be merged to master in upcoming version.
