### ISSUE TITLE
SessionClosed not triggered when client closes

### ISSUE THREAD

**Issue by Thad3us** [Code-Sharp/WampSharp#85]
Hey guys, WAMP newbie here.

First off, thanks for all the great work, it's very useful :)
I'm still trying to grasp all the little details of the basic examples given in the wiki and one point confuses me, about client disconnection.

When the client ends its execution, at no point is IWampChannel.Close called, and therefore the router-side event IWampHostedRealm.SessionClosed never gets triggered. But then how can the router know that a client has been disconnected (voluntarily or not) ?

darkl, you state here : http://stackoverflow.com/questions/25260715/how-to-ping-a-websocket-server-using-a-wampsharp-client that WebSocket4Net's WebSocket sends a ping every 60 seconds. I would have expected that IWampHostedRealm.SessionClosed would have triggered after max 60 seconds in case of client crash but this is not the case. Is there a bug or am I missing something ?

**Comment by darkl** [comment]
Hi @Thad3us,

Thanks for opening this.

This bug might be related to the Fleck transport implementation.
I never checked if ping/pong messages are sent by default by Fleck.

Anyways, I'll check this and investigate this issue later, probably in a
week or so.

Do you have any code snippet that reproduces the problem? It can help.

Elad

**Comment by darkl** [comment]
You can also try vtortola WebsocketListener transport, that transport
implementation might behave differently with ping/pongs.

**Comment by Thad3us** [comment]
Thanks for the quick reply :)

Here is the client:
```c#
public static void Main(string[] args)
{
	const string serverAddress = "ws://127.0.0.1:8090";

	DefaultWampChannelFactory factory = new DefaultWampChannelFactory();

	IWampChannel channel = factory.CreateJsonChannel(serverAddress, "realm1");
	channel.Open().Wait(5000);

	IArgumentsService proxy = channel.RealmProxy.Services.GetCalleeProxy<IArgumentsService>();

	proxy.Ping();
	Console.WriteLine("Pinged!");

	Console.ReadLine();
}
```

And the router :
```c#
public static void Main(string[] args)
{
	const string location = "ws://127.0.0.1:8090/";

	try
	{
		using (IWampHost host = new DefaultWampHost(location))
		{
			IWampHostedRealm realm = host.RealmContainer.GetRealmByName("realm1");

			IArgumentsService serviceInstance = new ArgumentsService();

			 Task<IAsyncDisposable> registrationTask = realm.Services.RegisterCallee(serviceInstance, new CalleeRegistrationInterceptor(new RegisterOptions { DiscloseCaller = true }));
			// await registrationTask;
			 registrationTask.Wait();

			 realm.SessionClosed += new EventHandler<WampSessionCloseEventArgs>(delegate(object sender, WampSessionCloseEventArgs e) {
				 Console.WriteLine("SessionClosed called");
			 });
			
			host.Open();

			Console.WriteLine("Server running on " + location);
			Console.WriteLine("Press enter when done");
			Console.ReadLine();
		}
	}
	catch (Exception e)
	{
		Console.WriteLine(e.ToString());
	}
}
```

Couldn't be any simpler :)

**Comment by darkl** [comment]
Hi @Thad3us,
I've been working on this, and it should work fine in v1.2.2.9-beta.

Thanks again for reporting this issue.

**Comment by Thad3us** [comment]
Hey Elad,

Thanks a lot, it works like a charm :)

**Comment by hawkerm** [comment]
@darkl I'm seeing a similar problem with 19.1.1.

If I connect a client and then close the channel, I do get a `SessionClosed` on the router.  However, as soon as I add an RPC call from the client, I will no longer get a SessionClosed event on the router, even after waiting more than 60 seconds.

Is there someway I have to clean-up the proxy to get this to work?
