### ISSUE TITLE
How to know if someone registered to some topic?

### ISSUE THREAD

**Issue by shanielh** [Code-Sharp/WampSharp#86]
Hi.

Is there any way to know if someone is _currently_ registered to my topic? 

Thanks.

**Comment by darkl** [comment]
You can do this via realm.TopicContainer to get the topic and then check
topic.HasSubscribers property.

Please note that this api is unofficially documented and might change in
future versions. Please also note that this won't work with pattern based
subscriptions.

>

**Comment by shanielh** [comment]
Sweet. Thanks. 



—

שני.
