### ISSUE TITLE
Call into callee

### ISSUE THREAD

**Issue by hugomallet** [Code-Sharp/WampSharp#89]
Hello,

How to create a RPC method which calls itself a RPC method?

Example:
```cs
[WampProcedure("foo")]
public int foo()
{
    IArgumentsService proxy =
         realm.Services.GetCalleeProxy<IArgumentsService>();

    return proxy.Add2(3, 4);
}
```

Thanks,
Hugo

**Comment by darkl** [comment]
Looks fine. If your code gets blocked, try not to block (i.e. use async
version with tasks and async/await). I can think of a couple of cases where
the synchronous version can block the executed code.

Elad

**Comment by hugomallet** [comment]
Thanks.

Finally i have found a solution using futures.

Example:
```cs
[WampProcedure("foo")]
public Task<int> foo()
{
    IArgumentsService proxy =
         realm.Services.GetCalleeProxy<IArgumentsService>();
    Task<int> futur = TaskFactory.StartNew<int>(() => proxy.Add2(3, 4));
    return futur;
}
```

**Comment by darkl** [comment]
You should not start a new task that calls a synchronous method, that makes
a thread of your application block and wastes a thread.
Instead you should change your proxy interface to be async and return a
Task<int> instead of an int. It will not block and not waste any threads.

Elad
