### ISSUE TITLE
invalid serialization of WAMP message (unpack(b) received extra data.)

### ISSUE THREAD

**Issue by nj4x** [Code-Sharp/WampSharp#94]
invalid serialization of WAMP message (unpack(b) received extra data.)
is reported by crossbar.io router when using WampSharp (1.2.2.57-dev) as a client over the MsgpackChannel.

To reproduce:

a) Start crossbar using [.crossbar\config.json](https://gist.github.com/nj4x/13fd21e63f6949aac041)

Tested configuration:

	Crossbar.io package versions and platform information:

	Crossbar.io                  : 0.10.4

	  Autobahn|Python            : 0.10.5.post2
		WebSocket UTF8 Validator : ?
		WebSocket XOR Masker     : ?
		WAMP JSON Codec          : stdlib
		WAMP MsgPack Codec       : msgpack-python-0.4.6
	  Twisted                    : 15.3.0-IOCPReactor
	  Python                     : 2.7.10-CPython

	OS                           : Windows-8-6.2.9200
	Machine                      : AMD64

b) Open [subscriber](https://gist.github.com/nj4x/7b2ec5ebd3068c391258)
c) Run [publisher](https://gist.github.com/nj4x/23076d7cd37c428c0d24)

crossbar log file or console reports

	2015-08-28 22:16:27+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)
	2015-08-28 22:16:33+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)
	2015-08-28 22:16:39+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)

client gets no message on a subscribed topic

**Comment by darkl** [comment]
The problem seems to be related with the fact that you serialize here a byte array. If I change the type to be a string it works fine.

Will investigate this further later.

Elad

**Comment by darkl** [comment]
Seems to be an issue with the [msgpack-python](https://github.com/msgpack/msgpack-python) library which crossbar uses:

```python
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>>
>>> message = "lRDTAAAupj9xtuWAsGNvbS5zaGFycC53YW1wLjGRxIDEgFVx0td5dovKhDQunuX2s
7Z6G9hPYNlRSJJsYnMX4cxUqP+LXl8g5a1xLDwLrrTccZ7+Ogz+3Nh7IIpFDBQYsqNo2fbmalVWWjUq3
jSdRZrdkPHVGaa/VssmED7V2tiZWXmYo9S+9QZIp+DW1P6j3tvwaHwiQ5n8qIMrv1oWgX9d"
>>>
>>> bytes = base64.b64decode(message)
>>>
>>> import msgpack
>>>
>>> deserialized = msgpack.unpackb(bytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/
_unpacker.cpp:142)
msgpack.exceptions.ExtraData: unpack(b) received extra data.
>>>
```

Seems to work fine with [u-msgpack-python](https://github.com/vsergeev/u-msgpack-python) library:

```python
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>>
>>> message = "lRDTAAAupj9xtuWAsGNvbS5zaGFycC53YW1wLjGRxIDEgFVx0td5dovKhDQunuX2s
7Z6G9hPYNlRSJJsYnMX4cxUqP+LXl8g5a1xLDwLrrTccZ7+Ogz+3Nh7IIpFDBQYsqNo2fbmalVWWjUq3
jSdRZrdkPHVGaa/VssmED7V2tiZWXmYo9S+9QZIp+DW1P6j3tvwaHwiQ5n8qIMrv1oWgX9d"
>>>
>>> bytes = base64.b64decode(message)
>>>
>>> import umsgpack
>>>
>>> deserialized = umsgpack.unpackb(bytes)
>>>
>>> deserialized[4]
['\xc4\x80Uq\xd2\xd7yv\x8b\xca\x844.\x9e\xe5\xf6\xb3\xb6z\x1b\xd8O`\xd9QH\x92lbs
\x17\xe1\xccT\xa8\xff\x8b^_ \xe5\xadq,<\x0b\xae\xb4\xdcq\x9e\xfe:\x0c\xfe\xdc\xd
8{ \x8aE\x0c\x14\x18\xb2\xa3h\xd9\xf6\xe6jUVZ5*\xde4\x9dE\x9a\xdd\x90\xf1\xd5\x1
9\xa6\xbfV\xcb&\x10>\xd5\xda\xd8\x99Yy\x98\xa3\xd4\xbe\xf5\x06H\xa7\xe0\xd6\xd4\
xfe\xa3\xde\xdb\xf0h|"C\x99\xfc\xa8\x83+\xbfZ\x16\x81']
>>>
```

Please open an issue to crossbar regarding this.

**Comment by nj4x** [comment]
Thank you!
An issue has been [copied](https://github.com/crossbario/crossbar/issues/419) to crossbar

**Comment by darkl** [comment]
Hi @nj4x,

This was actually a bug in Newtonsoft.Msgpack which was fixed. A new version will be published to MyGet soon.

Now there's a new issue that seems to be related to crossbar (autobahn.js drops connection because websocket gets an error: "WebSocket connection to 'ws://127.0.0.1:2015/ws' failed: Could not decode a text frame as UTF-8."), you are welcome to open an issue for it in crossbar repository.

**Comment by nj4x** [comment]
Hi Elad,

Thank you very much!
