### ISSUE TITLE
Newtonsoft.Json versioning in nuget

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#96]
In many projects that I reference, the Newtonsoft.Json dependency is listed in nuget as >= a specific version.  In WampSharp.NewtonsoftJson it is set to = 6.0.6.  An example of where this is set to >= is https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/, where the version is set to >= 6.0.4.  Is it possible to do this in WampSharp (with a minimum of at least 6.0.5, for example)?  I'd like to avoid a cascading update of dependencies when this is possible.

**Comment by StevenBonePgh** [comment]
Looks like this could be done with a change to the nuspec based on http://docs.nuget.org/create/versioning

We'd need to change from:
<dependency id="Newtonsoft.Json" version="[6.0.6]" />
to
<dependency id="Newtonsoft.Json" version="[6.0.5,7.0.0)" />

in the Newtonsoft.Msgpack/NuGet/Newtonsoft.Msgpack.nuspec and WampSharp/NuGet/WampSharp.NewtonsoftJson.nuspec.  After the new Newtonsoft.Msgpack is published, then update the version for Newtonsoft.Msgpack in WampSharp\NuGet\WampSharp.NewtonsoftMsgpack.nuspec 

Is this something you are interested in doing?

**Comment by darkl** [comment]
Yeah, I'll do it in next release. (v1.2.3.12)
Can't promise when it will be released, but probably in late September/early-mid October.

Elad

**Comment by StevenBonePgh** [comment]
Thanks!
