### ISSUE TITLE
WampInvocationContext vs. Wamp.v1's WampRequestContext

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#98]
I'm working to move to Wamp V2, and noticed that the V1's WampRequestContext has the authenticator instance in it, but in V2's WampInvocationContext, it is not.  The WAMP specification plus your [v1.2.1.6 release notes](https://github.com/Code-Sharp/WampSharp/wiki/WampSharp-v1.2.1.6-beta-release-notes) discuss some of the details around this context.

My understanding based on the docs and a brief walkthrough of the code, I see that the sessionId is very much optional via WampInvocationContext.Current.InvocationDetails.Caller based on (both sides - not sure on this point?) agreeing to set DiscloseMe to true. 

What I need to do is audit who is making certain RPC calls, and I was using the WampRequestContext.Current.Authenticator.AuthKey and WampRequestContext.Current.Authenticator.IsAuthenticated properties to look up the user making the call via an interceptor proxy sitting over my RPC implementations.

I presume the best path forward is to maintain a mapping of sessionid to authenticated users somewhere on my side and look it up.  Where would you inject the logic to maintain this list and keep it up to date when sessions are created and destroyed?  I haven't looked at how to implement the server side WAMP v2 CRA  - I assume it is similar to V1 in that we'd get an instance of an authenticator with a session id that would enable associating the sessionid with the user.  Then handle the IWampHostedRealm.SessionClosed event to remove it?

I'd also need to make sure that DiscloseMe is always set true on the client side.  Is there a way to do this by default?

Thanks,
Steve

**Comment by darkl** [comment]
Hi,

Router-side authentication hasn't been released yet. I'm working on it in the develop branch, you can try it via MyGet feed (I posted instructions how to configure it in a couple issues). I'm working on releasing it soon in the v1.2.3.* release. (Mostly what's left is documentation and tests)
The develop version has a simple demo of WampCra.Router which you can try, and this will be improved soon with documentation.

Regarding your questions - WAMPv2 doesn't have yet a good solution for retrieving the caller authentication details in callees. (See [issue 57](https://github.com/tavendo/WAMP/issues/57))

Currently my implementation (in develop branch) passes to the callee  the authid, authrole and authmethod of the caller, in case the caller is disclosed. Once you have these details, I suggest you to write your own class that gets the authid/authmethod and checks if the user has permissions to call the procedure with given parameters. 

Note that if you want to disallow an user to call a procedure, no matter what parameters it passes, you can already do it via the IWampAuthorizer mechanism.

About setting DiscloseMe, this can be done using interceptors: See Caller identification [here](https://github.com/Code-Sharp/WampSharp/wiki/Caller-role). If you want to set it automatically via AutobahnJS, I think they have a switch for that too.

You can also use DiscloseCaller = true when registering a callee to always get caller details, see Caller identification [here](https://github.com/Code-Sharp/WampSharp/wiki/Callee-role). 

Note that DiscloseCaller option is being discussed these days in the WAMP world (see [these](https://github.com/crossbario/crossbar/issues/447) and [issues](https://github.com/crossbario/crossbar/issues/283)), so stuff are likely to change.

**Comment by darkl** [comment]
Update: I wrote some documentation: [router-side authentication](https://github.com/Code-Sharp/WampSharp/wiki/Router-side-authentication) and [WAMP-CRA router-side authentication](https://github.com/Code-Sharp/WampSharp/wiki/WAMP-CRA-router-side-authentication). You are welcome to test the develop version via MyGet feed:

In order to try it, you need to add a package source to https://www.myget.org/F/wampsharp/api/v2 (Tools -> NuGet Package Manager -> Package Manager Settings -> Packages Sources -> + button)

An official release will be released later to NuGet.
